### PR TITLE
[VAN-2018] Updating JPEG with white background

### PR DESCRIPTION
**Pull request by tylermauthe**
The previous logo-square image was a PNG and on iOS showed up with a black background - I'd like to replace with this JPEG. Thanks!

### CODE REVIEW

**Comment by phrawzty** [comment]
@mattstratton I don't think we're against this (using jpgs for logos), but if transparent PNG backgrounds are showing up black on iOS, that might be something we should look into. 😄

**Comment by mattstratton** [comment]
IIRC the docs specify a jpg for logo-square in the first place.

**Comment by tylermauthe** [comment]
I'm curious why we are required to use JPEG?

**Comment by mattstratton** [comment]
Because that’s how i coded it. There is logic that looks for a specific file name. If this is a major show stopper for you we can prioritize it into the backlog. But jpg is a better format for most logos from a performance perspective

**Comment by mattstratton** [comment]
Anyway, this is all documented. I spent a fair amount of time writing the docs which are all linked in the readme. Please read them rather than wonder why it works or doesn’t. Thanks!

**Pull request merged**
