### PR TITLE
[DC-2022] sponsor prospectus update

### PR DESCRIPTION
**Pull request by robbkidd**
Basic levels and pricing. Registration links pending.

Based on 2019 sponsor page. Keeping Media, Community, and Captions sponsorships invisible until details about them are finalized.

### CODE REVIEW

**Comment by robbkidd** [comment]
@gallimorej @trevorbryant 👀 ❓

**Comment by gallimorej** [comment]
This works. And we need to get the sponsor tiers updated in the main body to "Silver", "Gold", and "Platinum" once we have sponsors.

**Comment by robbkidd** [comment]
> we need to get the sponsor tiers updated in the template to "Silver", "Gold", and "Platinum"

@gallimorej That's easy enough to update in this PR. I'll push another change!

**Comment by gallimorej** [comment]
Excellent. Mahalo!

**Comment by MikeRosTX** [comment]
Ready for us to merge this PR @robbkidd❓🤔

**Comment by robbkidd** [comment]
Yes please and thank you, @MikeRosTX!

**Pull request merged**
