### PR TITLE
[ZRH-2018] Opening pull request for Event Zürich 2018

### PR DESCRIPTION
**Pull request by Roderick-Jonsson**
🎉  After the successful 2017 event we have decided to do the DevOpsDays in Zürich - Winterthur again for 2018 🎉

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Cool - thanks! We do need an email to info@devopsdays.org confirming the email addresses you want on the 2018 mailing lists. Those need to get set up before this is merged.

**Comment by Roderick-Jonsson** [comment]
@bridgetkromhout You got Mail ^^

**Comment by bridgetkromhout** [comment]
Great. I've corrected the places where your code of conduct was pointing to the 2017 email list.

**Comment by Roderick-Jonsson** [comment]
@bridgetkromhout As always thank you Bridget for merging so fast and correcting the error 🏆

**Pull request merged**
