### PR TITLE
[TPA-2023] Created new event for Tampa 2023

### PR DESCRIPTION
**Pull request by jmgress**
[TPA-2023] Created new event for Tampa 2023

Removed one file from 2022 and is expected.

### CODE REVIEW

**Comment by mattstratton** [comment]
the contact page doesn't match the mailing list we have right now; please send an email to info@devopsdays.org with the updated list of who should be on it and their email addresses

**Comment by mattstratton** [comment]
the current list is as follows (obfuscated for privacy)



bjorne@li***o.com
cpartington@zp**p.com
jamesgress@h***l.com
ksartain@c***e.com
saguiar@i***x.io
troykoss@g***l.com

**Comment by bridgetkromhout** [comment]
This PR has many places with 2022 that need to be changed to 2023.

**Comment by jmgress** [comment]
@mattstratton , I have sent an email with the current list of orginizers.

@bridgetkromhout , nothing that is "published" should contain 2022.  I had left a few pages alone to use as a template when we open them, like locaiton, etc.  I can update them but as of now they are not referenced in the main yml file.

**Comment by jmgress** [comment]
Recommitted with the changes from 2022 to 2023.  There is a couple of 2022 in comments and did remove one file from the 2022 event that wasn't used.

@bridgetkromhout @mattstratton  thanks for your help.

**Comment by yvovandoorn** [comment]
LGTM

**Pull request merged**
