### PR TITLE
[HOU-2020] Adding first group of speakers

### PR DESCRIPTION
**Pull request by coolblknerd**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@coolblknerd are you leaving the Speaker page off the navbar on purpose?  Just curious.

**Comment by mattstratton** [comment]
@MikeRosTX I should update the part of the docs - the speaker images do it HAVE to be square, although it’s recommended to make them that way as the grid on the speaker page will auto-crop them in the view. 

They don’t need to be made square anymore, though - it’s just a recommendation. I’ll update the docs.

**Comment by skryukova** [comment]
@MikeRosTX Yes, we are leaving speakers page off intentionally, until our Blind Bird sales end in 2 days.

**Comment by MikeRosTX** [comment]
> @MikeRosTX I should update the part of the docs - the speaker images do it HAVE to be square, although it’s recommended to make them that way as the grid on the speaker page will auto-crop them in the view.
> 
> They don’t need to be made square anymore, though - it’s just a recommendation. I’ll update the docs.

@coolblknerd - The updated docs will read as follows:

_The name of the image for this user, located in `static/events/YYYY-CITY/organizers/`. This image **must be a JPEG**, and **should be either 300px square or (optimally) 600px square**._

**Comment by skryukova** [comment]
@MikeRosTX I wanted to clarify the file format for images. I've used add_speakers.sh script, and it automatically turned all JPG files into PNG files. So, I assume that either PNG or JPEG are supported (as per @mattstratton comment above)

**Comment by mattstratton** [comment]
Yes, either PNG or JPG is supported; the script is a little bit of a blunt instrument. :)

**Comment by bridgetkromhout** [comment]
> it automatically turned all JPG files into PNG files.

The rename does not do any kind of conversion, fwiw.

**Pull request merged**
