### PR TITLE
[SITE] add logo rendering

### PR DESCRIPTION
**Pull request by toshywoshy**
Add logo rendering

- use logo.png to generate logo.webp on listing page
- use logo.png to generate logo.webp on welcome page

**This adds the asset folder for hugo rendering and requires hugo-extended**
To avoid any breakage, the old style remains supported and this adds rendering if the file exists

### CODE REVIEW

**Comment by mattstratton** [comment]
We will need to update documentation on the new Hugo version needed and ensure all scripts that load Hugo in various containers are also updated and tested.

**Comment by toshywoshy** [comment]
OK, added the new logo option to the documentation
The version of hugo defined in the workflow 0.123.3 is sufficient
All scripts are working now and all containers have been updated

**Comment by toshywoshy** [comment]
I tested this now several times, it doesn't break old, and only provides an new option

**Comment by mattstratton** [comment]
@toshywoshy this PR seems to be the code for the tix shortcode now? I think with the force push you did to this source branch it might have lost the other changes?

**Comment by toshywoshy** [comment]
Yes, that was a bad idea, still had the old files in a backup folder.
I created a new branch and enhanced the code a little, including this for all images
So I created a new PR #14341 with more options, closing
Thank you for spotting that @mattstratton

**Pull request closed without merging**
