### PR TITLE
[MVD-2019] CFP is Open, Sponsorship packages added, logo contest

### PR DESCRIPTION
**Pull request by andresantoniuk**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @andresantoniuk! Thank you for this! We will merge it. But first, please email us at info@devopsdays.org and give us the email addresses of your new team members. Thanks!

**Comment by andresantoniuk** [comment]
e-mail sent.

**Comment by MikeRosTX** [comment]
@antonbabenko, podrias cambia la página de welcome.md de la línea 39 a la 46 así?

<div class = "row">
  <div class = "col-md-2">
    <strong>Proponer</strong>
  </div>
  <div class = "col-md-8">
    {{< event_link page="propose" text="¡Proponga una charla!" >}}
  </div>
</div>

**Comment by andresantoniuk** [comment]
https://github.com/devopsdays/devopsdays-web/pull/6608#issuecomment-473491376 done!

@MikeRosTX

**Comment by antonbabenko** [comment]
@MikeRosTX si, pero @andresantoniuk voy a cambiar este.

**Pull request merged**
