### PR TITLE
[PDX-2017] Our schedule is ready!

### PR DESCRIPTION
**Pull request by BillWeiss**

### CODE REVIEW

**Comment by BillWeiss** [comment]
Please don't merge this until another of my organizers gives a thumbs up.

**Comment by jyee** [comment]
👍 LGTM

**Comment by dev-dull** [comment]
+1

**Comment by mattstratton** [comment]
@jyee I didn't look at the dimensions but we actually ask for them to be big because the gulp tasks when merging to master do resizing for retina and also optimize them.

**Pull request merged**
