### PR TITLE
[KC-2025] Initial drop of 2025 details

### PR DESCRIPTION
**Pull request by jerdog**
LFG! DevOpsDays KC 2025 is rolling!

### CODE REVIEW

**Comment by jerdog** [comment]
Waiting on a few more bits of info before this will be ready for review:

- [ ] Sponsor prospectus updates
- [ ] CFP dates

**Comment by toshywoshy** [comment]
Did you also mail info@
Also remember to change the city redirect to 2025

**Review by toshywoshy — CHANGES_REQUESTED** [review]
- Add city redirect
- Email info@

**Comment by jerdog** [comment]
> * Add city redirect
> * Email info@

City redirect previously done #14103. Info was let know of our organizers for this year.

**Review by toshywoshy — APPROVED** [review]
Redirect already completed

**Pull request merged**
