### PR TITLE
[rdu-2022] cleaning up organizers

### PR DESCRIPTION
**Pull request by normalfaults**
[rdu-2022] cleaning up organizers

### CODE REVIEW

**Comment by mattstratton** [comment]
If you have not already, please send an email to info@devopsdays.org with the changes you need to the email alias so that it is in sync with the organizers listed on the site! Thanks!

**Comment by normalfaults** [comment]
Hi @mattstratton I had sent an email to info@ the day of this pull request. Any updates on this PR and that email ?

**Comment by phrawzty** [comment]
👋 I've processed the changes to both the distribution list and the Slack workspace.

**Comment by normalfaults** [comment]
Thank you !

**Pull request merged**
