### PR TITLE
[ZRH-2017] Update Charity Majors - do-not-merge

### PR DESCRIPTION
**Pull request by Roderick-Jonsson**
Updated Charity Majors description and program

### CODE REVIEW

**Comment by drbokko** [comment]
@mattstratton @MikeRosTX could you go on with merging the pull request?

**Comment by MikeRosTX** [comment]
Sorry @Roderick-Jonsson & @drbokko but can one of you resubmit this PR?  I was trying to fix the **_title=_** that @bridgetkromhout mentioned and it reverted back to the previous.

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX I am on it

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX Done. It is referenced in our issue https://github.com/devopsdays/devopsdays-web/issues/1902 where Vittorio or Matías will give a ok

**Pull request merged**
