### PR TITLE
[BOI-2022] adds program and updates site navigation

### PR DESCRIPTION
**Pull request by ksatirli**
Hello Core Organizers 👋🏼 

This PR adds speakers and program for Boise 2022 and updates some parts of our site navigation.

(We used `add_speakers.sh` and `add_program.sh` to generate most of these files and amended them as necessary)

### CODE REVIEW

**Comment by ksatirli** [comment]
Question for reviewers: this PR adds the schedule, but it doesn't show on https://deploy-preview-11141--devopsdays-web.netlify.app/events/2022-boise/program

Locally, the schedule renders as expected. 

Are we missing something in this PR?

**Comment by mattstratton** [comment]
I’ll be happy to merge as is, but make the follow of recommendations (later if you want)

- remove the “propose a talk” from the welcome.md
-  add “speakers” to your nav elements in your data file.

**Comment by ksatirli** [comment]
Thanks @mattstratton!

We do plan on adding speakers back to the main nav, as soon as we've collected all speaker pictures.

**Comment by mattstratton** [comment]
Cool! Would def remove the propose link though :)

**Comment by ksatirli** [comment]
Absolutely agreed @mattstratton - added this in https://github.com/devopsdays/devopsdays-web/pull/11154

**Pull request merged**
