### PR TITLE
CPH 2018 Added speaker section and sponsors

### PR DESCRIPTION
**Pull request by mariuszbury**
This pull request includes the changes from https://github.com/devopsdays/devopsdays-web/pull/4025, which were reverted due to a submodule being added by mistake.

### CODE REVIEW

**Comment by kmugrage** [comment]
@mariuszbury this PR adds the program page to the navigation, but doesn't include the program page itself. This results in a 404 error if people click that link.

**Comment by mariuszbury** [comment]
@kmugrage Where's the devil in these details? I could not see or overlooked that part of readme, which says how to do it. Have tested everything in Hugo, and it seemed to be okay though.

**Comment by kmugrage** [comment]
There's a script called add_program.sh in the utilities directory which will help.

What it's doing...
Adding the fields from https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#program-fields to your event data file.

Creating a program.md file in your event directory which will be auto-filled by hugo from that data

You can see examples from the theme at https://github.com/devopsdays/devopsdays-theme/blob/master/exampleSite/data/events/2017-ponyville.yml as well.

**Comment by bridgetkromhout** [comment]
@kmugrage explained how to create the program file. If you would like to have someone walk you through it, please ask on devopsdays organizer Slack. For now, I removed the program link that doesn't go anywhere.

**Pull request merged**
