### PR TITLE
[BOS-2018] new speaker pics

### PR DESCRIPTION
**Pull request by technovangelist**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Do you want to enable the Speaker navbar?

**Comment by MikeRosTX** [comment]
Make sure pic size meet specs:
https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md#speaker-page-fields

**Comment by bridgetkromhout** [comment]
Hi, @technovangelist - if you want to take a look at https://deploy-preview-5160--devopsdays-web.netlify.com/events/2018-boston/welcome/ you can see all the fixes I made in https://github.com/devopsdays/devopsdays-web/pull/5160. If you approve my PR, I'll merge it and resolve any discrepancies.

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/devopsdays/devopsdays-web/pull/5166 - also, keep in mind for future reference that if you add pictures that aren't square, they will be auto-cropped, so you probably would prefer to crop them to your liking ahead of time .

**Pull request closed without merging**
