### PR TITLE
Release new theme

### PR DESCRIPTION
**Pull request by bridgetkromhout**
To be merged after the new theme is released - per https://github.com/devopsdays/devopsdays-web/issues/1947

### CODE REVIEW

**Comment by devopsdays-service** [comment]
@bridgetkromhout, thanks! Based upon the content in this PR, we need a review from @mattstratton and @bridgetkromhout

**Comment by bridgetkromhout** [comment]
Hey @mattstratton I looked at https://github.com/devopsdays/devopsdays-web/pull/1910/files and that move doesn't put the speaking.md file into the same path it currently lives over in devopsdays-theme. Over there, it's no longer under "page". Can you clarify what's right? Thanks.

**Comment by mattstratton** [comment]
It doesn't seem to actually matter, so I'll leave it as is.

**Comment by mattstratton** [comment]
Hm.. On the deploy preview, the order is jacked up in the sidebar. Same issue we have had before.

**Pull request merged**
