### PR TITLE
[BUF-2023] Add 2023 event with TBD date/location

### PR DESCRIPTION
**Pull request by ryansb**

### CODE REVIEW

**Comment by mattstratton** [comment]
This seems to be missing the datafile?

**Comment by mattstratton** [comment]
This is definitely missing a few things. Did you use the https://github.com/devopsdays/devopsdays-web/blob/main/utilities/add_new_event.sh script to generate it?in  addition to the files in the `content` directory you need a file in the `data/events` directory

**Comment by mattstratton** [comment]
This might be helpful reference:
https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#events

**Comment by ryansb** [comment]
@mattstratton thank you for the tip, I didn't add the data file in git. 😓 

Please take another look.

**Comment by mattstratton** [comment]
One more! You should update https://github.com/devopsdays/devopsdays-web/blob/df330505d39a922fc1d75a931c07e56d8ddb6911/static/_redirects#L20 to point to the 2023 version

**Comment by mattstratton** [comment]
77DB08E7-8A08-493A-82E3-19CABED3700D

broken image hmm

**Comment by mattstratton** [comment]
> 77DB08E7-8A08-493A-82E3-19CABED3700D
> 
> broken image hmm

This image is missing 
https://github.com/devopsdays/devopsdays-web/blob/a244357df5647ce07e3184ff36e0a644b4647d17/content/events/2023-buffalo/welcome.md?plain=1#L69

**Comment by mattstratton** [comment]
> This image is missing
> 
> https://github.com/devopsdays/devopsdays-web/blob/a244357df5647ce07e3184ff36e0a644b4647d17/content/events/2023-buffalo/welcome.md?plain=1#L69

Please make sure to put it in `/static/events/2023-buffalo` etc not the main content directory also!

**Comment by ryansb** [comment]
Thanks @mattstratton - I think I've got it all fixed up, and the preview correctly shows the image.

**Pull request merged**
