### PR TITLE
[Silicon Valley- 2018] Adding 2018 Silicon Valley event.

### PR DESCRIPTION
**Pull request by iennae**
Initial creation of the Silicon Valley event site.

### CODE REVIEW

**Comment by iennae** [comment]
@pmoosh and @irabinovitch Please take a look.

**Comment by bridgetkromhout** [comment]
Are we waiting for any specific 👍 to merge this? Thanks.

**Comment by bridgetkromhout** [comment]
Ah, `content/events/2018-siliconvalley` should be `content/events/2018-silicon-valley` with a hyphen. Can't change that in the online editor.

**Comment by iennae** [comment]
@bridgetkromhout I used the new script, but I did siliconvalley rather than Silicon Valley or silicon-valley as input. (Might be misunderstanding what you mean by the new script does the dashes though)

**Comment by bridgetkromhout** [comment]
>  I did siliconvalley rather than Silicon Valley or silicon-valley as input. 

Ah, that's why. It would have changed "Silicon Valley" into "silicon-valley". 

Is this ready to merge now? Thanks.

**Comment by iennae** [comment]
I think so, thanks!

**Pull request merged**
