### PR TITLE
BOG-2022 Event added

### PR DESCRIPTION
**Pull request by rrmartinez87**
Hi team

Please check our changes to add the 2022 event files.

Thanks

### CODE REVIEW

**Comment by yvovandoorn** [comment]
Hi @rrmartinez87,

Exciting that y'all are putting up another event. Unfortunately I can't merge the PR as is. 

I suggest visiting https://devopsdays.org/organizing for a good reminder of whats needed for the initial PR. Some missing bits are:

- Lack of dates
- Lack of venue information (is the venue confirmed?)
- PR has sample team members, rule is at least 3 from three different companies/employers/contractors.

The above link should get you to a place for a more complete PR. Feel free to commit against this open PR and do a "@yvovandoorn" when ready for review.

**Comment by yvovandoorn** [comment]
Hi @rrmartinez87 I'll be closing this PR at the end of this week if no further changes are committed to this branch.

**Comment by rrmartinez87** [comment]
Hi

This week I will be working on the changes

Thanks

**Comment by mattstratton** [comment]
@rrmartinez87 to clarify, it's okay to have the PR in without dates or a venue (the event will just show up as TBD for now)

but as yvo said, we definitely need the organizers, and they need to match the people who are on the `bogota@devopsdays.org` email alias. You can email us at info@devopsdays.org if any changes need to be made to that mailing list!

**Comment by yvovandoorn** [comment]
> Hi
> 
> This week I will be working on the changes
> 
> Thanks
> 
> El mar, 1 mar 2022 a las 3:29, Yvo ***@***.***>) escribió:
> 

Great @rrmartinez87! For the initial PR we just need a list of organizers. **Venue and dates can come later. **

**Comment by rrmartinez87** [comment]
Hi Matt & Team

For devopsdays bogota 2022 the mailing list will be the same as last year

As Matt indicates I will send the email indicating this to
***@***.***

Additionally we will upload today the changes with the dates and place for
the event


Thanks

**Comment by rrmartinez87** [comment]
We have added additional information for our event, date, location, logos, and other additional data

Thanks

**Comment by yvovandoorn** [comment]
This looks good now. Merging.

**Pull request merged**
