### PR TITLE
[LA 2022] add edge delta as sponsor

### PR DESCRIPTION
**Pull request by irabinovitch**
[LA 2022] add edge delta as sponsor

### CODE REVIEW

**Comment by glasnt** [comment]
New sponsor logos have to be `.png`, if you can rename that file, then this PR will be good to go 👍

**Comment by mattstratton** [comment]
@irabinovitch as @glasnt mentioned, the image has to be a PNG for sponsors:

image

**Comment by irabinovitch** [comment]
Will fix soon. Just traveling right now.

**Comment by mattstratton** [comment]
Sure! My comment wasn't to bug you, just to show why :)

**Comment by yvovandoorn** [comment]
This was an accidental merge, please re-open a PR with the png file. Apologies @irabinovitch for the extra work.

**Pull request merged**
