### PR TITLE
[2024-LON] Add the first sponsors!

### PR DESCRIPTION
**Pull request by issyl0**
With thanks to Cloudsmith and Commify!

### CODE REVIEW

**Comment by issyl0** [comment]
Ah. The Cloudsmith logo is not the one they said they wanted... 🤔 But presumably it _is_ the one they want on the other things they're sponsoring? Or was it just a random one that PDX-2021 and BER-2024 used? How should we update this?

We have:

image

And they want:

CloudsmithLogo--RGB_Transparent@M@2x

**Comment by adrianmoisey** [comment]
There is a script that handles this situation for us. Take a look at https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data

**Comment by glasnt** [comment]
We're waiting for your scripted changes to this PR. If you need a hand, let us know!

**Comment by issyl0** [comment]
I forgot about this - sorry. Done now.

**Comment by issyl0** [comment]
I assumed that Cloudsmith's new logo was intended for Berlin 2024 as well, but the Berlin organizers can revert to the old logo if needed - I'll let them know in Slack.

**Pull request merged**
