### PR TITLE
Sponsor update for Montreal 2022

### PR DESCRIPTION
**Pull request by purpleidea**
Thank you!

### CODE REVIEW

**Comment by yvovandoorn** [comment]
I think you need to remove the origins that say `master` and add the `main` origin. Something like `git remote remove origin` then `git remote add <new origin>`. 

Then pull, rebase your branch, and it should be a far cleaner PR.

**Comment by adrianmoisey** [comment]
I changed the PR to merge into `main` instead of `master`, and it looks neater now.

**Comment by adrianmoisey** [comment]
@purpleidea are you happy if we merge this now?

**Comment by purpleidea** [comment]
Yes thank you1

**Comment by purpleidea** [comment]
btw @yvovandoorn 

```
$ git remote show origin 
* remote origin
  Fetch URL: https://github.com/devopsdays/devopsdays-web/
  Push  URL: https://github.com/devopsdays/devopsdays-web/
  HEAD branch: main

```

hmm.

**Review by glasnt — APPROVED** [review]

**Pull request merged**
