### PR TITLE
[SLC-2020] Initialize next year's conference

### PR DESCRIPTION
**Pull request by Clait**
Copy 2019 files and change dates and info for setting up our 2020 event.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I've updated email and Slack to match the contents of this PR.

**Comment by Clait** [comment]
Thanks Bridget - we have new members for the board incoming. Will post
another PR in the coming weeks for that.

**Comment by bridgetkromhout** [comment]
That's fine. We need an email with their names/email addresses at the same time as the PR.

**Comment by Clait** [comment]
> That's fine. We need an email with their names/email addresses at the same time as the PR.

sounds good

**Pull request merged**
