### PR TITLE
Add 2016 chicago blog post

### PR DESCRIPTION
**Pull request by mattstratton**

### CODE REVIEW

**Comment by mattstratton** [comment]
The deploy preview link doesn't quite work, so if you want to review the post, the link to look at is http://deploy-preview-1514--devopsdays-web.netlify.com/blog/2016/12/12/chicago-2016-in-review/

**Comment by MikeRosTX** [comment]
Great blog.

**Comment by mattstratton** [comment]
Hold off on merging this, as @bridgetkromhout and I are bikeshedding over something...

**Comment by bridgetkromhout** [comment]
I'm fine with pushing the bikeshedding over URLs to the future in the interests of getting this merged. :)

**Pull request merged**
