### PR TITLE
[Natal - 2024] Update sponsor, insert link to CFP and insert new organizers

### PR DESCRIPTION
**Pull request by luancarlos021**
- Update sponsor
- Insert link to CFP 
- Insert new organizers

### CODE REVIEW

**Review by toshywoshy — CHANGES_REQUESTED** [review]
Please move the organizer images to `assets/events/2024-natal/organizers/1

**Comment by toshywoshy** [comment]
I have also added a verification for organiser change so Core will need to aprove this

**Comment by luancarlos021** [comment]
@toshywoshy, organizer images moved to `assets/events/2024-natal/organizers/`

**Comment by toshywoshy** [comment]
Can someone confirm the change of organizers from @core then we can merge this

**Comment by luancarlos021** [comment]
> Can someone confirm the change of organizers from @core then we can merge this

@gomex ;)

**Comment by nimbinatus** [comment]
@luancarlos021, you need to send an email to the info@ mailing list with organizer changes. The alias you're tagging in your messages is not DevOpsDays Global Core; we're `@devopsdays/core-active`, but all changes *must* go through email as documented here: https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#local-organizers, the last paragraph.

**Comment by luancarlos021** [comment]
@nimbinatus, thanks for the info ;) 

Email sent with the list of organizers to info@devopsdays.org

**Comment by nimbinatus** [comment]
Found the email; core work complete. Safe to merge!

**Review by nimbinatus — APPROVED** [review]
LGTM

**Pull request merged**
