### PR TITLE
Adding sponsors & update speaker pictures for Raleigh

### PR DESCRIPTION
**Pull request by mrry550**

### CODE REVIEW

**Comment by mattstratton** [comment]
Is there a reason for creating a new `2016-chef.png` instead of the `chef.png` that is already there? I realize this could be a bikeshed...

**Comment by kmugrage** [comment]
Can we please adjust the images to the sizes from the README? 200px by 200px for the new logo and 500px wide for the speaker image. Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @mrry550 -

* We'll make the guidelines more clear, but do not use `2016-` before sponsors. Just use the sponsor name. Chef already exists, as @mattstratton pointed out. Change the other one, please, to remove the `2016-`.
* As @kmugrage points out, we're trying for images of a certain size. (I understand sometimes that's hard to do with speakers & sponsor logos.)
* I added Katie to the email list (she's already on Slack), so that part is fine to merge.

I marked this entire PR as "do not merge" because you're adding a new Chef sponsor that shouldn't be added. We can merge when that's fixed.

**Comment by mrry550** [comment]
@bridgetkromhout - should I fixed all of the other 2016- sponsors that I added with the other PRs I submitted? I'm just trying to be clear about which format you'd like us to use since I'm seeing 2016 all over the repo and was just trying to follow suit. Also, I added several other sponsors this way. Am I meant to back those changes out?

**Comment by mrry550** [comment]
@bridgetkromhout - I updated the sponsors for the ones I just added. Let me know about the rest of them- there are 5 other sponsors that I had formatted that way in previous merged PRs. In terms of the speaker images, can we just merge them as is for now? I have asked for the logos to be a certain size, but they are not sending them over that way. I'd rather not refuse to update especially if we are holding onto cash.

**Comment by bridgetkromhout** [comment]
> should I fix all of the other 2016- sponsors that I added with the other PRs I submitted that were already merged?
> Also, I added several other sponsors this way. Am I meant to back those changes out?

Naw, we iterated a few times before we settled on what we want to try to do, so don't worry about anything that's gone before. Any more refactoring won't be something you'll have to worry about.

I won't hold any PR over image size (although if aspect ratios are wrong, they'll look bad). This one's merged now.

**Pull request merged**
