### PR TITLE
Remove config.toml from .gitignore

### PR DESCRIPTION
**Pull request by mattstratton**
When the `config.toml`is in `.gitignore`, it means that folks who do a `git pull` won't get any updates. This is going to be a big problem when we release the new theme.

However, my concern is with people making changes to this file. We need to watch for changes on this file before merging PR's.

I need a couple 👍  from maintainers before this gets merged.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
👍  We just have to watch if we can't add a post-commit hook or something to warn us.

**Comment by mattstratton** [comment]
@bridgetkromhout I want a hook like that for other files too, so I think we're okay right now. 

I kinda want an easy way to get a message to everyone who has commit bits on this repo; github notifications aren't reliable because people turn them off. Anyway, that's a problem for another day. I'll merge this once I get one more 👍

**Comment by MikeRosTX** [comment]
@mattstratton my concern for adding **config.toml** in to **.gitignore** was because I was doing all my changes in Windows and every time I changed the **PathSeparator** to **\\** it wanted to merge into the main branch. I'm a little unclear how we should making these changes to work in all environments without affecting the main branch.

**Comment by mattstratton** [comment]
Based upon the conversation I just had with @MikeRosTX, what we need to do is create a `config-windows.toml` which looks just like the `config.toml` but has the `PathSeparator` set for the Windows version.

Then when someone wants to run on windows, they run `hugo -w -b "https://localhost:1313 --config windows-config.toml`.

The only thing this means is we have to keep both config files in sync, but they change rarely.

I'll keep this PR open until I can create and test that Windows config file.

**Comment by mattstratton** [comment]
OK I think it worked; insomuch as I tried pointing to that config file using that flag on my Mac and it blew up. 

i'll make one more documentation change before merging.

**Comment by mattstratton** [comment]
I think I caught it all.

**Comment by mattstratton** [comment]
I just tested this on Windows and it works, so I am gonna merge this.

EVERYONE WATCH OUT FOR PR's WITH THESE FILES.

**Pull request merged**
