### PR TITLE
Testing Netlify deprecation of Asset optimization

### PR DESCRIPTION
**Pull request by jerdog**
With Netlify's upcoming [deprecation of Asset optimization](https://answers.netlify.com/t/please-read-deprecation-of-post-processing-asset-optimization/96657), some prep needs to happen. An early step is to see what happens when we [turn off asset optimization](https://answers.netlify.com/t/please-read-deprecation-of-post-processing-asset-optimization/96657#how-can-i-run-a-test-build-without-asset-optimization-4).

This first step will be testing against Deploy Previews, and done after conversation with @mattstratton and myself in Slack.

### CODE REVIEW

**Comment by jerdog** [comment]
ffs - there are changes from a new branch that need removed... but it won't really matter since this just tests what happens with the deploy preview when asset optimization is turned off

**Comment by jerdog** [comment]
So this doesn't use cloudfront.net anymore

Screenshot 2023-08-31 at 3 06 04 PM

**Comment by jerdog** [comment]
The builds will be quicker, but (and borrowing Matty's analysis) since Netlify isn't handling the asset fingerprinting, it will negatively effect site performance, especially for those not in North America. Netlify's change here means that we will have to handle it ourselves.

**Comment by mattstratton** [comment]
okay so i'm super confused bc we already skip processing on branch deploy and deploy prview

```
 [context.deploy-preview]
  command = "bin/netlify.sh"
  publish = "public/"
  skip_processing = true

 [context.branch-deploy]
  command = "bin/netlify.sh"
  publish = "public/"
  skip_processing = true
```

**Comment by mattstratton** [comment]
handled in #13224

**Pull request closed without merging**
