### PR TITLE
[CHA-2019] Adds JJ Asghar as a speaker

### PR DESCRIPTION
**Pull request by asachs01**
Add's JJ's speaker page.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
- The resizing doesn't work if the extension is `.jpeg` instead of `.jpg`.
- Are we sure we want speakers talking about "flirting" with technologies in their bio? There are better ways to express that (like "experimenting").
- The bio (other than that) has errors like "he’s always to convince" and "madding Dwarf Fortress".

**Comment by asachs01** [comment]
Good call out. That's on me for blindly copy/pasting from what was
supplied. I'll take a look over it later tonight.

**Comment by bridgetkromhout** [comment]
Hi, @asachs01 - we want to get this merged for you, and we're hoping you can take a look at this and make any adjustments you'd like to make - thanks!

**Comment by asachs01** [comment]
👍👍 I had to make an unexpected trip to help some family yesterday. I'll
try and take a gander tonight and get those adjustments in.

**Comment by asachs01** [comment]
@bridgetkromhout I'm going to go back to the speaker with the feedback and see if I can have the bio resubmitted with corrections. Let's just close this for now and I'll have a new PR once I've got the corrections from him.

**Pull request closed without merging**
