### PR TITLE
Use latest Hugo - v0.55

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Just like the last one.. https://github.com/devopsdays/devopsdays-web/commit/55e25671ac1c951f5d500705d23a41fe1a595d4f

**Comment by ghoneycutt** [comment]
with the addition of circleci config

**Comment by ghoneycutt** [comment]
cc @mattstratton

**Comment by ghoneycutt** [comment]
Should we use 55.1 for consistency?

**Comment by mattstratton** [comment]
Let's see if 55.2 builds in netlify - there are bugfixes in it, so I'd rather use that if we can (although the docker images aren't updated yet)

**Comment by mattstratton** [comment]
This all looks good in preview! Great job, @ghoneycutt !

**Pull request merged**
