### PR TITLE
[SSA-2017] Add Thiago Colares as a organizer

### PR DESCRIPTION
**Pull request by colares**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@colares before we can add you as an organizer and merge this PR, we need the lead organizer to send an email to info@devopsdays requesting your email be added to the team email and Slack.

**Comment by colares** [comment]
@MikeRosTX Sure! He told about it :) I've just let him know about the PR so he'll an email soon

**Comment by colares** [comment]
@gomex

**Comment by gomex** [comment]
I already created another PR to add Colares and another guy #3256  please ignore this PR here

**Comment by MikeRosTX** [comment]
Closing this PR per @gomex request, see  #3256.

**Pull request closed without merging**
