### PR TITLE
[SEA-2023]  Location updates etc

### PR DESCRIPTION
**Pull request by harbinger55**
- Add organizer Mia Villasenor
- Add location
- Add Dates
- Add "hidden" sponsor-info page

### CODE REVIEW

**Comment by jyee** [comment]
Small nit on this PR, but we should probably update Mia's last name from `Villasenor` to `Villaseñor`

**Comment by davenash-lytx** [comment]
I just copied & pasted it from our slack channel, but I will check in with Mia and update it to the correct character set

**Comment by villasenor** [comment]
Thanks @jyee - either one works! Depending on the system, I sometimes omit it because the first ASCII standard (X3.64-1963) did not have a tilde, and `ñ` was not added officially until Part 1 of ISO/IEC 8859 (extended ASCII) in 1987 so I often worry about support for the character in poorly designed systems. If it's easy to add, that's great, but if not no worries @harbinger55

**Comment by jyee** [comment]
Haha, be like my friend Jérôme and be an agent of chaos!

(small note that he also will insert emojis into his name to try to break systems 😆 )

**Pull request merged**
