### PR TITLE
[TLV-2021] Yay! New Sponsors Announced

### PR DESCRIPTION
**Pull request by shar1z**
Thank you very much for merging our previous PR.  Really excited to be able to announce new sponsors already!

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
To resolve the merge conflicts you probably want to pull in changes from upstream. See  https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#editing-your-site for how to fix this.

**Comment by shar1z** [comment]
Thanks Bridget - my upstream is set correctly - not sure why I always have drift.  Should be fixed now, I hope.  Trying again.

**Comment by shar1z** [comment]
Hey - I don't have any merge conflicts on my end to resolve.  I've rebased a bunch of times.

Let me know if there's anything else I can / should do - this is true when I checkout my tlv-2021 branch too. 
I don't have any merge conflicts to fix on my end - so perhaps we can just confirm the new files committed?  I imagine those are the correct ones - if the conflicts are solely with TLV-2021 files (our yml and sponsors images).

Worst case I'll see they're the wrong ones, and I'll push the new ones again.


====================================================

See local log:


Your branch is up to date with 'upstream/main'.

nothing to commit, working tree clean
shar1z@Sharones-MBP devopsdays-web % git pull
Already up to date.
shar1z@Sharones-MBP devopsdays-web % git pull upstream main --rebase

From github.com:devopsdays/devopsdays-web
 * branch                  main       -> FETCH_HEAD
Already up to date.
Current branch main is up to date.
shar1z@Sharones-MBP devopsdays-web % git pull                       
Already up to date.
shar1z@Sharones-MBP devopsdays-web % git status
On branch main
Your branch is up to date with 'upstream/main'.

nothing to commit, working tree clean
shar1z@Sharones-MBP devopsdays-web %

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/devopsdays/devopsdays-web/pull/10458

**Pull request closed without merging**
