### PR TITLE
[ZRH-2020] Update speakers

### PR DESCRIPTION
**Pull request by RomanoRoth**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by glasnt** [comment]
It looks like your program is incomplete, do you intend to add more information to this PR?

**Comment by RomanoRoth** [comment]
Hi @glasnt 
No I will not add more information to this PR. 
I will create new branches and PR when I received more informations from the other speakers.

**Comment by glasnt** [comment]
Okay, I've merged it for now. You may also want to make sure the CFP information from the March event is removed, given you're moving to a new format.

**Comment by RomanoRoth** [comment]
Perfect. Thank you. I will do so.

**Pull request merged**
