### PR TITLE
[AMS-2024] Add Picnic, update Okta

### PR DESCRIPTION
**Pull request by FloorD**
Adding Picnic as our final Silver sponsor, and updating Okta's logo. I did a grep and didn't see Okta as a sponsor for any other event which... surprised me, but I guess that means we're good?! :)

### CODE REVIEW

**Comment by adrianmoisey** [comment]
You also need to add the "okra-before..." yaml file for the old image, and update older events (Amsterdam 2022) to use it.
There is a script somewhere that does all this

**Comment by FloorD** [comment]
@adrianmoisey right, sorry, thanks!

**Comment by adrianmoisey** [comment]
The previous event now needs to refer to the old Okta sponsor yaml file

**Comment by timothymamo** [comment]
Hi I created a [new PR](https://github.com/devopsdays/devopsdays-web/pull/14163) to add the Picnic and the new Okta logo as @FloorD is at a conference and has limited time to look at this. Please close this PR

**Pull request closed without merging**
