### PR TITLE
[ZRH-2021] Added the DevOpsDays Zuerich 2021

### PR DESCRIPTION
**Pull request by RomanoRoth**
Note: We will re-shedule the DevOpsDays Zuerich 2020 to DevOpsDays Zuerich 2021
Announcement is ongoing. 
Instead of the DevOpsDays Zuerich 2020 we will do a DevOpsTuesDays Zuerich 2020 in September. 
Announcement is pending.

### CODE REVIEW

**Comment by RomanoRoth** [comment]
Hello
Could someone merge this pull request?

**Comment by RomanoRoth** [comment]
Hello?
Anybody out there?

**Comment by bridgetkromhout** [comment]
As I mentioned on Slack, the all-volunteer core team works on PRs as soon as we can. I haven't had time to review this one yet. Likely over the weekend is when I can, if someone doesn't beat me to it.

**Comment by RomanoRoth** [comment]
👍 no problem. thank you for the great work!

**Comment by yvovandoorn** [comment]
Hey @RomanoRoth,

Could you merge the other PR (https://github.com/devopsdays/devopsdays-web/pull/9753) into this one? Once the two are combined, I'll review and approve.

**Comment by RomanoRoth** [comment]
Hi @yvovandoorn 
I've merged it.

**Pull request merged**
