### PR TITLE
[GHENT-2019] Launch logo & program

### PR DESCRIPTION
**Pull request by yvovandoorn**
* Reveal logo for 2019 Ghent
* Launch program
* Add missing talks
* Cleanup welcome page / remove mailing list
* Go!

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hey, @yvovandoorn - are you sure you want to put Ken on the schedule twice with the same talk? https://deploy-preview-8354--devopsdays-web.netlify.com/events/2019-ghent/program for reference.

Also, I try to livetweet everyone, but I usually have to decompress immediately after I speak - if that matters, you might want to swap my timeslot with Jabe's - just a thought!

**Comment by bridgetkromhout** [comment]
Ah, the logo-square file needs to actually be square or it will get stretched to be square when it's on the front page after it has gone through the build process (this won't show up in the preview). I recommend pasting the image onto a blank or white square of the correct size.

**Comment by yvovandoorn** [comment]
@bridgetkromhout thanks for catching the double Ken talk and non square logo. I've also swapped you with Jabe!

**Comment by jedi4ever** [comment]
@yvovandoorn not sure there is a type ignite? or did they not get listed here

**Comment by yvovandoorn** [comment]
@jedi4ever the type ignite doesn't allow for specific times (only something for program/talks). So I had to compromise on using the 'talk' type with a specific background color.

**Pull request merged**
