### PR TITLE
[CHI-2018] Add Hangzhou,Shanghai,Shenzhen,Chengdu,Xi'an in China

### PR DESCRIPTION
**Pull request by xiaotianguo**
[CHI-2018] Add Cites:Hangzhou,Shanghai,Shenzhen,Chengdu,Xi'an in China
We are the organizer of DevOpsDays Beijing And Shanghai in 2017. The DevOps community in China really loves this event to promote DevOps in China, As the core member of DevOps community in China, we would like to host DevOpsDays in more cites in China to spread DevOps in this country.
Thanks.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I'll try to look through all this tomorrow!

**Comment by bridgetkromhout** [comment]
Hi, @xiaotianguo - most of this is fine but we will need the venue location for each city before we can publish dates. Thanks!

**Comment by bridgetkromhout** [comment]
Hi, @xiaotianguo - I tried to email you, but I don't have your correct email address. Please email info@devopsdays.org about who is on your organizer list. Thanks!

**Comment by xiaotianguo** [comment]
@bridgetkromhout I'not sure why do you revert my PR.please tell me the reason and I'll update the information ASAP. And I'm the organizer of DevOpsDays Beijing and Shanghai in 2017, The community have done lots of things to promote DevOps and DevOpsDays in China.We have confidence to do it more successful in 2018.

**Comment by KrisBuytaert** [comment]
@xiaotianguo  because @jedi4ever  and I just sat down with Sun Zhenpeng and he explained us that you are not involved in the organisation anymore.

**Comment by bridgetkromhout** [comment]
What @KrisBuytaert said is correct. @xiaotianguo, if you would like to email info@devopsdays.org we can clarify there.

**Comment by xiaotianguo** [comment]
Apologize that recently we can not use gmail for some special reasons. Truly, Some misunderstanding happened. Actually we love DevOpsDays and are very happy to meet with @KrisBuytaert and @jedi4ever last year in China. I will email info@devopsdays.org sooner.

**Comment by xiaotianguo** [comment]
Apologize that recently we can not use gmail for some special reasons.
Truly, Some misunderstanding happened. I will email info@devopsdays.org
sooner.

2018-01-26 12:02 GMT+08:00 Bridget Kromhout <notifications@github.com>:

**Pull request merged**
