### PR TITLE
[SHA-2019] Add 2019-Shanghai event

### PR DESCRIPTION
**Pull request by overloadzy**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @overloadzy - this appears to be a completely different team from last year; please email us at info@devopsdays.org. We definitely need the organizer info to be clear before merging a new event - thanks.

**Comment by bridgetkromhout** [comment]
Waiting for clarification via email.

**Comment by overloadzy** [comment]
> email



> Waiting for clarification via email.

**Comment by bridgetkromhout** [comment]
Sun Zhenpeng has given us the necessary email addresses, and I'm setting this up now.

**Comment by overloadzy** [comment]
> Sun Zhenpeng has given us the necessary email addresses, and I'm setting this up now.

Dear @bridgetkromhout Thanks for your great support!

**Comment by bridgetkromhout** [comment]
> Dear @bridgetkromhout Thanks for your great support!

Hi, @overloadzy - thanks for your great work supporting devopsdays in China! I am merging this PR after https://github.com/devopsdays/devopsdays-web/pull/7865 finishes building, so we can avoid having broken images.

Just checking, is your Shanghai 2019 event a one-day event? It looks that way, but since it was a two-day event in 2018, I want to make sure that's correct.

**Comment by overloadzy** [comment]
> > Dear @bridgetkromhout Thanks for your great support!
> 
> Hi, @overloadzy - thanks for your great work supporting devopsdays in China! I am merging this PR after #7865 finishes building, so we can avoid having broken images.
> 
> Just checking, is your Shanghai 2019 event a one-day event? It looks that way, but since it was a two-day event in 2018, I want to make sure that's correct.

Hi, @bridgetkromhout Yes, Shanghai 2019 event is a one-day event. Thanks for your help again , we will do our best to promote devopsdays in China persistently.

**Comment by bridgetkromhout** [comment]
Great! Okay, I am merging this now. It should build in about 10-15 minutes or so. I added a link to your local site too. Feel free to customize your page on the international site however it makes sense to you - I suggest adding pictures for your new team members, if you want.

**Pull request merged**
