### PR TITLE
Change to organizing doc to encourage default program

### PR DESCRIPTION
**Pull request by kmugrage**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I like this. It’s succinct but covers the necessary info.

**Comment by nathenharvey** [comment]
Could we link to a previous schedule to help illustrate?

**Comment by nathenharvey** [comment]
Maybe this?

>DevOps encourages the free flow of information, sharing experiences, and communication among peers.  The recommended structure of events reinforces and amplifies these practices.

> First time events should consult with a core organizer before altering the format.  Doing so will ensure organizers benefit from our experience organizing and attending DevOpsDays all over the world.

**Comment by MikeRosTX** [comment]
👍 👍 👍

**Comment by kmugrage** [comment]
I like it @nathenharvey - mind adding a commit? 

> Maybe this?
> 
> > DevOps encourages the free flow of information, sharing experiences, and communication among peers.  The recommended structure of events reinforces and amplifies these practices.
> 
> > First time events should consult with a core organizer before altering the format.  Doing so will ensure organizers benefit from our experience organizing and attending DevOpsDays all over the world.

**Comment by nathenharvey** [comment]
@kmugrage I don't mind but won't be in a place where I can until tomorrow morning.

**Comment by nathenharvey** [comment]
@kmugrage changes pushed to this PR.

**Comment by nathenharvey** [comment]
chatted with @kmugrage via slack.  we are good to merge.

**Pull request merged**
