### PR TITLE
FOR - 2019 - Add Speaker Marcelo Andre and Move sponsor img to right place

### PR DESCRIPTION
**Pull request by gb8may**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by mattstratton** [comment]
Can you please remove the extra YAML files (looks like they are kubernetes related?) from this commit?

**Comment by mattstratton** [comment]
Additionally, the title of this PR doesn't seem to match the changes you made. Please update.

**Comment by gb8may** [comment]
What extra YAML files?

**Comment by mattstratton** [comment]
Look at the changed files to see the files added in this commit:

https://github.com/devopsdays/devopsdays-web/pull/7730/files

**Comment by gb8may** [comment]
Wow.. I didn’t saw this.. i’ll close this PR and create a new one with right files!

Mayara Gouveia
DevOps Engineer
Information Security Specialist
DevOps Professional | Agil Scrum Foundation CompTIA Network+ | Ethical Hacking Foundation | Fortinet NSE1
DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 Puppet ID: PPT0005371

**Pull request closed without merging**
