### PR TITLE
[Baku-2019] Added new organizer

### PR DESCRIPTION
**Pull request by NasehBadalov**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Anytime a new organizer is added or removed, please send an email to info@devopsdays.org to let us know their full name and email. Once this is completed, we will proceed with the merge of this PR.

**Comment by NasehBadalov** [comment]
Thanks for informing. Should I close this and send a new pull request in the future or you will merge it after we send an email?

**Comment by MikeRosTX** [comment]
We will merge this PR after receiving the email.

**Comment by MikeRosTX** [comment]
@NasehBadalov we still have not received the email.

**Comment by MikeRosTX** [comment]
We have not received a response from any of the Baku organizer either via GitHub, Slack, or email. If we don't receive a response in the next couple of days, we will close out this PR. Once we receive an email with the new organizer's full name and email, you can reopen this PR.

**Comment by NasehBadalov** [comment]
Sorry for the delay, we sent you the details of the new organizers 2 hours ago

**Pull request merged**
