### PR TITLE
[PRG-2021] Move Prague from 2020 to 2021

### PR DESCRIPTION
**Pull request by EtssMM**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Can you change the **logo.png** and **logo-square.png** from 2020 to 2021?

**Comment by MikeRosTX** [comment]
Is Prague planning to do an **In-Person** or **Virtual** event?

**Comment by EtssMM** [comment]
> Can you change the **logo.png** and **logo-square.png** from 2020 to 2021?

Aware of that, still waiting on our designer to provide that unfortunatelly. I wanted to get the information about the date up without waiting for it.

**Comment by EtssMM** [comment]
> Is Prague planning to do an **In-Person** or **Virtual** event?

In person. We see a big value added in that form so we have selected the date when we believe is the best chance of the event being possible and safe.

**Comment by MikeRosTX** [comment]
> > Can you change the **logo.png** and **logo-square.png** from 2020 to 2021?
> 
> Aware of that, still waiting on our designer to provide that unfortunately. I wanted to get the information about the date up without waiting for it.

Completely understand, then for the time being go ahead and delete them temporarily until you get the new ones from your graphic designer so we can merge this PR. Because leaving the 2020 logos will make things confusing. You can create a new PR once you get the new logos.

**Comment by MikeRosTX** [comment]
Why did you close this PR?

**Comment by EtssMM** [comment]
> Why did you close this PR?

I see Sao Paulo changes in the PR so checking if I didn't merge something wrong.
And still need to remove the logo reference from welcome page.

**Comment by MikeRosTX** [comment]
> I see Sao Paulo changes in the PR so checking if I didn't merge something wrong.
> And still need to remove the logo reference from welcome page.

👍

**Pull request closed without merging**
