### PR TITLE
[VAN-2017] adding event guide

### PR DESCRIPTION
**Pull request by rmkbow**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@rmkbow please reference [https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#reference-content](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#reference-content) and move PDF guide to [https://github.com/devopsdays/devopsdays-assets](https://github.com/devopsdays/devopsdays-assets).

**Comment by mattstratton** [comment]
To be fair, we say to keep it under 3 MB, and this one is 1.5, but yes, I'd rather it was hosted offsite.

Nit - your page still has all the links to CFP's, the Propose menu is still active, etc. Might want to turn all of that off.

**Comment by rmkbow** [comment]
Ah shoot, I already made printed signs that point to the existing link.

Can we make an exception for this? I'll keep this in mind for next time.

I figured it was okay since it was small and that we did the same thing last year and that we have an old existing PDF in there.

**Comment by mattstratton** [comment]
It's totally fine. I was looking at the repo size, and it's not terribad. 

For future reference, if you want to shove something into assets and have a redirect off of www.devopsdays.org, let me know, and we can create those. But let's merge this one since you're off to the races!

**Comment by rmkbow** [comment]
I'll make sure it gets into our retrospective meeting so we can do it properly next time 👍

**Pull request merged**
