### PR TITLE
[STH-2019] add slides

### PR DESCRIPTION
**Pull request by krakan**
The slides need to be merged at devopsdays-assets first.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
We’ll merge it like this if you want, but if you add these links to the frontmatter instead you’ll get a nice embed. See https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#talk-page-fields for details.

**Comment by krakan** [comment]
Oh, documentation, my old nemesis! ;)
Thanks for the pointer, I'll update the PR.

**Comment by yvovandoorn** [comment]
Adding 'do-not-merge' until the PR is updated!

**Comment by krakan** [comment]
Now that looks a lot nicer; Thanks for poking me! I believe it can be merged now.
Oh, yes, I removed Kris too as he had to cancel at the last minute.

**Comment by krakan** [comment]
And while I'm at it I realized there was one more change to the actual schedule.

**Comment by bridgetkromhout** [comment]
Much better!

**Pull request merged**
