### PR TITLE
[2016-chicago] update sponsors

### PR DESCRIPTION
**Pull request by jerrycattell**
add new Slalom and Atlassian logos

update AppDynamics logo to be 200x200

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @jerrycattell - is there a reason to add a different Atlassian and Slalom? https://github.com/devopsdays/devopsdays-web/blob/master/static/img/sponsors/atlassian.png and https://github.com/devopsdays/devopsdays-web/blob/master/static/img/sponsors/slalom.png look the same as the ones you're adding.

**Comment by jerrycattell** [comment]
The atlassian logo is 500x500 with transparent background (as opposed the white that most others have). The slalom logo is 100x100, with transparency on top/bottom of the slalom with white background. I'm not opposed to just replacing those images with 200x200 logos.

**Comment by bridgetkromhout** [comment]
Let's ping @mattstratton because I am not sure what he intends with the transparent vs white. (Maybe eventually we move away from logos needing to be square?)

**Comment by mattstratton** [comment]
Tbh we are just lucky with the white backgrounds right now. Transparent should be fine for now. 

WRT square logos, visit this bike shed over here --> https://github.com/devopsdays/devopsdays-web/issues/545

**Comment by jerrycattell** [comment]
Regardless of transparency, we're standardizing on 200x200 for now, correct? Slalom is 100x100, so we'll definitely want to update that one. The Atlassian one is 500x500, but is actually smaller in size than the 200x200 one I generated, so I'm less concerned about that one.

As I said, I'm completely fine with redoing this but updating the slalom logo in place if that is preferred.

**Comment by mattstratton** [comment]
Correct. 200x200. It's actually kind of important that it's exactly that size because retina.

**Comment by jerrycattell** [comment]
@bridgetkromhout @mattstratton, I switched it up to just update the logos for AppDynamics, Atlassian, and Slalom to 200x200 instead of creating new sponsors.

**Comment by bridgetkromhout** [comment]
Okay. I'll merge this and then I'm going to collapse appdynamics and 2016-appdynamics into one.

**Pull request merged**
