### PR TITLE
Initial DevOpsdays Stockholm info

### PR DESCRIPTION
**Pull request by lsc**
Venue is lined up and waiting for confirmation.

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@lsc we can merge this PR, we need a venue name without the hyperlink on the Welcome page.

**Comment by bridgetkromhout** [comment]
Since you have specific dates listed, the venue needs to be confirmed before we will merge this. If you'd like to remove the dates, then the only blocker is needing to get the email and Slack set up. Thanks.

**Comment by lsc** [comment]
Thanks for the quick feedback. When we say confirmed, do we mean something like a contract written? 

I'll remove the dates for now and figure out the logistics around the venue asap.

**Comment by lsc** [comment]
@MikeRosTX oh, sorry missed the first comment. Both email for organizer and slack is up and running already.

**Comment by MikeRosTX** [comment]
Yes, confirmed means deposit and contract with venue location.

**Comment by lsc** [comment]
Sorry, it's close to 00:00 and I should be sleeping. 

@bridgetkromhout We have the email and slack already set up for us.

**Pull request merged**
