### PR TITLE
[RIO-2024] Program

### PR DESCRIPTION
**Pull request by mauriciopgomes**
Add Program

### CODE REVIEW

**Comment by mauriciopgomes** [comment]
please insert no-merge label

**Comment by nimbinatus** [comment]
@mauriciopgomes label added! Please let us know when you're ready for the label to be removed.

**Comment by nimbinatus** [comment]
I'm going to flip this to a draft PR until you're ready to be sure :)

**Comment by nimbinatus** [comment]
Hey there! Is this PR still active considering https://github.com/devopsdays/devopsdays-web/pull/14358 was merged? cc @pedroamaralm @somatorio (in case there was a discussion I missed :) )

**Comment by somatorio** [comment]
Wow, didn't saw this one, no I'm wondering if I did something wrong merging https://github.com/devopsdays/devopsdays-web/pull/14358

**Comment by nimbinatus** [comment]
> Wow, didn't saw this one, now I'm wondering if I did something wrong merging #14358

Nope, you're fine! I just wanted to be sure there wasn't a convo that was happening somewhere that would have us close this one.

**Pull request closed without merging**
