### PR TITLE
[CAI-24] Update welcome and sponsors

### PR DESCRIPTION
**Pull request by aameen79**
Update welcome and sponsors

### CODE REVIEW

**Comment by phrawzty** [comment]
https://github.com/devopsdays/devopsdays-web/pull/14440/commits/8258c1970fc0e90b780f37ab2c63479b3e0a9485 aligns all of your organizer / sponsor logos with the same format used by every other event in this repository. Details of the changes:

"Corporate Organizers"

1. Itida / Secc
   1. Created sponsor object
2. Atos
   1. Sponsor already exists but needed to be cleaned up (URL)
      1. Modified Zurich-2018 to point the URL correctly
3. Cegedim
   1. Sponsor already exists
4. DXC Technology
   1. Created sponsor object
5. Orange
   1. Sponsor already exists
6. \_VOIS Vodafone
   1. Created sponsor object

“Academia Organizers”

1. Cairo University
   1. Created sponsor object
2. The American University in Cairo
   1. Created sponsor object
3. Egypt University of Informatics
   1. Created sponsor object

`main.yaml`

1. Added "corporate" and "academia" items to `sponsor_levels`
   1. Set max: 1 to avoid the "join as" string from appearing
2. Added sponsors (above) to sponsors in the same order they appeared in the original PR
3. Removed the entire `<figure>` block that contained the external images

**Comment by aameen79** [comment]
Thanks @phrawzty for your support, I wanted to do it this way but I have a problem putting the word "sponsors" after corporate or academia organizers, and making these two categories the upper most level
Can you help doing so?

**Comment by mattstratton** [comment]
> Thanks @phrawzty for your support, I wanted to do it this way but I have a problem putting the word "sponsors" after corporate or academia organizers, we need to remove the word "sponsors" from these categories, and making these two categories the upper most level Can you help doing so?

currently, the code does not support this (the word "sponsor" is embedded). we can open an issue to look into the ability to override this, but i can't guarantee when/if it would be added

**Comment by mattstratton** [comment]
I have opened https://github.com/devopsdays/devopsdays-web/issues/14456 for discussion on adding this feature (need to determine if there are other things not thought of)

**Comment by aameen79** [comment]
Thank you all for your proactivity and support.
These entities are organizing the event with ITIDA and not sponsoring, that's why I put them in the welcome page in the first place before @phrawzty proactively change the code, effort appreciated, but it would be confusing labeling an entity "Organizer Sponsor" as it show right now.
I appreciate opening a discussion by @mattstratton about a technical change that will solve the case, which seems reasonable to be.
But since this may take time, I hashed the changes (and added a Platinum Sponsor) until it's possible to override the "Sponsors" word.
Kindly need to merge asap because this is causing embarrassment with sponsors and organizers.

**Review by phrawzty — APPROVED** [review]

**Pull request merged**
