### PR TITLE
[BOISE-2021] Cancel Boise 2020, Create Boise 2021

### PR DESCRIPTION
**Pull request by mattk42**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by mattstratton** [comment]
@mattk42 do you all have a contract with the venue for the dates in 2021? Usually, we don't put dates on the website unless there is a venue contract.

I understand this is a new situation for all of us; I'm not saying I won't merge this otherwise but wanted to check on that first.

**Comment by mattstratton** [comment]
I am also sourcing input on adding a "canceled" field for events that are no longer going forward, but we want to keep their event site up. https://github.com/devopsdays/devopsdays-web/issues/9681

**Comment by mattk42** [comment]
@mattstratton Thanks for checking, the word I got from the Boise team is that they are "confirmed" with the venue. I am not sure if that means a contract is signed or they just have a verbal/written confirmation at this point. I can get further clarification. Sorry, I am part of Denver's team and just helping Boise out, so not 100% in the loop there.

Will chime in on the PR regarding canceled events and will follow whatever happens there to update Boise when the time comes.

**Comment by mattk42** [comment]
They have the contract in hand, signing it tomorrow.

**Pull request merged**
