### PR TITLE
[SYD-2019] kickoff

### PR DESCRIPTION
**Pull request by m1keil**
Adding sydney 2019 event to the list. :fireworks:

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
While the UTC +2 time was definitely wrong, I think the +10 may also be wrong for your event dates: https://www.timeanddate.com/time/zone/australia/sydney - by that time in October, will it be +11?

**Comment by m1keil** [comment]
good catch @bridgetkromhout :-)

**Comment by bridgetkromhout** [comment]
@m1keil can you email info@devopsdays.org with your organizer team's names and email addresses? We need that info to set up the email list and Slack. Thanks.

**Comment by m1keil** [comment]
done!

could you please also add devopsdays-sydney-2019-organisers@googlegroups.com
as a target to the email alias?

Cheers

**Comment by bridgetkromhout** [comment]
> could you please also add devopsdays-sydney-2019-organisers@googlegroups.com
as a target to the email alias?

As you can imagine, this ends up being way too complex in terms of one-offs, so we don't do them. But you are of course welcome to have your own mail filters set any way you like.

**Comment by bridgetkromhout** [comment]
Fixed a few other things - when the build finishes this should be good to merge.

**Comment by bridgetkromhout** [comment]
Hmm, the propose link 404s. Either fix it or remove it?

**Comment by m1keil** [comment]
@bridgetkromhout I was hoping link will be active by today but we need some financials to figure out. commented out for now. Thanks for the review.

**Comment by bridgetkromhout** [comment]
Great! I’ll merge this now and your page will be up. You will likely want to add an event image and possibly organizer images, when you get a chance.

**Comment by m1keil** [comment]
Yep, going to do tweaks during the week. thanks a lot

**Pull request merged**
