### PR TITLE
 [SIN-18] Add theme and proposals

### PR DESCRIPTION
**Pull request by sergiubodiu**
[SIN-18] add so0k as organiser
[SIN-18]  add CFP papercall

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@sergiubodiu we cannot merge this PR until dates for CFP are set in yaml file and until PaperCall url resolves in **_proposal.md_**

**Comment by bridgetkromhout** [comment]
To clarify, https://www.papercall.io/devopsdays-singapore-2018 appears to not work. We don't want to merge this until that link works - thanks.

**Comment by sergiubodiu** [comment]
Hi Bridget, the link is live

**Comment by MikeRosTX** [comment]
@sergiubodiu I've added the following dates to the **_2018-singapore.yml_** file for CFP.
If you want to readjust those dates, just create a new PR.

**_cfp_date_start_**: 2018-07-05  # start accepting talk proposals.
**_cfp_date_end_**: 2018-08-31  # close your call for proposals.
**_cfp_date_announce_**: 2018-09-11  # inform proposers of status

**Pull request merged**
