### PR TITLE
[Montreal-2022]

### PR DESCRIPTION
**Pull request by sebagomez**
More speakers data and sponsors

### CODE REVIEW

**Comment by yvovandoorn** [comment]
hi @sebagomez, there seems to be a problem surrounding: `Error: Error building site: "/home/circleci/devopsdays/content/events/2022-montreal/speakers/pascal-robert.md:1:26": unmarshal failed: toml: expected newline but got U+0054 'T'` (from CircleCI).

Looking at `content/events/2022-montreal/speakers/pascal-robert.md`, it does appear that specific file doesn't contain line breaks, whereas the other ones do. So its causing Hugo to have issues.

**Comment by sebagomez** [comment]
I tried to push it as I saw it in the devopsdays-web repo. Let me change it to what I really want it to be

**Comment by sebagomez** [comment]
hey @yvovandoorn the file is as I want it right now... you can overwrite your's with this one

**Comment by sebagomez** [comment]
Closed it to open a new one

**Pull request closed without merging**
