### PR TITLE
[rdu-2024] Create 2024-raleigh files

### PR DESCRIPTION
**Pull request by jrn00**
Created event for 2024-raleigh:

Created 2024-raleigh.yml

Thank you!

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Looks like you copied your 2023 files - make sure you go through and edit the places where they say 2023 to now say 2024.

**Comment by bridgetkromhout** [comment]
Oh, and if you don't use the new event script, then be sure to update https://github.com/devopsdays/devopsdays-web/blob/main/static/_redirects#L92 manually.

**Comment by jrn00** [comment]
> Looks like you copied your 2023 files - make sure you go through and edit the places where they say 2023 to now say 2024.

I did copy. I know there's a script but I couldn't find it. I think I changed the '23 the '24 on everything.

**Comment by adrianmoisey** [comment]
Hey, I still see some 2023 references

**Comment by jrn00** [comment]
> Hey, I still see some 2023 references

Ok, I'll run through it again and remove the '23 stuff.

**Comment by jrn00** [comment]
Closed for editing.

**Comment by jrn00** [comment]
Opened [rdu-2024] Create Raleigh 2024 event #13323

Disregard this PR

**Pull request closed without merging**
