### PR TITLE
[KC-2019] kansas city initial 2019

### PR DESCRIPTION
**Pull request by aaronblythe**
Initial 2019 Kansas City scaffolding.
Add initial organizer list.
Date and Venue still TBD.

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello! Happy to see that KC is coming back in 2019 - that's great news. Could you please also send an email to info@devopsdays.org with the list of organisers (name & email addresses), including any changes from 2018. This is so that we can ensure parity between the website, Slack, and distribution list.

Thanks!

**Comment by bridgetkromhout** [comment]
Specifically we need any email addresses that changed for the returning organizers, and we need the email addresses for Chris Fisher, Kayla Crowder, and DaShaun Carter so we can set up email and Slack.

**Comment by bridgetkromhout** [comment]
Per discussion with @aaronblythe, they will send the email addresses later in the week and understand that this PR will wait until then.

**Comment by bridgetkromhout** [comment]
Slack and email list updated.

**Pull request merged**
