### PR TITLE
[STH-2019] New stockholm team

### PR DESCRIPTION
**Pull request by JasmineCrozier**
I've added the new team members for the Stockholm event in 2019

### CODE REVIEW

**Comment by JasmineCrozier** [comment]
@mattstratton Could this be a CI problem on your hand?

**Comment by mattstratton** [comment]
Yeah, appveyor has been a little flaky. We don’t need to worry about that test (i know, I know, bad devops practice!)

**Comment by mattstratton** [comment]
We will merge this as soon as we get your email alias set up!

**Comment by JasmineCrozier** [comment]
OK thanks. I've sent the email to info ;)

**Pull request merged**
