### PR TITLE
Adding new event in Fortaleza

### PR DESCRIPTION
**Pull request by gb8may**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @gb8may - we need to list 3 organizers. I see 2 organizers on your list. Is @gomex also an organizer for Fortaleza? Please let us know. Thank you!

**Comment by gb8may** [comment]
Hi Bridget,

No, Rafael is not one of the organizers, i will edit the files today, and add the other team members.

Thanks!

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
CompTIA Network+ | Ethical Hacking Foundation
Fortinet NSE1 | DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552

**Comment by gb8may** [comment]
Add logo.png on directory static/events/2018-fortaleza

**Comment by gb8may** [comment]
Hello!

I made some changes on yaml file, adding other members. Do i need to make a
new PR?

Thanks.

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
CompTIA Network+ | Ethical Hacking Foundation
Fortinet NSE1 | DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 | Puppet ID: PPT0005371

2018-06-22 8:18 GMT-03:00 Mayara Gouveia <gb8may@gmail.com>:

**Comment by bridgetkromhout** [comment]
Discussing in email.

**Comment by gb8may** [comment]
Ok!

**Comment by bridgetkromhout** [comment]
I’m away from a real computer (just on the phone) a lot right now. This can be merged when a core team member has the bandwidth to set up the Slack and email configs that go with it.

**Comment by bridgetkromhout** [comment]
I set up the Slack and email lists.

**Pull request merged**
