### PR TITLE
[Moscow-2017] Change dates, closed speaking proposals

### PR DESCRIPTION
**Pull request by VitMosin**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by KrisBuytaert** [comment]
Isn't it a bit to late to shorten the CFP deadeline by a week ?

**Comment by VitMosin** [comment]
Hi, yes, it is a bit late, but we are forced to close the CFP due to future visa problems (not enough time for international speakers) and a huge amount of talks proposed (over 30), which our talk committee cant handle.
 
If you thing that it is not appropriate to close the CFP now, leave it as it is, but we are afraid that we would not be able to handle the international speakers talks and dont want to take their time on preparing the talk for us.

**Comment by KrisBuytaert** [comment]
I'd leave it and start working with those International speakers asap .. that would leave time open for local folks to still submit with their original planning.  People might have set their reminders to the original ones.    When you see an international speaker submitting after the proposed date you can already ask them if they have visas etc...

**Comment by VitMosin** [comment]
Is it normally for your view to move CFP date to 08/02?

**Pull request closed without merging**
