### PR TITLE
Add Event and Dates to the Slack unfurl

### LINKED ISSUE #8189: Add more meta tags to improve slack unfurl
Improvements suggested by @adrianmoisey 

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

First related PR: https://github.com/devopsdays/devopsdays-web/pull/8185

### PR DESCRIPTION
**Pull request by adrianmoisey**
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

Fixes #8189

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Before:

image


After:

image

**Comment by adrianmoisey** [comment]
Testing each page type:

Welcome:
image

Speakers:
image

Program:
image

Talk:
image

**Comment by adrianmoisey** [comment]
I'm happy that it works as intended. 
It seems to do nothing on twitter (the medium article explains why, and seems to br correct).

Happy to receive review/thoughts/comments/ideas!

**Comment by bridgetkromhout** [comment]
LGTM - let's have @mattstratton review too!

**Comment by mattstratton** [comment]
LGTM. This is great. I was bikeshedding over the label being called "Event" vs something else, but I don't have a better idea.

One thing - maybe make the title ("Speakers", etc) include the event name, so it would be "Speakers - DevOpsDays Ponyville 2020") to give a bit more context?

**Comment by mattstratton** [comment]
I don't know if we can control that though - it might pull directly from the HTML for the page, and I *think* we don't want to modify the title on the page.

**Comment by mattstratton** [comment]
OK, so thinking about this some more, this is more a thing where we want to fix the `<title>` for pages to be more descriptive in general. That is out of scope for this change (it's also weird, because we don't want to automatically add the event name and year, because some pages have that in their title already). So really it's just a thing that people should do better in general, not something we should fix in code.

**Comment by adrianmoisey** [comment]
I agree with you. I think it would be nice to have more info in the title, but for the reasons you describe might be difficult.

**Comment by mattstratton** [comment]
This looks good to me, so I'm going to merge it

**Comment by mattstratton** [comment]
Oof. This isn't great. Now every page in the site changes on every production build, so they are all new files. The master builds have doubled in time since adding this. :/

**Comment by mattstratton** [comment]
Disregard. That was a red herring. This change is fine!

**Comment by adrianmoisey** [comment]
> Disregard. That was a red herring. This change is fine!

*phew*

**Pull request merged**
