### PR TITLE
[DET-2022] Add Speakers, Program, Sponsor, Close Proposals

### PR DESCRIPTION
**Pull request by dejonghe**
* Added Speakers and Program
* Added one sponsor. Closed proposals

Talk times coming soon, program page looks blank going to leave it off nav until we have times.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi! You're missing a `speakers.md` to display the speaker listing

**Comment by mattstratton** [comment]
You also are missing the pages for each talk, etc (usually found in the "/program" directory. 

The `sharing image` settings are off as well? I didn't see anything committed to `/static/events/2022-detroit/sharing` directory?

Take a look at the current setup for 2022-chicago for an example

**Comment by dejonghe** [comment]
Forgot to commit program and speakers.md, thanks for the catch. 
Are sharing images required? These might take us a another day. Could I just comment out sharing_image in the speaker profiles?

**Comment by mattstratton** [comment]
@dejonghe sharing images are optional! Just remove the field from the frontmatter if you don’t want to use them :)

**Comment by mattstratton** [comment]
More info: https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/REFERENCE.md#social-sharing-image

**Pull request merged**
