### PR TITLE
Detroit sponsors

### PR DESCRIPTION
**Pull request by bchess**
Added sponsor logos for Detroit 2016. Also made some small fixes to the old Detroit 2015 site so it's not as broken. :)

### CODE REVIEW

**Comment by yvovandoorn** [comment]
Hey @bchess! 

A few suggestions
* There is some remnant text running amock on the welcome page:
wild text
* You should try to conform the sponsor images to equal WxH (preferably 200x200). Currently the Canonical logo is doing some not fun things (related to #545). 
stretched logo
* Would it be possible for you to try converting the `span` to `col`. This is part of the responsive theme. See [dod AMS 2016 welcome](https://raw.githubusercontent.com/devopsdays/devopsdays-web/master/content/events/2016-amsterdam/welcome.md) or [dod MSP 2016 welcome](https://raw.githubusercontent.com/devopsdays/devopsdays-web/master/content/events/2016-minneapolis/welcome.md) as examples.

**Comment by bchess** [comment]
@yvovandoorn I don't see the text problem as you do: 
screen shot 2016-06-23 at 2 20 38 pm

And for the col/span - I believe we already are using col for 2016? 2016-detroit/welcome.md follows the same template that you link to. Are you maybe instead looking at 2015-detroit?

Ack on the Canonical logo fix, can do.

**Comment by yvovandoorn** [comment]
@bchess you're right on the welcome.md. I totally mistook the commits as /2015-detroit/ and not /2016-detroit/!

On the text one -- just discovered because my latest `brew upgrade` pulled in Hugo 0.16 locally and its an issue @mattstratton is tracking in #569.

Looks like all thats needed is a better Canonical logo 😄

**Comment by bchess** [comment]
Updated Canonical logo

**Pull request merged**
