### PR TITLE
[LDN-2019] Add Influxdata as sponsor

### PR DESCRIPTION
**Pull request by chriscoffee**
We've got influxdata sponsoring gold this year.

Signed-off-by: Chris M <me@christophermills.co.uk>

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@chriscoffee did you do a rebase? Because there are some required checks that are failing.

**Comment by MikeRosTX** [comment]
Please rebase to see if that fixes the failing issues. Because there were some new Theme changes that it seems to be failing on...

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: speaking/single.html:9:4: executing "main" at <partial "speaking.ht...>: error calling partial: "/root/devopsdays/themes/devopsdays-theme/layouts/partials/speaking.html:12:34": execute of template failed: template: partials/speaking.html:12:34: executing "partials/speaking.html" at <dateFormat "2006-01-...>: error calling dateFormat: unable to cast <nil> of type <nil> to Time
Exited with code 255

**Comment by bridgetkromhout** [comment]
I merged this using the "rebase and merge" option in github.

**Comment by chriscoffee** [comment]
Yeah apologies about this, I did it on my phone after putting in the work yesterday. 👍 Thanks for sorting

**Pull request merged**
