### PR TITLE
[RDU-2019] added RDU program

### PR DESCRIPTION
**Pull request by normalfaults**
[RDU-2019] added RDU program

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
If you want to pull in upstream master to bring this up to current it would be good.

**Comment by mattstratton** [comment]
I tried merging this, because it seemed like it would work, but it fails. We'll need to have a new PR but need to figure out why it's not working.

**Comment by normalfaults** [comment]
Thanks I'll make a new branch and pull request. Something got mucked up somewhere ...

**Comment by mattstratton** [comment]
I actually fixed it -there were lots of errors in the program YAML and
program files. I’m pushing up a new PR and I’ll tag you to review it.


On July 28, 2019 at 1:31:30 PM, Nirmal Mehta (notifications@github.com)
wrote:

Thanks I'll make a new branch and pull request. Something got mucked up
somewhere ...

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/devopsdays/devopsdays-web/pull/7762?email_source=notifications&email_token=AAJYVGRZII25ENOU4AIBRWDQBXQYFA5CNFSM4IHLNRJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD27D6WQ#issuecomment-515784538>,
or mute the thread

**Pull request merged**
