### PR TITLE
create CFP page

### PR DESCRIPTION
**Pull request by bridgetkromhout**
This is for https://github.com/devopsdays/devopsdays-web/issues/880 and is definitely not ready to merge.

### CODE REVIEW

**Comment by mattstratton** [comment]
If fixed the date sorting issue in https://github.com/devopsdays/devopsdays-web/pull/881/commits/e8ca8e42bec8eb96fb0d9d0f92638b6de70d5fe5

**Comment by mattstratton** [comment]
I fixed the issue with the footer in the latest commit.

**Comment by bridgetkromhout** [comment]
This could use many improvements but I think as an MVP it can see the light of day. Changes the frontpage so I'd like @mattstratton to sign off/merge.

**Comment by mattstratton** [comment]
Looks good to me for now. We'll want to add an issue for enabling sorting on the table (probably some jquery magic) like we discussed offline.

**Pull request merged**
