### PR TITLE
[RDU-2021] expose program and speakers in menu bar

### PR DESCRIPTION
**Pull request by normalfaults**
[RDU-2021] expose program and speakers in menu bar

### CODE REVIEW

**Comment by normalfaults** [comment]
It looks like the program link is 404-ing . any thoughts on hwo to fix @MikeRosTX ?

**Comment by MikeRosTX** [comment]
Not sure why you're getting a 404. But ask other from your RDU team to check. If still not, then post it in the #website channel on Slack.

**Comment by mattstratton** [comment]
You need a `program.md` in your content directory. 

Here's a template you can copy:

`utilities/examples/templates/program.md`

**Comment by mattstratton** [comment]
You need a `program.md` in your content directory. 

Here's a template you can copy:

`utilities/examples/templates/program.md`

**Pull request merged**
