### PR TITLE
[GE-2023] program updates

### PR DESCRIPTION
**Pull request by deniger**
program updates

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
All the checks that were failing finally PASSED.

But would like to recommend complying with the Speaker Guidelines in making the speaker images smaller.

https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#speaker-page-fields

The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. It can be either .png or .jpg. It is recommended to be 600px square.

**Comment by icrc-fdeniger** [comment]
@MikeRosTX I've just updated the image to be 600*600

**Comment by MikeRosTX** [comment]
Please review all the images, because there are a lot more images bigger than 600x600.

**Comment by deniger** [comment]
@MikeRosTX I've updated the image to expected size: https://github.com/devopsdays/devopsdays-web/pull/12522/commits/febd39b6d35851b9210ee1a0215de56b9baf3475

Thanks

**Comment by MikeRosTX** [comment]
But all the other images previously uploaded are bigger than 600x600. Please reduce the rest of the images.

**Comment by deniger** [comment]
speaker images updated

**Review by MikeRosTX — APPROVED** [review]

**Pull request merged**
