### PR TITLE
[DEN-2024] update honeycomb logo

### PR DESCRIPTION
**Pull request by themightymuppet**
honeycomb _very slightly_ updated their logo and requested the change. (colors are a bit bolder and hexagons are marginally closer together.)
- also updates parking details on devopsdays denver 2024.

### CODE REVIEW

**Comment by adrianmoisey** [comment]
There's a part missing from this PR, old events need to be updated to point at the old honeycomb logo. There's a script to handle this here: https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data

**Comment by themightymuppet** [comment]
thanks @adrianmoisey - i've updated the old logos accordingly! please let me know if anything else is missing

**Comment by adrianmoisey** [comment]
Hey, looks good!
Just 1 file was missed:
`data/events/2024/los-angeles/main.yml`

**Comment by themightymuppet** [comment]
> Hey, looks good! Just 1 file was missed: `data/events/2024/los-angeles/main.yml`

sorry i missed your message - i originally omitted LA because it was part of 2024 and i thought it should use the new logo but this PR is a bit overdue at this point so i went ahead and included this change 😅 

thank you!

**Pull request merged**
