### PR TITLE
[TLV-2024] Added New Sponsors + FINALLY Updated Aerospike

### PR DESCRIPTION
**Pull request by shar1z**
- Added Coralogix, Cast.AI and Upgraded Big Data Boutique
- Updated new Aerospike logo per these guidelines https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data (I hope I did it right)
NOTE: I could not check at all because there is some kind of syntax error across all of the 2019 event directories (see screenshot).  I removed one just to see if localhost will serve, and it didn't so I believe it's a global issue.  
Screen Shot 2024-07-07 at 14 10 06
- Removed sponsors who pulled out

### CODE REVIEW

**Comment by shar1z** [comment]
The deployment preview isn't working for me either.

Screen Shot 2024-07-07 at 14 20 15

**Comment by mattstratton** [comment]
Why does this PR change the base Hugo config?

**Comment by mattstratton** [comment]
> Why does this PR change the base Hugo config?

I mean it is just adding some extra whitespace at the end but still.

**Comment by shar1z** [comment]
I'm not sure - I think I may need to delete the directory.
I haven't updated in a while - I did a pull and rebase but a lot of weird things happened.  I'm going to close this PR - delete my directory and try again.

**Comment by shar1z** [comment]
CLOSING PR AND REFORKING AND TRYING AGAIN
Haven't updated in too long - and there are too many conflicts and weird things happening.

**Pull request closed without merging**
