### PR TITLE
[RDU-2018] added happy hour

### PR DESCRIPTION
**Pull request by normalfaults**
[RDU-2018] added happy hour

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @normalfaults - attendees may be confused and think they _must_ give contact info to a sponsor in order to participate in an official conference event (the first evening's event). We prohibit that.

The sponsor may _request_ attendees to hand over contact info, but may not _require_ it if this event is part of the conference and listed on your program (which it appears to be). Please make sure that's clear on the website - thanks.

**Comment by normalfaults** [comment]
Thank you for the reply @bridgetkromhout . I am working with the other organizers and sponsor to clarify the verbage. I will create a new commit / pr in the future.

**Comment by MikeRosTX** [comment]
@normalfaults - Do you want us to close this PR and you'll create a new once you've consulted with your other team organizers?  Or would you like to keep it open until you guys come to a conclusion?

**Comment by normalfaults** [comment]
@MikeRosTX you can close this PR. I'll create another one once we figure out solution.

**Pull request closed without merging**
