### PR TITLE
[Baltimore-2018] Sponsor logos should be square

### PR DESCRIPTION
**Pull request by nathenharvey**
Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by mattstratton** [comment]
THey don't need to be square - that's the old theme.

also, this change would update many events, so I'm not sure we want to make it.

Example:

```
data/events/2017-boston.yml:  - id: appdynamics
data/events/2017-chicago.yml:  - id: appdynamics
data/events/2017-dallas.yml:  - id: appdynamics
data/events/2017-detroit.yml:  - id: appdynamics
data/events/2017-kansascity.yml:  - id: appdynamics
data/events/2017-madison.yml:  - id: appdynamics
data/events/2017-minneapolis.yml:  - id: appdynamics
data/events/2017-nashville.yml:  - id: appdynamics
data/events/2017-ohio.yml:  - id: appdynamics
data/events/2017-philadelphia.yml:  - id: appdynamics
data/events/2018-atlanta.yml:  - id: appdynamics
data/events/2018-austin.yml:  - id: appdynamics
data/events/2018-baltimore.yml:  - id: appdynamics
data/events/2018-denver.yml:  - id: appdynamics
data/events/2018-des-moines.yml:  - id: appdynamics
data/events/2018-new-york-city.yml:  - id: appdynamics
data/events/2018-salt-lake-city.yml:  - id: appdynamics
data/events/2018-seattle.yml:  - id: appdynamics
```

@bridgetkromhout

**Comment by mattstratton** [comment]
More references:

https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor

https://github.com/devopsdays/devopsdays-web/pull/503

**Comment by nathenharvey** [comment]
ahhh ... didn't realize that!  that's awesome.  Would you be opposed to hosting square versions of these that are used for other purposes?  for example, I want to use them in an email that we send out.

**Comment by mattstratton** [comment]
For those, please use the devopsdays-assets repo; we like to keep this one as thin as possible.

**Comment by nathenharvey** [comment]
got it, thanks!

**Pull request closed without merging**
