### PR TITLE
[columbus-2019] - Update DataRobot logo

### PR DESCRIPTION
**Pull request by bilsch**
Updating the logo per request of DataRobot

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Replacing sponsor's logo is linked in the section about **_Updating a Sponsor_** https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor

**REPLACING SPONSOR LOGO**
https://github.com/devopsdays/devopsdays-web/pull/503
I'd prefer a PR that moves static/img/sponsors/thoughtworks-products.png and copies data/sponsors/thoughtworks-products.yml to a clearly-namespaced-in-the-past name like thoughtworks-product-before-20160602.whatever and updates the events on this list that already happened. Ideally a tool that does just that, which I recognize is a pain to do manually. Then static/img/sponsors/thoughtworks-products.png can be this new image and data/sponsors/thoughtworks-products.yml can be whatever you want (possibly exactly what it is now).
$ grep -r thoughtworks-products data/events/*
data/events/2016-amsterdam.yml: - id: thoughtworks-products
data/events/2016-austin.yml: - id: thoughtworks-products
data/events/2016-chicago.yml: - id: thoughtworks-products
data/events/2016-denver.yml: - id: thoughtworks-products
data/events/2016-minneapolis.yml: - id: thoughtworks-products
data/events/2016-portland.yml: - id: thoughtworks-products
data/events/2016-saltlakecity.yml: - id: thoughtworks-products
data/events/2016-seattle.yml: - id: thoughtworks-products
data/events/2016-toronto.yml: - id: thoughtworks-products
data/events/2016-vancouver.yml: - id: thoughtworks-products
data/events/2016-washington-dc.yml: - id: thoughtworks-products

**Comment by bilsch** [comment]
> Replacing sponsor's logo is linked in the section about Updating a Sponsor https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor

Not a problem thanks @MikeRosTX will push an update shortly. Also @kjenkins19 was talking about doing an update so I may have him do that as he knows this process ;) ( my first pr in a very long time to devopsdays-web ;) )

**Comment by MikeRosTX** [comment]
Well close this PR for now and @kjenkins19 can submit a new one later.

**Comment by bilsch** [comment]
sorry just had not gotten back to this - good to close @MikeRosTX ;)

**Pull request closed without merging**
