### PR TITLE
[ZRH-2019] Open CfP

### PR DESCRIPTION
**Pull request by tobru**
Please wait with merge until we give the final go! Thanks

### CODE REVIEW

**Comment by tobru** [comment]
Not sure why the preview build fails:

```
[...]
4:02:19 PM: Starting to deploy site from 'public/'
4:07:22 PM: Failing build: Failed to deploy site
4:07:22 PM: failed during stage 'deploying site': Failed to execute deploy: Error: preprocessing deploy timed out
4:07:22 PM: Finished processing build request in 7m0.676862713s
```

I would love to see a preview before giving a go for merging. Can one of the DoD website admins have a look?

**Comment by bridgetkromhout** [comment]
The build sometimes fails with a timeout. The way to have it retry is to add a commit. I have added the full datetime strings; let's see if the build succeeds this time.

**Comment by bridgetkromhout** [comment]
You can now see it here: https://deploy-preview-5603--devopsdays-web.netlify.com/events/2019-zurich/welcome/

**Comment by tobru** [comment]
Thanks very much @bridgetkromhout We'll check it and I'll release the PR once everyone is ok with it.

**Comment by bridgetkromhout** [comment]
Hi, @tobru - should we merge this now? Thanks!

**Comment by tobru** [comment]
@bridgetkromhout Yes, please go ahead. Thanks!

**Pull request merged**
