### PR TITLE
[#10822] Migrate PDFs into devopsdays-assets repository and redirect them.

### LINKED ISSUE #10822: move pdfs from www to assets & set up redirects
There are a bunch of `pdf`s in www that should be in assets. Propose that we move them to assets and set up redirects so as not to break links.

```
$ find . -type f -name '*.pdf' -exec du -ch {} + | grep total$
 30M	total
```

@mattstratton sez:
> that is what /static/_redirects file can be used for

See also: netlify

cc @yvovandoorn

### PR DESCRIPTION
**Pull request by chriscoffee**
This should migrate all the PDF formatted assets from `./static/` -> `https://assets.devopsdays.org`

It relies on another PR being merged (https://github.com/devopsdays/devopsdays-assets/pull/164) and checked whether the URLs respond with their given redirect (which I'll quickly write a script for..) in the devopsdays-assets repo once it's deployed.

I've tried to keep everything in a logical format and migrated 1:1 apart from extra folders where we've got `/sponsor/` and `/transcripts` et al.

We might also want to reach out to people/put in a check to make sure that future PDFs aren't added in this way, note that those from 2023 were, if we were to blamelessly name and shame:
- New York City
- Los Angeles
- Melbourne
- Rio De Janeiro

Though, I don't think it's on the person contributing to *know*, we should pick it up with a warning/make sure we advise people in CONTRIBUTING if it's not already in place.

**Dependencies: https://github.com/devopsdays/devopsdays-assets/pull/164**

Fixes #10822

### CODE REVIEW

**Comment by mattstratton** [comment]
@chriscoffee I've merged https://github.com/devopsdays/devopsdays-assets/pull/164 if you want to test now?

I'm changing this to a draft PR until it's been tested (just to keep from an accidnetal merge!)

**Comment by mattstratton** [comment]
> Though, I don't think it's on the person contributing to _know_, we should pick it up with a warning/make sure we advise people in CONTRIBUTING if it's not already in place.
> 
it's already there - https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#minimal-large-files

**Comment by mattstratton** [comment]
that said, we should probably reword this a little more strongly:
```
It is acceptable to add in a single PDF for your sponsor prospectus if you desire (in static/events/YYYY-city), but please keep this file under 3 MB. It is better to host it on Google Drive or something similar, and then link to it from your site.
```

**Comment by chriscoffee** [comment]
> @chriscoffee I've merged https://github.com/devopsdays/devopsdays-assets/pull/164 if you want to test now?
> 
> I'm changing this to a draft PR until it's been tested (just to keep from an accidnetal merge!)

No worries I'll test in a mo when my daughter is in bed. Thanks for looking at this quickly

**Comment by chriscoffee** [comment]
```
$ xargs -n1 -P 10 curl -o /dev/null --silent --head --write-out '%{url_effective}: %{http_code}\n' < ./urls.txt


https://assets.devopsdays.org/events/2022/zurich/workshop-info-anand-bagmar.pdf: 200
https://assets.devopsdays.org/events/2023/rio-de-janeiro/devopsdays-rj-sponsor-2021.pdf: 200
https://assets.devopsdays.org/events/2022/los-angeles/devopsdayla2022_sponsor.pdf: 200
https://assets.devopsdays.org/events/2023/melbourne/prospectus.pdf: 200
https://assets.devopsdays.org/events/2022/melbourne/prospectus.pdf: 200
https://assets.devopsdays.org/events/2023/los-angeles/devopsdayla2023_sponsor.pdf: 200
https://assets.devopsdays.org/events/2023/new-york-city/dodnyc-23-sponsor-prospectus.pdf: 200
https://assets.devopsdays.org/events/2022/los-angeles/devopsdayla2022_sponsor_v2.pdf: 200
https://assets.devopsdays.org/events/2020/madrid/madridsponsorship.pdf: 200
https://assets.devopsdays.org/events/2020/guadalajara/prospectus.pdf: 200
https://assets.devopsdays.org/events/2021/raleigh/sponsorpackage-devopsdaysraleigh2021.pdf: 200
https://assets.devopsdays.org/events/2020/philadelphia/devopsdays_philadelphia_2020_prospectus.pdf: 200
https://assets.devopsdays.org/events/2021/blumenau/devopsdays-blu-2021.pdf: 200
https://assets.devopsdays.org/events/2022/buffalo/prospectus.pdf: 200
https://assets.devopsdays.org/events/2020/houston/sponsorship-prospectus.pdf: 200
https://assets.devopsdays.org/events/2020/houston/dodh-health-and-safety-update.pdf: 200
https://assets.devopsdays.org/events/2022/bengaluru/prospectus.pdf: 200
https://assets.devopsdays.org/events/2020/sao-paulo/novo_palestrante.pdf: 200
https://assets.devopsdays.org/events/2019/washington-dc/resilience-engineering.pdf: 200
https://assets.devopsdays.org/events/2019/washington-dc/engineers-guide-to-devops.pdf: 200
https://assets.devopsdays.org/events/2019/philadelphia/devopsdays_philadelphia_2019_prospectus.pdf: 200
https://assets.devopsdays.org/events/2019/washington-dc/emmanuel-apau.pdf: 200
https://assets.devopsdays.org/events/2019/victoria/sponsordevopsdays2019.pdf: 200
https://assets.devopsdays.org/events/2019/kansas-city/2019-kansas-city-prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/victoria/sponsordevopsdays2018.pdf: 200
https://assets.devopsdays.org/events/2019/washington-dc/all-tech-is-debt.pdf: 200
https://assets.devopsdays.org/events/2019/kansas-city/devopsdays2019-map-westport-commons-plexpod.pdf: 200
https://assets.devopsdays.org/events/2018/phoenix/devopsdays_phoenix_2018_sponsor_prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/raleigh/sponsorpackage-devopsdaysraleigh2018.pdf: 200
https://assets.devopsdays.org/events/2018/kansas-city/prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/philadelphia/devopsdaysphl2018-prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/boise/prospectus.pdf: 200
https://assets.devopsdays.org/events/2019/chattanooga/devopsdays-chattanooga-2019-prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/detroit/devopsdaysdetroit-prospectus-2018.pdf: 200
https://assets.devopsdays.org/events/2017/vancouver/sponsordevopsdays2017.pdf: 200
https://assets.devopsdays.org/events/2018/moscow/%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_devopsdays.pdf: 200
https://assets.devopsdays.org/events/2018/moscow/partner%20proposal%20devopsdays%202018.pdf: 200
https://assets.devopsdays.org/events/2017/hartford/devopsdays-hfd-2017-prospectus.pdf: 200
https://assets.devopsdays.org/events/2017/philadelphia/devopsdaysphl2017-prospectus.pdf: 200
https://assets.devopsdays.org/events/2018/chattanooga/devopsdays-chattanooga-2018-prospectus.pdf: 200
https://assets.devopsdays.org/events/2017/vancouver/guide.pdf: 200
https://assets.devopsdays.org/events/2018/boston/devopsdayssponsorprospectus2018.pdf: 200
https://assets.devopsdays.org/events/2017/detroit/devopsdaysdetroit-prospectus-2017.pdf: 200
https://assets.devopsdays.org/events/2017/boston/boston2017sponsorprospectus.pdf: 200
https://assets.devopsdays.org/events/2017/moscow/презентация-для-спонсоров-мероприятия-devopsdays-moscow-2017.pdf: 200
https://assets.devopsdays.org/events/2016/toronto/devopsdaystorontosponsorshipprospectus2016.pdf: 200
https://assets.devopsdays.org/events/2016/raleigh/2016-raleigh-sponsor.pdf: 200
https://assets.devopsdays.org/events/2016/siliconvalley/sponsorshipprospectusdodsv2016.pdf: 200
https://assets.devopsdays.org/events/2016/philadelphia/devopsdaysphl2016-prospectus.pdf: 200
https://assets.devopsdays.org/events/2016/minneapolis/devopsdaysmsp2016-prospectus.pdf: 200
https://assets.devopsdays.org/events/2016/vancouver/guide.pdf: 200
https://assets.devopsdays.org/events/2017/moscow/sponsorship-information-devopsdays-moscow-2017.pdf: 200
https://assets.devopsdays.org/events/2016/madison/devopsdays_madison_2016_prospectus.pdf: 200
https://assets.devopsdays.org/events/2016/kiel/devopsdays-kiel-2016-hotel-booking.pdf: 200
https://assets.devopsdays.org/events/2016/kansascity/sponsorshipprospectusv2016.pdf: 200
https://assets.devopsdays.org/events/2016/dallas/devopsdays_dallas_sponsor_prospectus_v0.5.pdf: 200
https://assets.devopsdays.org/events/2016/chicago/devopsdays-chicago-2016-prospectus.pdf: 200
```

Where URLs tested were:
<details>

```
https://assets.devopsdays.org/events/2023/new-york-city/dodnyc-23-sponsor-prospectus.pdf
https://assets.devopsdays.org/events/2023/los-angeles/devopsdayla2023_sponsor.pdf
https://assets.devopsdays.org/events/2023/melbourne/prospectus.pdf
https://assets.devopsdays.org/events/2023/rio-de-janeiro/devopsdays-rj-sponsor-2021.pdf
https://assets.devopsdays.org/events/2022/buffalo/prospectus.pdf
https://assets.devopsdays.org/events/2022/melbourne/prospectus.pdf
https://assets.devopsdays.org/events/2022/zurich/workshop-info-anand-bagmar.pdf
https://assets.devopsdays.org/events/2022/bengaluru/prospectus.pdf
https://assets.devopsdays.org/events/2022/los-angeles/devopsdayla2022_sponsor.pdf
https://assets.devopsdays.org/events/2022/los-angeles/devopsdayla2022_sponsor_v2.pdf
https://assets.devopsdays.org/events/2021/blumenau/devopsdays-blu-2021.pdf
https://assets.devopsdays.org/events/2021/raleigh/sponsorpackage-devopsdaysraleigh2021.pdf
https://assets.devopsdays.org/events/2020/guadalajara/prospectus.pdf
https://assets.devopsdays.org/events/2020/madrid/madridsponsorship.pdf
https://assets.devopsdays.org/events/2020/philadelphia/devopsdays_philadelphia_2020_prospectus.pdf
https://assets.devopsdays.org/events/2020/sao-paulo/novo_palestrante.pdf
https://assets.devopsdays.org/events/2020/houston/sponsorship-prospectus.pdf
https://assets.devopsdays.org/events/2020/houston/dodh-health-and-safety-update.pdf
https://assets.devopsdays.org/events/2019/washington-dc/resilience-engineering.pdf
https://assets.devopsdays.org/events/2019/washington-dc/engineers-guide-to-devops.pdf
https://assets.devopsdays.org/events/2019/washington-dc/emmanuel-apau.pdf
https://assets.devopsdays.org/events/2019/washington-dc/all-tech-is-debt.pdf
https://assets.devopsdays.org/events/2019/victoria/sponsordevopsdays2019.pdf
https://assets.devopsdays.org/events/2019/philadelphia/devopsdays_philadelphia_2019_prospectus.pdf
https://assets.devopsdays.org/events/2019/kansas-city/devopsdays2019-map-westport-commons-plexpod.pdf
https://assets.devopsdays.org/events/2019/kansas-city/2019-kansas-city-prospectus.pdf
https://assets.devopsdays.org/events/2019/chattanooga/devopsdays-chattanooga-2019-prospectus.pdf
https://assets.devopsdays.org/events/2018/victoria/sponsordevopsdays2018.pdf
https://assets.devopsdays.org/events/2018/raleigh/sponsorpackage-devopsdaysraleigh2018.pdf
https://assets.devopsdays.org/events/2018/phoenix/devopsdays_phoenix_2018_sponsor_prospectus.pdf
https://assets.devopsdays.org/events/2018/philadelphia/devopsdaysphl2018-prospectus.pdf
https://assets.devopsdays.org/events/2018/moscow/%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_devopsdays.pdf
https://assets.devopsdays.org/events/2018/moscow/partner%20proposal%20devopsdays%202018.pdf
https://assets.devopsdays.org/events/2018/kansas-city/prospectus.pdf
https://assets.devopsdays.org/events/2018/detroit/devopsdaysdetroit-prospectus-2018.pdf
https://assets.devopsdays.org/events/2018/chattanooga/devopsdays-chattanooga-2018-prospectus.pdf
https://assets.devopsdays.org/events/2018/boston/devopsdayssponsorprospectus2018.pdf
https://assets.devopsdays.org/events/2018/boise/prospectus.pdf
https://assets.devopsdays.org/events/2017/vancouver/sponsordevopsdays2017.pdf
https://assets.devopsdays.org/events/2017/vancouver/guide.pdf
https://assets.devopsdays.org/events/2017/philadelphia/devopsdaysphl2017-prospectus.pdf
https://assets.devopsdays.org/events/2017/moscow/презентация-для-спонсоров-мероприятия-devopsdays-moscow-2017.pdf
https://assets.devopsdays.org/events/2017/moscow/sponsorship-information-devopsdays-moscow-2017.pdf
https://assets.devopsdays.org/events/2017/hartford/devopsdays-hfd-2017-prospectus.pdf
https://assets.devopsdays.org/events/2017/detroit/devopsdaysdetroit-prospectus-2017.pdf
https://assets.devopsdays.org/events/2017/boston/boston2017sponsorprospectus.pdf
https://assets.devopsdays.org/events/2016/vancouver/guide.pdf
https://assets.devopsdays.org/events/2016/toronto/devopsdaystorontosponsorshipprospectus2016.pdf
https://assets.devopsdays.org/events/2016/siliconvalley/sponsorshipprospectusdodsv2016.pdf
https://assets.devopsdays.org/events/2016/raleigh/2016-raleigh-sponsor.pdf
https://assets.devopsdays.org/events/2016/philadelphia/devopsdaysphl2016-prospectus.pdf
https://assets.devopsdays.org/events/2016/minneapolis/devopsdaysmsp2016-prospectus.pdf
https://assets.devopsdays.org/events/2016/madison/devopsdays_madison_2016_prospectus.pdf
https://assets.devopsdays.org/events/2016/kiel/devopsdays-kiel-2016-hotel-booking.pdf
https://assets.devopsdays.org/events/2016/kansascity/sponsorshipprospectusv2016.pdf
https://assets.devopsdays.org/events/2016/dallas/devopsdays_dallas_sponsor_prospectus_v0.5.pdf
https://assets.devopsdays.org/events/2016/chicago/devopsdays-chicago-2016-prospectus.pdf
```

</details>

**Pull request merged**
