### PR TITLE
[FOR/2022] Add sponsor

### PR DESCRIPTION
**Pull request by renat473**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Missing logo & sponsor level in yml.

**Comment by renat473** [comment]
Hola 

PR with logo and sponsor level was included in PR from two days ago.

Do you also need to include in this same file?

**Review by MikeRosTX — APPROVED** [review]

**Comment by MikeRosTX** [comment]
Work on getting a bigger logo, because it can barely be seen. People are going to miss it.

**Comment by somatorio** [comment]
I think the problem with the logo is the white letters with a white background...
It is better to ask them for another logo, but that can be changed later I think

**Pull request merged**
