### PR TITLE
[MSK-2018] Added basic info

### PR DESCRIPTION
**Pull request by srusanov**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Hi @srusanov, please review the following changes we've made to make the website displayable and let us know if there's anything missing.
https://deploy-preview-4313--devopsdays-web.netlify.com/events/2018-moscow/welcome/

Please do a rebase to download all the changes, so that you can continue to make changes in the future.

**Comment by MikeRosTX** [comment]
@srusanov, you need to add yourself as an organizer in the **moscow-2018.yml** file so it appears here:
https://deploy-preview-4313--devopsdays-web.netlify.com/events/2018-moscow/contact/

**Comment by srusanov** [comment]
i'm added myself as an organizer

**Comment by bridgetkromhout** [comment]
I've synced the organizer list with what's been discussed in email, and I'm merging this now.

**Pull request merged**
