### PR TITLE
[OSLO-2017] Add EVRY as sponsor

### PR DESCRIPTION
**Pull request by Starefossen**
Add EVRY as Gold Sponsor.

CC @sveinung @steinim

### CODE REVIEW

**Comment by sveinung** [comment]
@Starefossen We should probably wait until the money is in the bank ;) That's our policy for sponsors in general at least.

**Comment by Starefossen** [comment]
Fine with me. According to Victoria/Macsimum the invoice should be on it's way today.

**Comment by sveinung** [comment]
Cool! Then it won't be long :)

**Comment by mattstratton** [comment]
I am going to mark this "do not merge" until confirmed?

**Comment by phrawzty** [comment]
> Fine with me. According to Victoria/Macsimum the invoice should be on it's way today.

Any updates? :)

**Comment by bridgetkromhout** [comment]
Hi, folks - if we don't hear in the next day or so that you're ready for this to be merged, we'll close without merging. It's already gone longer than we like to leave them. Thanks.

**Comment by bridgetkromhout** [comment]
Closing per @steinim.

**Pull request closed without merging**
