### PR TITLE
[DFW-2020] removing diamond level from sponsor.md 

### PR DESCRIPTION
**Pull request by baldwinjim**
Removing diamond level sponsor package for DFW

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @baldwinjim - are you sure you want to change a number of the items from 2020 to 2019? Also, the email is just dallas@devopsdays.org now.

**Comment by baldwinjim** [comment]
@bridgetkromhout MIke Rosado was bugging me to get the diamond sponser level removed but I was not sure about the email addresses.  Hold on this merge for now and I will update with the changes that you mentioned

**Comment by baldwinjim** [comment]
@bridgetkromhout that should be better now

**Comment by baldwinjim** [comment]
I think this good for now.  Please merge

**Comment by bridgetkromhout** [comment]
I fixed a few instances of the email - let's let it build and take a look.

**Comment by bridgetkromhout** [comment]
I see Diamond mentioned a few times on https://deploy-preview-8922--devopsdays-web.netlify.com/events/2020-dallas/sponsor - and is your coffee sponsorship actually already sold, as I don't see anyone listed with it.

**Comment by baldwinjim** [comment]
Yeah, I saw that too.  Thanks for your guidance on this.  I will make some more updates.  ;)

**Comment by bridgetkromhout** [comment]
Also https://github.com/devopsdays/devopsdays-assets/tree/master/events/2020 is where to put your prospectus so it can be available at the URL you're listing (https://assets.devopsdays.org/events/2020/dallas/DevOpsDaysDallas2020Sponsorships.pdf)

**Comment by baldwinjim** [comment]
I am waiting on Mike to provide the prospectus and will add it once he provides.  Again, appreciate the help here.

**Comment by bridgetkromhout** [comment]
Okay, please don't link to something that doesn't exist, though (because then people will click and get a broken link). You can change it to say "prospectus available shortly" or whatever you prefer.

**Comment by bridgetkromhout** [comment]
Are these two available at all now? They aren't listed at any of the levels.

```
Five (5) minute greeting and introduction during the opening session each day
Two (2) VIP backstage passes ($1,000 value)
```

**Comment by baldwinjim** [comment]
Honestly, I am not sure.  Mike just asked me to copy the 2019 sponsor page to 2020 folder and remove the diamond level column.  So, I think that you I have taken it much further than what he had asked for.  I am compiling a list of questions for him to answer regarding updates and will include these as well.  I guess, if you prefer, we can leave this on-hold until I get clarification and make updates according to his direction.

**Comment by bridgetkromhout** [comment]
Looking at https://assets.devopsdays.org/events/2019/dallas/DevOpsDaysDallas2019Sponsorships.pdf I've answered my own question - those were part of the package you're not doing anymore. I would like to get this merged so I'll make a few changes (removing those two lines, removing the link to the missing prospectus) and then get this in. Then you can make iterative improvements as needed.

**Comment by baldwinjim** [comment]
Sounds good.  Thanks again for your guidance.

**Pull request merged**
