### PR TITLE
[Boise 2020] Updating the website

### PR DESCRIPTION
**Pull request by tresni**
* Added link to papercall for CfP
* Corrected sponsorship information
* Added Simplot as sponsor
* Updated Jane's employer information

### CODE REVIEW

**Comment by mattstratton** [comment]
Note! If you add a field to `data/events/2020-boise.yml` like this:

```
cfp_link = "https://www.papercall.io/devopsdaysboise"
```
That will add a Propose button to the main welcome page also :)

**Comment by mattstratton** [comment]
You also should set the cfp dates in the data file as well - these lines here:

https://github.com/tresni/devopsdays-web/blob/2020-boise/data/events/2020-boise.yml#L16-L21

```
# Leave CFP dates blank if you don't know yet, or set all three at once.
cfp_date_start:  # start accepting talk proposals.
cfp_date_end:  # close your call for proposals.
cfp_date_announce:  # inform proposers of status

cfp_link: "" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
```

**Comment by tresni** [comment]
Hey @mattstratton I've pushed a change to incorporate the notes you've mentioned.

**Comment by mattstratton** [comment]
Looks good! I'll merge it!

**Pull request merged**
