### PR TITLE
[OSL-2017] new standards, organizer info and confirmed speakers

### PR DESCRIPTION
**Pull request by steinim**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by mattstratton** [comment]
Not sure why the deploy preview failed (some kind of netlify error) so i'm kicking off another one.

**Comment by mattstratton** [comment]
If you want to enable the speakers menu item, you'll want to un-comment it from [this line](https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2017-oslo.yml#L32)

**Comment by steinim** [comment]
Yes. We're not quite ready yet. I'll uncomment it when we're ready to announce.

**Comment by steinim** [comment]
Can you have a look at this one too? https://github.com/devopsdays/devopsdays-assets/pull/11

**Comment by mattstratton** [comment]
I made some comments in that PR as well - my only concern is that if you try to set `srcset`, it might get overridden in our post-processing of the release, so that might be tricky.

**Pull request merged**
