### PR TITLE
[CUA-2020] Add devopsday - criciuma

### PR DESCRIPTION
**Pull request by guilhermealano**
#9354

### CODE REVIEW

**Comment by mattstratton** [comment]
There are some issues with whitespace in the data file with the organizer section

**Comment by mattstratton** [comment]
There are merge conflicts for some reason as well. Does this PR include the fixes from @bridgetkromhout in the previous PR which you closed?

**Comment by guilhermealano** [comment]
> Há conflitos de mesclagem por algum motivo também. Este PR inclui as correções de @bridgetkromhout no PR anterior que você fechou?

It was me, because I ended up submitting a new PR, and closed the old one. :(

**Comment by bridgetkromhout** [comment]
Hi, it looks like all five organizers work at the same place. We require organizers from at least three different employers.

**Comment by somatorio** [comment]
Olá, como foi dito na nossa reunião inicial, precisamos de ao menos 3 empresas diferentes na organização, pois caso contrário o evento pode ser visto como "o evento da empresa x"

**Comment by bridgetkromhout** [comment]
Closing unmerged because it is replaced by https://github.com/devopsdays/devopsdays-web/pull/9447.

**Pull request closed without merging**
