### PR TITLE
[RDU-2019] Add rdu program

### PR DESCRIPTION
**Pull request by mattstratton**
This PR updates the RDU program from the reverted change; this should work now.

### CODE REVIEW

**Comment by mattstratton** [comment]
@normalfaults 	please review this once the tests have passed. 

Couple things I noticed:

1) Ignites should be specified slightly differently (take a look at the YAML to see what I did for this). 
2) All talks (ignites, talk, or workshop) have the "type" of "talk" in their file.
3) There was SOMETHING in the whitespace or who knows what that made a couple of the items bail. I typed things by hand and it worked then.

**Comment by normalfaults** [comment]
Is there a way to specify the time for the ignites ? We are having them in the middle of the day instead of the end of each day.

**Comment by mattstratton** [comment]
Yes. There is a section for it. You'll see it in the preview when it's done, but for now, you can see how it looks here for Chicago:

https://devopsdays.org/events/2019-chicago/program/

**Comment by normalfaults** [comment]
Excellent. Thank you for helping fix these. It was a lot of copying and pasting. Really appreciate the help. Everything looks great.

**Comment by mattstratton** [comment]
I made one more small fix. Once this is done building the preview I'll merge it!

**Comment by bridgetkromhout** [comment]
Hi, @normalfaults - you currently have `Adam Lefkowitz - Agile transformation patterns that are being repeated in DevOps transformations` listed on both days. Do you plan to have that Ignite talk twice? Thanks.

**Comment by normalfaults** [comment]
Yes. 

Nirmal Mehta

**Comment by bridgetkromhout** [comment]
Okay, @normalfaults, merged this, and it will be live in 10-15min. Note that you'd uncomment these lines if you wanted program and speakers linked in the front page text as well as in the menu: https://github.com/devopsdays/devopsdays-web/blame/master/content/events/2019-raleigh/welcome.md#L48-L64

**Comment by normalfaults** [comment]
Noted and thank you for the help. 

Nirmal Mehta

**Pull request merged**
