### PR TITLE
[AMS-2018] update Xebia logo

### PR DESCRIPTION
**Pull request by dpnl87**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please rename the **_xebia.png_** file to _**xebia-ams.png**_ since this is a sole company with offices in Amsterdam. Once completed, we'll merge this PR.

**Comment by bridgetkromhout** [comment]
If https://xebia.com/ and https://xebialabs.com/ aren't the same thing, we should list them by the words "xebia" and "xebialabs". Please clarify.

**Comment by yvovandoorn** [comment]
So XebiaLabs (software company) was founded by the company Xebia (consulting / services). It seems initially the png for XebiaLabs was named wrong (xebia.png vs xebialabs.png).

I agree with @MikeRosTX that the interim solution is to call this one xebia-ams.png. 

Thoughtworks has similar woes with their consulting vs software arms :-).

**Comment by MikeRosTX** [comment]
@dpnl87 can you please rename the **_xebia.png_** file to **_xebia-ams.png_**? 
Once completed, we'll merge this PR.

**Comment by bridgetkromhout** [comment]
Now that I've had time to look into this, it's clear that "xebialabs" is what's being used everywhere anyhow, so it's okay to update this. See also: https://github.com/devopsdays/devopsdays-web/pull/4338

**Pull request merged**
