### PR TITLE
[MAR-2018] -  Adding schedule, sponsors and fixing speakers

### PR DESCRIPTION
**Pull request by souzaxx**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@souzaxx you have some errors. Conflicting files with content/events/2018-maringa/index.md.
Have you done a rebase?  If you need help, chat us up on Slack.

**Comment by souzaxx** [comment]
Hi Mike, I'm not sure what happened here.. I saw that some files has changed when I did the pull, but in my branch was everything okay..

I'm also not sure how to login on Slack.. Sorry about that

**Comment by bridgetkromhout** [comment]
Hi, @souzaxx - you have an account on https://devopsdays.slack.com - you can reset your password there. 

I'm making a few corrections so you don't accidentally link to other events.

**Comment by bridgetkromhout** [comment]
You are still missing some of your intended content, it looks like, but what's there is good, so I'm merging it. You can add the missing info later if you decide to. Thanks!

**Pull request merged**
