### PR TITLE
Use existing docker image

### PR DESCRIPTION
**Pull request by adrianmoisey**
Fixes https://github.com/devopsdays/devopsdays-web/issues/4127

I still need to figure out how Travis is setup and replace that one.

### CODE REVIEW

**Comment by kmugrage** [comment]
"works on my machine"

**Comment by mattstratton** [comment]
My only concern is that the baseURL doesn't get set...if you build this, what are the paths to the CSS, etc, in the html?

**Comment by bridgetkromhout** [comment]
Hmm, Travis doesn't seem to like this: `The command "docker run --name "hugo-server" -P -v $(pwd):/site jojomi/hugo" failed and exited with 1 during .`

**Comment by adrianmoisey** [comment]
Replaced by https://github.com/devopsdays/devopsdays-web/pull/4536

**Pull request closed without merging**
