### PR TITLE
[NYC-2020] Add solarwinds, instana, appdynamics to sponsors

### PR DESCRIPTION
**Pull request by kuritz**
Solarwinds asked for a logo update. I tried to duplicate what I saw in the repo, but not sure if something else needs to be changed too.

### CODE REVIEW

**Comment by adrianmoisey** [comment]
@kuritz With regards to the logo change, it looks like you're almost there. Take a look at the docs to see what else you need to do.

I'm happy to help if you need any.

**Comment by kuritz** [comment]
Thanks @adrianmoisey. I looked through a number of the docs we have, but I wasn't able to find the entry on this. Can you point me to it?

**Comment by bridgetkromhout** [comment]
Hi @kuritz - the lore you seek is here: https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor-image-or-data (and yes, it is the dark art of `sed` - I apologize for the universe being sadness.)

**Comment by adrianmoisey** [comment]
I was totally going to paste the URl, but seem to have forgotten. Thanks Bridget for saving the day!

**Comment by kuritz** [comment]
Thanks Bridget! I did the dark arts thing 😂

**Pull request merged**
