### PR TITLE
DevOps Days Tokyo 2020 logos

### PR DESCRIPTION
**Pull request by ngannon**
Trying to get logo up for DevOps Days Tokyo 2020

logo
devopsdays-web/static/events/2020-tokyo

### CODE REVIEW

**Comment by mattstratton** [comment]
Did this work locally for you?

**Comment by ngannon** [comment]
Trying that now. Fingers crossed! 

Sorry, first time doing this. Learning as I go.

**Comment by mattstratton** [comment]
No worries! Just trying to help troubleshoot (and I’m on mobile so it’s harder to see stuff)

**Comment by ngannon** [comment]
I appreciate that! I tried to create an folder for this locally and pushed it.

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/devopsdays/devopsdays-web/pull/8477.

**Pull request closed without merging**
