### PR TITLE
fix registration TLV

### PR DESCRIPTION
**Pull request by gilzellner**

### CODE REVIEW

**Comment by phrawzty** [comment]
Hi there,

The commit message says "fix registration TLV", which appears to have been done in `registration.md`; however, this PR also includes an alternate sponsor logo for logz.io.  Is that intentional?

**Comment by gilzellner** [comment]
no, it was done by mistake, i apologize.

**Comment by phrawzty** [comment]
> no, it was done by mistake, i apologize.

Not a problem - just remove it from the PR, and then I'll merge the change to `registration.md`. 😄

**Comment by gilzellner** [comment]
done

**Pull request merged**
