### PR TITLE
[VAN-2024] CFP Page 

### PR DESCRIPTION
**Pull request by frozenprocess**
This PR adds a bit of clarity for CFP submission.

### CODE REVIEW

**Review by cstyan — APPROVED** [review]
lgtm

**Review by terraboops — APPROVED** [review]
awesome! thanks!

**Comment by phrawzty** [comment]
👋 This PR is fine. :)

In a _future_ PR you may wish to take advantage of the `static/events/YYYY-city/logo-square.jpg` pattern, which will replace the generic gear-brain logo on the main page with that of your event.
image

**Comment by frozenprocess** [comment]
Thanks @phrawzty !
I will adjust it in our next PR

**Pull request merged**
