### PR TITLE
[2017-brasilia] Add sponsors

### PR DESCRIPTION
**Pull request by adrianovieira**
- Rancher Labs
- Configr

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @adrianovieira - please do not put "2017" at the beginning of a sponsor name - we're moving away from using that.  Also, "rancher" with the image at https://github.com/devopsdays/devopsdays-web/blob/master/static/img/sponsors/rancher.png is the same company as the Rancher Labs you're trying to add. If Rancher asked you to use a different logo, do you know if they want it updated everywhere going forward, used only in .br, or something else?

**Comment by adrianovieira** [comment]
Ok! I can update the name cuting the 2017 at the begining. I noticed that Rancher already has one logo there, but it is not the correct brand logo. Than I thought I could update it according to their brand rules (http://rancher.com/brand-guidelines/) which tell us to use "Rancher Labs logo'.

But I'll update all our logos according to your tip Bridget.

**Comment by adrianovieira** [comment]
I hope everything is ok now.

**Comment by bridgetkromhout** [comment]
Thanks. We'll merge this for now, and I'm hoping @kmugrage can follow up on the logo updating  issue, as I know he knows how to properly update logos if need be.

**Pull request merged**
