### PR TITLE
[VAN-2018] Adjust sponsorship

### PR DESCRIPTION
**Pull request by tylermauthe**
Add salesforce, chef, statsearchanalytics, polyglot-van and adjust dynatrace level

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please check if you create a **polyglot-van.yml**?  Because it's not showing up in the preview:
https://deploy-preview-4217--devopsdays-web.netlify.com/events/2018-vancouver/welcome/

**Comment by tylermauthe** [comment]
Whoops, thank you! I've added the sponsor logo.

**Comment by MikeRosTX** [comment]
Jut adding the logo is not going to make it show up.
You need to create a **polyglot-van.yml** file under you **data/sponsors/** structure.

**Comment by tylermauthe** [comment]
Oh, I see. Sorry again. I've updated as requested.

**Comment by tylermauthe** [comment]
Sorry - I decided to change the sponsor name again. There's only one Polyglot, if there's more one day they'll likely share the logo too. 🙂

**Comment by MikeRosTX** [comment]
You need to rename this file to **polyglot.yml**
devopsdays-web/data/sponsors/**polyglot.yaml**

**Comment by tylermauthe** [comment]
Already done, cheers:
https://github.com/devopsdays/devopsdays-web/pull/4217/files#diff-505fbd241843c9628b4df661a9691f44

**Comment by tylermauthe** [comment]
Jeepers... I'm sorry, it's been a long day. I hope we are good now.

**Comment by MikeRosTX** [comment]
All good....

**Pull request merged**
