### PR TITLE
[2016_Brasília] Update CFP and add sponsor

### PR DESCRIPTION
**Pull request by adrianovieira**
fix erroneous deletion of ga_tracking

### CODE REVIEW

**Comment by adrianovieira** [comment]
Although I could see on [*"deploy/netlify Deploy preview ready!" on http://deploy-preview-1098.devopsdays-web.netlify.com/*](http://deploy-preview-1098.devopsdays-web.netlify.com/) our event updates (by this PR)... Why do we can't see it on production site?

Are there something we need to fix, yet?

Please, let we know.

**Comment by mattstratton** [comment]
There's some very weird code in this merge - looks like old webby code. @bridgetkromhout can you look?

**Comment by mattstratton** [comment]
Never mind. It's because you are mixing markdown and HTML in the same file. According to markdown rules if there is HTML in the file then markdown will not be processed.

**Comment by adrianovieira** [comment]
Humm...
May be I don't understand what did you mean @mattstratton.

mainly because your **check" built a deploy/preview with no errors - as you notice from the links above. Then I don't belive mixing *md+html* is the problem - and I think there are some events page (not only our own) that has some mix of md+html - where we catched some excerpt.

**Comment by adrianovieira** [comment]
And also...

 we can't forget that *hugo* engine convert everything from a page (even with a mix of md+html) to one html page.

**Comment by mattstratton** [comment]
Relevant link - https://discuss.gohugo.io/t/markdown-not-being-rendered-within-html-block/2532/3

**Comment by adrianovieira** [comment]
I don't understand yet..

As we can see here http://deploy-preview-1098.devopsdays-web.netlify.com/events/2016-brasilia/welcome/ as a result of your process, 
what happen with your automated check which built the preview site and everything is ok (sponsor addition and proposal update)?

**Comment by bridgetkromhout** [comment]
Hi, @adrianovieira - can you help me understand what's wrong here? Is there something missing from the live site at https://www.devopsdays.org/events/2016-brasilia/welcome/ which you submitted in this PR? I must have missed whatever it is. Thanks.

**Comment by adrianovieira** [comment]
Actually  I don't know what happened with this PR after it was merged on production.

As you can see on our commits (and on diffs) we added a "Supporter sponsor" and we also deleted/updated some sentences on our propose page.

For those commits we can see the results  here http://deploy-preview-1098.devopsdays-web.netlify.com/events/2016-brasilia/welcome/ and here http://deploy-preview-1098.devopsdays-web.netlify.com/events/2016-brasilia/propose/ which is the result of the automated checks processes and also of a build preview for PR.

On the other hand we can't see those updates on the production site - that I think also contain  this PR included.


Hope I explain well enough this time

**Comment by adrianovieira** [comment]
Hi!
one more information for this.

I just did a `git pull` of your master branch and everything I did produce a site with no problem. I did two test, as shown below:

1. for a `hugo server -w --log --verbose --verboseLog --bind=0.0.0.0 -D`

another

1. for:
    - `hugo --log --verbose --verboseLog -d /tmp/website`
    - `cd /tmp/website`
    - `python -m SimpleHTTPServer 1313`

For both of each test the site was served with no problems for all events - including our own. For this case our event has the PR included and show everything we did for this PR.

Then we think you have a problem with some steps there.

Could you check, please?

**Comment by adrianovieira** [comment]
Hi Folks!

Thanks a lot by your attention.

Now our event on the live site is fine.

Thanks.

Cheers.

**Comment by bridgetkromhout** [comment]
Thanks for the details. The weird thing is that the live site was already working for me (yesterday). I suspect a caching issue. Anyhow, I'm glad it's displaying for you correctly now.

**Pull request merged**
