### PR TITLE
program_entry Shortcode

### PR DESCRIPTION
**Pull request by tresni**
Includes example of use for Boise 2016.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks, but please put the shortcode change in a different PR, per the guidelines: https://github.com/devopsdays/devopsdays-web/blob/master/CONTRIBUTING.md#guidelines

**Comment by mattstratton** [comment]
Normally I would agree with @bridgetkromhout about splitting these, but since I would like to see what the shortcode actually DOES, we do need the content in the PR as well. 

I've usually done this in the past using my own city's event as the example event.

**Comment by mattstratton** [comment]
We need to keep this change in mind when working on #636 in the future.

**Comment by tresni** [comment]
@mattstratton Appropriate directory is actually `themes/devopsdays-responsive/layouts/shortcodes/` and I've moved the shortcode there.

**Pull request merged**
