### PR TITLE
[STHLM-2018] Organiser pictures

### PR DESCRIPTION
**Pull request by lsc**
Organiser pictures and some name fixes.

### CODE REVIEW

**Comment by phrawzty** [comment]
Wow that is a crazy commit message. Would you mind terribly cleaning that up and rebasing? If you need help just ask. Thanks!

**Comment by lsc** [comment]
@phrawzty yeah, wtf is that :D I'll have a look

**Comment by phrawzty** [comment]
Any update?

**Comment by bridgetkromhout** [comment]
If this can't be fixed I'm fine with cherry-picking too?

**Comment by bridgetkromhout** [comment]
I'm going to merge these commits in https://github.com/devopsdays/devopsdays-web/pull/3884 where I fixed that commit message.

**Pull request closed without merging**
