### PR TITLE
[ATX-2019] Add more gold sponsors

### PR DESCRIPTION
**Pull request by scottsbaldwin**
* Avi Networks
* Signal Sciences

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@scottsbaldwin have you done a rebase lately? If not, please do so.

**Comment by scottsbaldwin** [comment]
@MikeRosTX, yes, I had rebased. I must have missed something else somewhere.

**Comment by MikeRosTX** [comment]
Need to see if @bridgetkromhout or @mattstratton can figure out why **_ci/circleci: test — Your tests failed on CircleCI_**.

**Comment by bridgetkromhout** [comment]
I don't see why this test is failing.

**Comment by mattstratton** [comment]
Something weird is happening when circle is building node packages - my guess is they changed the version of node and now it’s throwing errors instead of warnings. Sigh.

**Pull request merged**
