### PR TITLE
[CAI-2019] Adding speakers and program

### PR DESCRIPTION
**Pull request by aameen79**
Adding speakers and program

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @aameen79 - if you want the program to stay on this site, I strongly recommend using the `add_program.sh` script: https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_program.sh

If you need to use that PDF as well, you should submit it to this repo. Having the program only exist offsite can lead it it being lost later.

Please let us know if you want assistance with building the program - thanks!

**Comment by mattstratton** [comment]
>If you need to use that PDF as well, you should submit it to this repo

It would be better to put it in devopsdays/devopsdays-assets and link to it here, although not having looked through this PR all the way that might not be what @bridgetkromhout 	had in mind.

**Comment by mattstratton** [comment]
I pushed the PDF to the `devopsdays-assets` repo for you - you can now use this link `https://assets.devopsdays.org/events/2019/cairo/DevopsDays-Cairo-2019-Agenda.pdf` instead of the off-site link.

I do agree with @bridgetkromhout that generating a program and talk pages would make a better experience for site visitors!

**Comment by aameen79** [comment]
Hi @bridgetkromhout 
I agree and will do so (build the program and keep PDF as well), this just a quick thing I need it to appear until I build the program by script.
So kindly merge and I'll follow it with another pull request may be tomorrow :)

Thanks @mattstratton I'll use this link.

**Comment by bridgetkromhout** [comment]
Sounds great - thanks!

**Pull request merged**
