### PR TITLE
[SITE] add possibility to hide sponsorlevels without sponsors #14322

### PR DESCRIPTION
**Pull request by toshywoshy**
The possiblitiy to add ```sponsors_showempty``` to the data yaml file
This options hides the sponsor levels with no sponsors
See #14322  for more details

### CODE REVIEW

**Comment by SeifElbayomi** [comment]
I suggest that https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md 
Is updated to reference this option and how to use it

**Comment by mattstratton** [comment]
> I suggest that https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md Is updated to reference this option and how to use it

I would add it to the [REFERENCE.md](https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#sponsor-levels) section as that details all the fields and this is a new field.

not a bad idea to add it to the overall README but it definitely needs to be documented in REFERENCE

**Review by mattstratton — CHANGES_REQUESTED** [review]
Please update the REFERENCE.md with this new field (specifically in this section): https://github.com/devopsdays/devopsdays-web/blob/34f89e185e9bc2b590b96bdd33ba1cfafad0c747/themes/devopsdays-theme/reference.md?plain=1#L173-L181

**Comment by toshywoshy** [comment]
I do not want to add it to the README in the utilities, as there is no script for this.
This option needs to be set manually, if not specified the default mode is used, displaying all sponsor levels.
I have added the option to REFECENCE below `sponsors_accepted`

**Review by mattstratton — APPROVED** [review]

**Pull request merged**
