### PR TITLE
[PT2024] adding keynote 04 - charity majors

### PR DESCRIPTION
**Pull request by eduardopiairo**
* adding keynote 04 - charity majors

### CODE REVIEW

**Comment by mattstratton** [comment]
@eduardopiairo please update your fork from origin - it’s behind and missing some key files 
IMG_2756

**Comment by mattstratton** [comment]
Please also allow maintainers to make changes too your pull requests as explained here 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by mattstratton** [comment]
To be clear, this is what is blocking this PR from being merged:

@eduardopiairo please update your fork from origin - it’s behind and missing some key files

**Comment by eduardopiairo** [comment]
@mattstratton I updated my fork.

**Pull request merged**
