### PR TITLE
[BMORE-2020] Initial commit of baltimore 2020

### PR DESCRIPTION
**Pull request by jaumann**
Also need the email created and slack updated if possible. Thanks!!

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @jaumann - when we merge this, we'll remove all the not-listed organizers from email (and Slack unless they organize something else). Given that, are you sure this is the lineup you want to start with? (You've removed a lot of the 2019 team.)

Also, email is now baltimore@devopsdays.org for all years moving forward - we won't make a "2020" address.

**Comment by jaumann** [comment]
@bridgetkromhout That sounds good. Yeah, we'll start with just this team for now. We mostly use an external slack, so this is the main organizers. As for the email, that makes things easier for us! Thanks so much for making that change!

**Comment by bridgetkromhout** [comment]
@jaumann I'll be looking at this again later tonight. I'm not sure why you're force-pushing but you've overwritten the update I made - please put the organizer-email back to `baltimore@devopsdays.org` if you're going to overwrite changes.

**Comment by jaumann** [comment]
@bridgetkromhout oh jeeze, I'm really sorry. Force of habit for keeping the branch up to date with rebasing master. I totally messed that one up. I've put the change in to update the PR. Once again, really sorry about that!

**Comment by bridgetkromhout** [comment]
I've corrected the Slack and google groups membership to match this PR for 2020.

**Comment by bridgetkromhout** [comment]
Hi, @jaumann - I'm going to merge this with a couple of fixes I made. Please be sure to pull upstream in before you send any more changes - specifically, definitely don't try to revert my changes, as they are necessary - the fix I made to your sponsorship page fixes this:

Screen Shot 2019-10-14 at 10 45 56 PM

**Pull request merged**
