### PR TITLE
PDF fix test (with test PDF re-added).

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Possible partial fix for https://github.com/devopsdays/devopsdays-web/issues/6542. Minimally tested but seems to help in this case.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Improved: doesn't run into sponsors
Question: can we make it have a better experience for a pop-out-to-see-fully link? https://deploy-preview-8076--devopsdays-web.netlify.com/events/2017-minneapolis/program/kristen-womack/

**Comment by mattstratton** [comment]
Hmm. if it doesn't show the whole slide without scrolling, I don't see the value in embedding the PDF instead of just using the "slides" type link, which provides a link to the slides instead (see this example):

image

**Comment by mattstratton** [comment]
> Question: can we make it have a better experience for a pop-out-to-see-fully link?

We could definitely put a "link to PDF" hyperlink above it for sure...

**Comment by mattstratton** [comment]
I suspect that the true fix for this is going to be doing some CSS magic - we'll have to maybe add a class for a div for PDF embeds, and then we can reference that class in the code. 

I think this fix is okay for now (it makes existing ones work okay) but I would open a new issue to make it look more ideal (and to include the "link to the pdf" link)

**Comment by mattstratton** [comment]
I found a slightly better fix:

```
           <div>
              <object data="{{.Params.pdf}}" type="application/pdf" width="300" height="200">
              alt : <a href="{{.Params.pdf}}">{{ .Title }}</a>
              </object>
            </div> 
```

The width and height need to be tweaked I think though.

**Comment by mattstratton** [comment]
My fix (above) looks like this:

image

**Comment by mattstratton** [comment]
Making it 600x400 looks pretty good:

image

**Comment by mattstratton** [comment]
The hyperlink to the PDF isn't necessary, because if you hover over it in this fix, it gives you the ability to download, etc:

image

**Comment by bridgetkromhout** [comment]
Okay, cool. Can you add changes to this PR?

**Comment by mattstratton** [comment]
Ah crap. It looks stupid on a smaller desktop (looks fine on mobile though)

image

**Comment by mattstratton** [comment]
I'll add the changes to the PR so you can play with them in the preview though (can always back them out)

**Comment by mattstratton** [comment]
Try out your test URL with my fix and see how it looks on your screen, etc

https://deploy-preview-8076--devopsdays-web.netlify.com/events/2017-minneapolis/program/kristen-womack/

**Comment by bridgetkromhout** [comment]
At scaled-down sizes (smaller than 600x400) it doesn't look right (missing the action links). However, given that it looks fine on my 12" MacBook in a full-sized Chrome window at the default font size, I think this is an incremental improvement.

**Comment by mattstratton** [comment]
Given that nobody has brought this up but you and me, Bridget, I think that means we can merge this as fixed :)

:shipit:

**Comment by bridgetkromhout** [comment]
Wellll. I am unconvinced it works for the github PDF link of Q's (see https://github.blog/2015-03-17-pdf-viewing/) but that's a corner case.

**Pull request merged**
