### PR TITLE
[2019-TLV] Program & Speaker Edits

### PR DESCRIPTION
**Pull request by shar1z**
My localhost is throwing an error on the andrew-gooding files, not sure exactly what is wrong - have checked for illegal characters, typos, spacing etc.

Rebuild failed:

Failed to render pages: render of "page" failed: "/Users/sharonezitzman/documents/github/devopsdays-web/themes/devopsdays-theme/layouts/talk/single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: failed to resolve ref: page reference "/events/2019-tel-aviv/speakers/andrew-gooding" is ambiguous

 {{- range .Params.speakers -}}     {{- $.Scratch.Set "speakername" . -}}     {{- $p := $.Site.GetPage (printf "events/%s/speakers/%s" $e.name ($.Scratch.Get "speakername")) -}}     {{- if $p -}}     {{- with $p -}}
-- | --

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I'm pretty sure that at one point we had a step in the build process that looked for `.jpg` but not `.jpeg`. That may not matter anymore since we removed most of the resizing; just mentioning it in case it leads to weirdness.

**Comment by shar1z** [comment]
I can fix that quickly - not sure why some files save with the e and some without.  I'll quickly fix and push again.

**Comment by bridgetkromhout** [comment]
Looks good! I'll get this merged in and then we can see what still needs fixing!

**Comment by shar1z** [comment]
Thanks!!

**Pull request merged**
