### PR TITLE
[AMS-2020] Move registration to the video platform

### PR DESCRIPTION
**Pull request by PaulusTM**
Please hold for technology validation

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Ping me on Slack.

**Comment by mattstratton** [comment]
The HTML had some weird quote formatting; I fixed it I think.

**Comment by MikeRosTX** [comment]
Waiting on @PaulusTM for approval before merging.

**Comment by PaulusTM** [comment]
Thank you for the assist @mattstratton! 

@MikeRosTX I've removed the WIP and it's ok to merge when the last change is successful. Thank you for the assistance as well.

**Pull request merged**
