### PR TITLE
[Baltimore-2017] Add twitter handles for sponsors

### PR DESCRIPTION
**Pull request by nathenharvey**
* @acesinc
* @bookerdimaio
* @cloudpassage
* @columnit
* @fearlesssol
* @nsoneinc
* @opsgenie
* @pivotal
* @puppetize
* @quetechnology
* @redhatsoftware
* @softwaredeftalk

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by nathenharvey** [comment]
These have no real impact on the functionality of the site but do provide an easy, common way for organizers to find twitter handles of sponsors.  This information can be used when thanking sponsors, building [twitter lists](https://twitter.com/DevOpsDaysBmore/lists/dodbmore-2017-sponsors/members), and for other purposes.

**Comment by mattstratton** [comment]
@nathenharvey - actually, what I would think would be super rad is if you could post an issue on https://github.com/devopsdays/devopsdays-theme as a feature request for this functionality, as we can figure out how to start using it in the future.

**Comment by nathenharvey** [comment]
closed/reopened to kick off travis again

**Comment by nathenharvey** [comment]
@mattstratton sure, I'll open an issue.  are you opposed to taking this PR in advance of adding functionality though?

**Comment by mattstratton** [comment]
@nathenharvey no problem merging the PR; my issue is more that if you add this data here and we don't track using it as a feature request, we'll forget it exists, etc.

**Comment by nathenharvey** [comment]
I've opened https://github.com/devopsdays/devopsdays-theme/issues/239

**Pull request merged**
