### PR TITLE
[2019-TLV] Added Ignites Speakers + Last Sponsors

### PR DESCRIPTION
**Pull request by shar1z**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @shar1z! This PR was flagged for insecure mixed http/https content. When I took a look, I found that the content of your PR is fine. The problem lies with this branch on your fork being far behind: `This branch is 1 commit ahead, 1358 commits behind devopsdays:master.`

I suggest bringing this branch up to date so you don’t accidentally flag issues in our automated tests. Thanks.

**Comment by bridgetkromhout** [comment]
We have some guidance in https://github.com/devopsdays/devopsdays-web/blob/master/CONTRIBUTING.md#editing-your-site but if you don’t want to make a new branch in your fork, that’s fine - update master on your fork and then merge master into your branch.

**Comment by shar1z** [comment]
Thanks Bridget - I thought I was up to date - had a really long git fetch upstream - not sure why it didn't actually update.

I'll fix. Thanks

**Comment by shar1z** [comment]
Thanks Bridget - I thought I was up to date - had a really long git fetch upstream - not sure why it didn't actually update.

I'll fix. Thanks

**Comment by bridgetkromhout** [comment]
After I had a chance to check more carefully I can verify there is no http content here, so I've merged it. FYI you're still not up to date, though.

**Pull request merged**
