### PR TITLE
[OSLO-2020] placeholder for virtual 2020 events in Oslo

### PR DESCRIPTION
**Pull request by bruvik**
Devopsdays Oslo 2020 is cancelled, but we are doing a series of online meetups, so creating a page to inform sponsors and attendees, and to link to our meetup group

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
You probably want to remove the files that don't make sense (like the location file and the CFP file).

**Comment by bruvik** [comment]
Hi @bridgetkromhout , i removed a few unused files. All currently listed organizers are still on the team, but we have a few new team members. I can add them to this pull request, or I can do a separate pull request with the new members later

**Comment by mattstratton** [comment]
@bruvik make sure you email info@deveopsdays.org with the correct list of organizers when you add them to the site (either in this PR or a future one)

**Comment by bruvik** [comment]
Of course @mattstratton ! 🙂

**Comment by bruvik** [comment]
If you let this pull request stay open a few more days, I’ll do all changes including new members in one go. I asked current members if they want to change any information, so I’ll do that as well

**Comment by mattstratton** [comment]
I just confirmed the mailing list updates. This looks good. I'll merge it now.

**Pull request merged**
