### PR TITLE
Add basic structured metadata to event pages for Google

### PR DESCRIPTION
**Pull request by esigler**
Howdy!

This change puts in the basics for JSON-LD metadata on an event page, with
a little bit of logic for if the city has been duplicated into the location.
Concatenating the image URL together took far longer than I want to admit.

Are there other types of metadata that y'all would want included?  If the
address was available in the event yaml, that might surface up better in 
search results?

Example output on what would be https://www.devopsdays.org/events/2016-chicago/welcome/:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ExhibitionEvent",
  "name": "DevOpsDays Chicago 2016",
  "startDate": "2016-08-30",
  "endDate": "2016-08-31",
  "url": "https://devopsdays.org/events/2016-chicago/welcome/",
  "image": "https://devopsdays.org/events/2016-chicago/logo.png",
  "location": {
    "@type": "Place",
    "name": "Summit West, Chicago",
    "address": "41.882219, -87.640530"
  }
}
</script>
```

Addresses https://github.com/devopsdays/devopsdays-web/issues/799

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks, Eric! @mattstratton wants to look at this and he's right in the midst of setting up for devopsdays Chicago, so you'll hear back after that's over.

**Comment by mattstratton** [comment]
When I run this through the structured testing tool, one of the warnings that comes up is:

`The description field is recommended. Please provide a value if available.`

@esigler do you think it would be easy to add that in and then re-submit the PR? I think that the description can be pretty simple for right now - or alternately, we could create a new issue to add a better event description metadata option.

**Comment by esigler** [comment]
@mattstratton I was wondering what the best choice was for `description`. I'm a tiny bit worried that all events having the same `description` could be seen as spammy, but I might be paranoid.  I've pushed up a branch with a description field & default text in the template, and adds it to the example yaml.  Example output is now:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ExhibitionEvent",
  
    "description": "The conference that brings development and operations together.",
  
  "name": "DevOpsDays Chicago 2016",
  "startDate": "2016-08-30",
  "endDate": "2016-08-31",
  "url": "http://devopsdays.org/events/2016-chicago/welcome/",
  "image": "http://devopsdays.org/events/2016-chicago/logo.png",
  "location": {
    "@type": "Place",
    
      "name": "Summit West, Chicago",
    
    "address": "41.882219, -87.640530"
  }
}
</script>
```

& validated that if an event yaml doc contains `description` with a value, it populates instead of the default text.

**Comment by mattstratton** [comment]
I think this should be fine - we can probably add a feature request in the future to construct the "default" to somehow include the city name, but for now it works.

**Pull request merged**
