### PR TITLE
[TPA 2019] - Added Clearly Agile - Thank you!

### PR DESCRIPTION
**Pull request by jmgress**
[TPA 2019] - Added Clearly Agile - Thank you!

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@jmgress - Please resolve this conflict. Best way would be is to do a rebase. Because we cannot merge this PR until conflict is resolved.

image

**Comment by jmgress** [comment]
The file it is conflicting with I am trying to delete

**Comment by MikeRosTX** [comment]
Understood, please try doing a rebase.

**Comment by jmgress** [comment]
Please close pull request and will reopen.

**Pull request closed without merging**
