### PR TITLE
[MDE-2024] Updating sponsor list

### PR DESCRIPTION
**Pull request by mpinedag12**
[MDE-2024] Updating sponsor list

### CODE REVIEW

**Comment by adrianmoisey** [comment]
This PR is adding both gaccp.yml and gaccpp.yml, but only using one of them.
Can you remove the unused one?

**Comment by mpinedag12** [comment]
Hi, I deleted the unused .yml! Thanks

**Comment by adrianmoisey** [comment]
Don't forget the image too: static/img/sponsors/gaccp.png

**Comment by mpinedag12** [comment]
I'm trying to do here because I dont have my computer untill next week, but I dont have that option (appears disabled) like with the yml. It is possible you can help me deleting this file for me?. Sorry and thank you.

**Pull request closed without merging**
