### PR TITLE
Fix incorrect code blocks

### PR DESCRIPTION
**Pull request by adrianmoisey**
I assume this is related to the hugo upgrade

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Oh dear. I've searched the code base for more instances of this. Looks like there's more cleaning up to do.
Please hold off on review until I can add them.

**Comment by adrianmoisey** [comment]
Please review with care, as I made these changes manually, and I'm sure I may have made mistakes.

**Comment by mattstratton** [comment]
It's very strange that it's happening on stuff in `static` as those files are just html that isn't processed by Hugo. It's possible they've been messed up for a long time :)

**Comment by mattstratton** [comment]
Out of curiosity, @adrianmoisey , for the files you modified in `static`, are you seeing them rendered incorrectly, or just saw it in the files themselves?

**Comment by adrianmoisey** [comment]
> It's very strange that it's happening on stuff in `static` as those files are just html that isn't processed by Hugo. It's possible they've been messed up for a long time :)

I assume that the 2018 issues weer introduced here: https://github.com/devopsdays/devopsdays-web/pull/8983

As for the non 2018 ones, I'm unsure.

**Comment by adrianmoisey** [comment]
> Out of curiosity, @adrianmoisey , for the files you modified in `static`, are you seeing them rendered incorrectly, or just saw it in the files themselves?

I checked the rendering, and changed accordingly.

**Comment by mattstratton** [comment]
The stuff in `static` very well may have been broken for a LONG time; the hugo change was only a couple days ago, so the html output has been using the old stuff. But it's good to fix it!

**Pull request merged**
