### PR TITLE
[ZRH2023] Set DevOpsDays Zurich 2023 to sold out

### PR DESCRIPTION
**Pull request by romanoroth**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by mattstratton** [comment]
@romanoroth do you want to maybe update the data file to show registration is not available, etc?

**Comment by mattstratton** [comment]
I can't do it for you, but these are the changes to make in your data file:

```
registration_closed: "true" #set this to true if you need to manually close registration before your registration end date
```

and also change to this:

```
#  - name: registration
```

you might also want to add something on the `registration.md` page to reflect it is sold out and remove the link from it (just in case people come across the page)

**Comment by romanoroth** [comment]
I'm on it

**Comment by romanoroth** [comment]
Added the changes.

**Pull request merged**
