### PR TITLE
[TPE-2022] add 2022 Taipei event

### PR DESCRIPTION
**Pull request by thebrecht**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by thebrecht** [comment]
Dear maintainer, does this PR have any problem? If it has any issue,  we will fix it soon.

**Comment by MikeRosTX** [comment]
> Dear maintainer, does this PR have any problem? If it has any issue, we will fix it soon.

Sorry for the delay in merging your event. We noticed there is a difference from last year to this year, the organizer John Yu was removed from last year and this new Tony Chang was added this year.

Please send the core team an email stating these changes with Tony's email so we can add him to the team email dl and slack.

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Please send an email to the core team that list all organizer's **full name** & **email** so we can confirm the team email dl is correct.

**Comment by MikeRosTX** [comment]
Hi @thebrecht 

Did you send an email to info@devopsdays.org with a list of all your team's full name and email 🤔❓
If not, please send at your earliest convenience so we can merge the PR.

**Comment by thebrecht** [comment]
Hi @MikeRosTX 

just send our updated member list to info@devopsdays.org, please correct the info, thanks.

**Review by MikeRosTX — APPROVED** [review]

**Pull request merged**
