### PR TITLE
[EHV-2022] initial program efforts

### PR DESCRIPTION
**Pull request by PaulusTM**
This pr is so @FloorD and me get builds of our program building efforts to test. 
Please wait with the merge.

### CODE REVIEW

**Comment by FloorD** [comment]
On it!

**Review by FloorD — APPROVED** [review]
Need someone else to build and test it, but otherwise I think we're getting there in terms of tentative program.

**Comment by PaulusTM** [comment]
LGTM :shipit:

**Comment by FloorD** [comment]
An excellent start if I do say so myself 😜

**Pull request merged**
