### PR TITLE
[Montreal-2022] "Dynamic" program added

### PR DESCRIPTION
**Pull request by sebagomez**
We want to have a fast way to update the schedule in case we have some last-minute changes.
We'll roll back to the static schedule after the event is over.

(and sorry, some meaningless commits trying to fix local stuff)

### CODE REVIEW

**Comment by adrianmoisey** [comment]
@sebagomez Do you also need to comment out the static schedule for the 26th October?

This is what I see in the preview, and it seems confusing:
image

Let me know what you want, happy to merge if you want it this way.

**Comment by sebagomez** [comment]
That's weird, I meant to comment out the static part. Thanks for the heads up, I'll fix it

**Comment by sebagomez** [comment]
hey @adrianmoisey I had commented Thrursday out but not Wednesday. Here's the updated version. Thanks

**Comment by adrianmoisey** [comment]
LGTM!

**Pull request merged**
