### PR TITLE
2018-fortaleza - Program Adjust

### PR DESCRIPTION
**Pull request by gb8may**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by gb8may** [comment]
Everything looks ok... With start and end time... What´s going on?


*Mayara Gouveia*

Jr DevOps Engineer

Information Security Specialist

https://mayara.gouveia.info/

Linux User #566363 | LPI ID: LPI000348552 | Puppet ID: PPT0005371






Em sex, 28 de set de 2018 às 10:45, Matt Stratton <notifications@github.com>
escreveu:

**Comment by mattstratton** [comment]
I don’t know. I was looking quickly at the failed build. I’m on mobile. Does this change build for you locally?

**Comment by mattstratton** [comment]
This is the error:

`yaml: line 203: did not find expected key`

**Comment by gb8may** [comment]
I made some corrections now... i think now it’s working fine!

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
DevOps Professional | CompTIA Network+ Ethical Hacking Foundation | Fortinet NSE1
DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 Puppet ID: PPT0005371

**Comment by gb8may** [comment]
Thank you Matt, sorry about the errors!

*Mayara Gouveia*

Jr DevOps Engineer

Information Security Specialist

https://mayara.gouveia.info/

Linux User #566363 | LPI ID: LPI000348552 | Puppet ID: PPT0005371






Em sex, 28 de set de 2018 às 11:33, Matt Stratton <notifications@github.com>
escreveu:

**Pull request merged**
