### PR TITLE
[AMS-2019] Add noti.st link for Daniel Maher

### PR DESCRIPTION
**Pull request by phrawzty**
Add noti.st link for Daniel Maher's workshop (see #8072)

cc @mattstratton for verification on proper usage

### CODE REVIEW

**Comment by mattstratton** [comment]
Aren't you a fancy lad?

Now I need to go back and do all of mine. Thanks for that.

**Comment by phrawzty** [comment]
> Now I need to go back and do all of mine. Thanks for that.

Hah! _Probably_ more trouble than it's worth.

probably.

**Comment by mattstratton** [comment]
Looks good. AMS 2019 doesn't have icons enabled on the program page, so it won't show up there, but the embed on the talk page is good. I'll merge this.

**Comment by mattstratton** [comment]
Except you already did.

**Pull request merged**
