### PR TITLE
[PDX-2017] Updated the schedule with Day 3: ConfigManagementCamp and ContainerDays

### PR DESCRIPTION
**Pull request by KrisBuytaert**
Update of the PDX schedule , added Day 3 for  Config Management Camp and Container Days in order to have all in one view.

I included all abstracts and bios I could find.

### CODE REVIEW

**Comment by mattstratton** [comment]
@KrisBuytaert Did you want to enable the "Speakers" menu item? It doesn't seem to be  enabled.

**Comment by KrisBuytaert** [comment]
Lemme check with @BillWeiss  etc .. there must be a reason why it ain't enabled for PDX right now ..

**Comment by BillWeiss** [comment]
Totally accidental if that's the case.

Also, 👍  to this change, looks great.

**Comment by mattstratton** [comment]
I just edited the commit/PR to enable it...let's take a look when the deploy preview builds since I yolo edited via the webui based on memory of the fields :)

**Pull request merged**
