### PR TITLE
[WIP] [OSL-2019] Updated program

### PR DESCRIPTION
**Pull request by larstobi**
do not merge

### CODE REVIEW

**Comment by serhatcan** [comment]
So, we shouldn't merge yet?

**Comment by bridgetkromhout** [comment]
Hi, @larstobi - we encourage people to submit PRs when they're ready for them to be merged. Please let us know if we can merge this; if we hear nothing today, we'll close it unmerged. Thanks.

**Comment by bridgetkromhout** [comment]
Hi, please open when you’re ready for us to merge - thanks!

**Comment by larstobi** [comment]
@bridgetkromhout I'm sorry, I wasn't aware of this norm, and I've been seing lots of do-not-merge PRs here lately, so I was under the impression that it was fine. Since it's not possible to see the result of a change unless I make a PR i.e. the netlify preveiw link, then it's difficult to know if it's good.

However, I thank you for your comments and will try to adhere as much as I can.

I am unable to re-open this PR, so I'll submit a new identical one now.

**Pull request closed without merging**
