### PR TITLE
[2017-zuerich] the beginning

### PR DESCRIPTION
**Pull request by locolupo**
The landingpage for the swiss DevOpsDays event next year.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks. I'm checking a few details for this new event before we merge.

**Comment by locolupo** [comment]
@bridgetkromhout great thx

**Comment by bridgetkromhout** [comment]
Okay, I checked and the email lists weren't set up to work with the `zuerich` spelling. I've added that as an alias so it will work.

**Comment by bridgetkromhout** [comment]
@gethash had the kickoff call with these folks and their email lists and Slack access are all set up, and I've included the Twitter account in the main-page list too.

Flagging @mattstratton who is cleaning up some issues around how we handle accented characters in city names. He can remove the `do-not-merge` and merge this when that's good to go.

**Comment by mattstratton** [comment]
I am going to merge this, and then I will clean up the fixes needed for the names and submit a new PR.

**Comment by locolupo** [comment]
awesome thx @bridgetkromhout and @mattstratton

**Pull request merged**
