### PR TITLE
[Paris-2017] adjust style to avoid auto-caps

### PR DESCRIPTION
**Pull request by phrawzty**
The default style for `##` auto-capitalises each word, which looks horrendous in French. 😉  This makes it hurt less.

`r?` @jooooooon

### CODE REVIEW

**Comment by mattstratton** [comment]
Just for my reference, can you give me an example page?

**Comment by mattstratton** [comment]
Oh I see it now.

I'm not sold that is a good styling choice myself - I think we will fix it a different way. Feel free to use this one, but I'm thinking that we can adjust this.

**Comment by phrawzty** [comment]
> Just for my reference, can you give me an example page?

Literally any page that uses headers of any type. :)

**Comment by phrawzty** [comment]
p.s. 2017-seattle saw this problem and fixed it this way already. 😉

**Comment by mattstratton** [comment]
yeah, that's bootstrap. Easy enough to override. I'll file a bug and fix that; I don't think I did that intentionally.

**Comment by mattstratton** [comment]
Oh, I did do it on purpose for some reason. I'll put in a bug to fix that and override it where I need them to be capitalized (there are places that it makes sense at a higher level I think?)

**Comment by jooooooon** [comment]
👍  Thanks @phrawzty

**Pull request merged**
