### PR TITLE
[RDU-2019] switched out chris mertz for James Maltba and Jonell Taylor pic

### PR DESCRIPTION
**Pull request by normalfaults**
[RDU-2019] switched out chris mertz for James Maltba and Jonell Taylor pic

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please resize the Speaker's picture images to comply with the guidelines.
https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields

The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. It can be either .png or .jpg. **_It must be square, and 300px square, 600px square, or 900px square._**

**Comment by normalfaults** [comment]
@MikeRosTX updated the pics

**Comment by normalfaults** [comment]
@MikeRosTX i need to update the yml. i'll update the pull request in less then 5 minutes. stand by :)

**Comment by normalfaults** [comment]
@MikeRosTX this pull request is ready for your review. thank you!

**Pull request merged**
