### PR TITLE
[SLC2016] Updates to SLC, fix future.html to sort by startdate

### PR DESCRIPTION
**Pull request by davidasnider**
Completed most of the changes to SLC, just need team to review.  Also added small snippet to make future.html sort in order of event start date.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks, David! While your team is reviewing, can you move the fix for future.html into a different branch and a different PR? It would be a lot easier to review and merge them independently then.

**Comment by davidasnider** [comment]
Well, I was gonna have them review on devopsdays.github.io.  Wouldn't you need to merge it for them to see that?

**Comment by davidasnider** [comment]
What ever changes they want I just plan to update and do another PR

**Comment by bridgetkromhout** [comment]
I mean that @mattstratton would be reviewing and deciding about https://github.com/davidasnider/devopsdays-web/blob/2016-slc-updates/themes/devopsdays-legacy/layouts/partials/future.html#L15 and that's a different question entirely than "is the rest of the team happy with stuff". So if that was in its own PR then he could merge that or not merge it, and it wouldn't prevent us from merging the rest of your stuff for your team to look at.

**Comment by davidasnider** [comment]
So, forgive my ignorance, I'm not sure how to do what you're asking me to do without simply starting over on all the changes.  If it's ok, I'm happy to wait until Matt takes a look at the future.html.

**Comment by mattstratton** [comment]
It's going to be tricky because #151 is a major change to future.html, so merging this in will cause a conflict. 

I'll merge in #151 and then you can re-pull into your branch. I think #151 might actually account for the sorting as well.

**Comment by bridgetkromhout** [comment]
@davidasnider - without doing anything fancy, here's what I recommend. Open your future.html in your clone of the repo locally in your 2016-slc-updates branch, delete everything in it, and replace it with the contents of this page: 


https://raw.githubusercontent.com/devopsdays/devopsdays-web/master/themes/devopsdays-legacy/layouts/partials/future.html

Then commit and push that to your fork of the repo on that branch.

If I'm not wrong, that should remove the merge conflict in this PR without you having to do anything difficult with git. :)

**Comment by davidasnider** [comment]
OK, after spending time with google, I pulled devopsdays/devopsdays-web master into my fork, resolved the conflict on future.html, and you were right, it also fixed the sorting.  I then pushed to my repo, so are we good?  Or do I need to do anything else fancy?  Sorry, the only time I've ever used Git is for this project so, still learning.

**Comment by mattstratton** [comment]
I think this is fine, but I would want @jyee to take a look at it after the PR is merged. Which I'm doing now :)

**Comment by davidasnider** [comment]
Thanks folks!  If I see anything outside of SLC's stuff that I want to change, I'll make sure to do that in a separate branch from now on.  Thanks for the learning experience.

**Pull request merged**
