### PR TITLE
[Cape Town 2018] Add CFP

### PR DESCRIPTION
**Pull request by adrianmoisey**

### CODE REVIEW

**Comment by manicminer** [comment]
LGTM!

**Comment by phrawzty** [comment]
Hooray for the CFP! Might I also suggest that you add the CFP start/end/announce dates, as well as set the URL formally?
https://github.com/devopsdays/devopsdays-web/blob/6b0e56cfc2292817d36fd03202b1cf5f4a93312e/data/events/2019-cape-town.yml#L13-L18

**Comment by adrianmoisey** [comment]
> Might I also suggest that you add the CFP start/end/announce dates, as well as set the URL formally?

Sorry! I rushed this change. Will fix now.

**Comment by phrawzty** [comment]
🎊

**Pull request merged**
