### PR TITLE
[DEN-2022] Add recent sponsors

### PR DESCRIPTION
**Pull request by mattk42**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by tavisto** [comment]
Looks good to me.

**Comment by phrawzty** [comment]
Regarding `static/img/sponsors/fairwinds.png`, do you have a version of this with a transparent background? It's not a blocker per-se but it is preferred.

**Comment by mattk42** [comment]
@phrawzty We will reach out to the vendor to see if I can get a transparent one. Would it be possible to merge this for now and I can update if we are able to get one?

**Comment by phrawzty** [comment]
@mattk42 That's fair. :)

**Pull request merged**
