### PR TITLE
[CWB-2024] Update event date and organizers

### PR DESCRIPTION
**Pull request by pedroalvesbatista**
Added new organizers and removed ones who's not anymore in core organization. Also updated event date and Call for Papers form link.

### CODE REVIEW

**Comment by mattstratton** [comment]
Please don’t mix changes to the build and other items along with content for your event. If you’d like to propose changes to devcontainer files etc please do this in a separate PR

also wow this changed a lot of files

**Review by mattstratton — CHANGES_REQUESTED** [review]
This PR includes many files with conflicts (see all the files with HEAD lines) and there are over 100 changed files, most of which have nothing to do with the started point of this change. Please clean this up and re submit.

**Comment by pedroalvesbatista** [comment]
> Please don’t mix changes to the build and other items along with content for your event. If you’d like to propose changes to devcontainer files etc please do this in a separate PR
> 
> also wow this changed a lot of files

Hey, thanks for checking. I just changed an error in `_redirects` that might seem to be something related to the general repo.

**Comment by mattstratton** [comment]
I don’t think this PR is salvageable in this state. I would suggest you rebase and try again.

**Pull request closed without merging**
