### PR TITLE
[KIEL-2018] created devopsdays Kiel 2018 event

### PR DESCRIPTION
**Pull request by connor21**
Hi,
finally we got the location for a new DevOpsDays event in Kiel. Please add the date to the devopdays page.
Thank you.
Cheers,
Maik

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Review why it's failing. @connor21 please try loading it in Hugo locally to see if it displays fine for you.  Did you rebase?  What version of Hugo are you using.  See error below:

298ERROR 2017/03/23 13:31:14 Error while rendering "page events/2018-kiel/speakers.md": template: /home/travis/gopath/src/github.com/devopsdays/devopsdays-web/themes/devopsdays-theme/layouts/_default/baseof.html:63:25: executing "main" at <index .Site.Data.spe...>: error calling index: index of nil pointer

**Comment by mattstratton** [comment]
I'll take a look in a few minutes and try to pull this down and see if I can figure it out.

**Comment by mattstratton** [comment]
It's an issue in the theme - I have a fix and will be releasing it shortly.

**Comment by mattstratton** [comment]
This should actually pass now; although I don't know how to re-kick the tests.

**Comment by MikeRosTX** [comment]
@mattstratton I'm trying to kick it off again...

**Comment by mattstratton** [comment]
It's passing travis so I am okay with merging this.

**Pull request merged**
