### PR TITLE
[NYC-2019] Adding James as organizer 

### PR DESCRIPTION
**Pull request by russAIC**
Adding James as an organizer to our event.

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Everytime an organizer is added to website, send an email to info@devopsdays.org with the new organizer's full name and email so they can be add to Slack and team's email.

**Comment by russAIC** [comment]
Sent email with title "Please Add James to NYC 2019 DOD Organizers list" to the address.

**Comment by kmugrage** [comment]
FYI, we have the request. There's a bit of a perfect storm with core organizers traveling and other stuff to get the request done. Thanks for your patience!

**Comment by phrawzty** [comment]
👋 I have sent the Slack invite and added the address to the ML as requested.

**Pull request merged**
