### PR TITLE
[TLV-2017] Speakers and logo

### PR DESCRIPTION
**Pull request by gilzellner**
[TLV-2017] Speakers and logo

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi @gilzellner - I updated Ashley's bio because she changed jobs. Let me know if that's 👍 when you look at the preview and we'll merge if desired.

**Comment by bridgetkromhout** [comment]
Also, the logo says 2016. You might want to fix that.

**Comment by gilzellner** [comment]
Hi!
You are more updated than I am!
thanks for fixing it 👍

**Comment by bridgetkromhout** [comment]
Okay. Do you want to go "live" with the 2016 date (without pasting a 2017 over it in the image)?

**Comment by gilzellner** [comment]
Hi,
yes, I'll fix it later.
Thanks!

**Comment by bridgetkromhout** [comment]
Okay, but you do need to make the image a square. Otherwise this happens:

screen shot 2017-08-30 at 7 35 26 am

See guidelines: https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#event-square-logo

**Comment by bridgetkromhout** [comment]
Just paste the image you already have onto a white square, like Seattle did here: https://github.com/devopsdays/devopsdays-web/blob/master/static/events/2018-seattle/logo-square.jpg

**Comment by bridgetkromhout** [comment]
And if you want that done but can't do it yourself, let me know and I'll do it.

**Comment by gilzellner** [comment]
Hi,
yes please. 
I've been trying for the last few minutes but it just keeps coming out really ugly.
I need to improve my gfx skills

**Comment by bridgetkromhout** [comment]
Ah, I see that I am wrong and a build step means the site is not quite wysiwyg. So I'll merge it and it will fix it in the build (I think).

**Pull request merged**
