### PR TITLE
[CPS-2024] Add organizer

### PR DESCRIPTION
**Pull request by theer1k**
This PR adds the following details for the upcoming DevOpsDays Campinas event:

## Organizers:
 - Douglas Esteves (new)

### CODE REVIEW

**Review by toshywoshy — CHANGES_REQUESTED** [review]
Need to send a mail to info and get their approval before adding a new organizer

**Comment by theer1k** [comment]
> Need to send a mail to info and get their approval before adding a new organizer

Email sent.

**Comment by nimbinatus** [comment]
Mail received; core work complete. Safe to merge!

**Review by nimbinatus — APPROVED** [review]
LGTM

**Pull request merged**
