### PR TITLE
[CHI-2025] add registration link (thanks Corey!)

### PR DESCRIPTION
**Pull request by dexhorthy**
Add the registration link for Chicago 2025 - @mattstratton let me know if I missed anything here!

### CODE REVIEW

**Comment by mattstratton** [comment]
There are two sections in content/events/2025-chicago/welcome.md which can be uncommented and updated to enable some additional buttons for sponsorship and registration on the main page !

**Comment by adrianmoisey** [comment]
@dexhorthy Are you good here?

**Comment by mattstratton** [comment]
This can merge without my suggested updates - I can do another PR later to add them.

**Comment by mattstratton** [comment]
IMG_2582

think the ticket options are off; self-funded is not discounted (and shouldn’t show up during early bird)

@dexhorthy

**Pull request merged**
