### PR TITLE
[BHE-2018] - Launching and first version

### PR DESCRIPTION
**Pull request by devopsdaysbh**
Changelog:
- Launching the first version of the Belo Horizonte/Brazil's page. Horray!

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Another thing, you need to convert **_zandler-oliveira.png_** to **_jpg_**.

https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md
The name of the image for this user, located in static/events/YYYY-CITY/organizers/. **_This image must be a JPEG_**, either 300px square or (optimally) 600px square.

**Comment by devopsdaysbh** [comment]
Hey @MikeRosTX , hello! I'll take a look at those items shortly. Thanks for the heads up!

**Comment by devopsdaysbh** [comment]
Hello gentlemans/ladies,

The fix has been submited as requested. Awaiting for a new review

**Comment by MikeRosTX** [comment]
Another thing, we need someone from your team to email info@devopsdays.org with a list of all the organizers for BH that includes their full name and email. Once that is done, we will create a team email and send out Slack invitation,

**Comment by MikeRosTX** [comment]
Waiting for organizer's emails before merging this PR.

**Comment by devopsdaysbh** [comment]
Hey Mike,

Yeay, we're already arranging this. Thanks for the attention.

Diego

**Comment by devopsdaysbh** [comment]
Sorry for the long delay, the e-mail has been sent now.

**Pull request merged**
