### PR TITLE
[KC-2017] Links to slides and videos for the program

### PR DESCRIPTION
**Pull request by aaronblythe**
Links to slides and videos for the program.

### CODE REVIEW

**Comment by devopsdays-service** [comment]
@aaronblythe, thanks! Based upon the content in this PR, we need a review from @mattstratton, @MikeRosTX, @phrawzty and @bridgetkromhout

**Comment by aaronblythe** [comment]
Example with video/slides filled out (note the links to video/slides):
https://deploy-preview-3413--devopsdays-web.netlify.com/events/2017-kansascity/program/

Example with video/slides not filled out (to show passive):
https://deploy-preview-3413--devopsdays-web.netlify.com/events/2017-chicago/program/

**Comment by mattstratton** [comment]
This PR has changes to the theme. Those changes need to be made in devopsdays/devopsdays-theme, and then once they are released the updated content can be pushed.

**Comment by aaronblythe** [comment]
@mattstratton can you comment on: https://github.com/devopsdays/devopsdays-theme/issues/600

**Comment by aaronblythe** [comment]
Theme change pull request: https://github.com/devopsdays/devopsdays-theme/pull/602

**Comment by bridgetkromhout** [comment]
Heya, @aaronblythe - looks like you probably want to revert the changes to `data/events/2017-kansascity.yml` because, based on the discussion in https://github.com/devopsdays/devopsdays-theme/issues/600, the duplicate info you're adding there won't be needed. If that's corrected I think this is mergeable.

**Comment by aaronblythe** [comment]
I have reverted the changes to data/events/2017-kansascity.yml

**Pull request merged**
