### PR TITLE
[2016-oslo] Added program to Oslo 2016

### PR DESCRIPTION
**Pull request by antonbabenko**

### CODE REVIEW

**Comment by antonbabenko** [comment]
@yvovandoorn - this can be merged now.

**Comment by yvovandoorn** [comment]
Hey @antonbabenko 

A few pointers:
* You have a few broken links to non-existing photos yet for some of your speakers (this is a known issue -- #365)
* You should consider adopting a [500x500](https://github.com/devopsdays/devopsdays-web#speaker-images) for your speaker images
* For all your talks I see you're going with

`<div class="span-15  ">`
`<div class="span-15  last ">`
...content...
`</div>`
`</div>`

You should consider migrating to (making @mattstratton proud-ish):

`<div class="col-12">`
...content...
`</div>`

Example: [Jody's talk on dod AMS' site](https://raw.githubusercontent.com/devopsdays/devopsdays-web/master/content/events/2016-amsterdam/program/jody-wolfborn.md)

**Comment by mattstratton** [comment]
@yvo - we should fix the talk template so that the `<div>` isn't required in the `.md` file. That's outside of scope of this PR, but your comments made me think of it.

**Comment by beddari** [comment]
Hm, ah, late to the party, we'll address these ...

**Comment by antonbabenko** [comment]
@yvovandoorn - Done:
- [x] Fixed html for all talks
- [x] Fixed broken links to images by uploading blank photos

We may ask 500x500 photos from speakers, but I don't think we should wait with this to be merged.

**Comment by yvovandoorn** [comment]
logo on page

Hey @antonbabenko -- If this is your intended look (block of text before logo) just let me know and I'll merge (To me -- it looks a bit weird 😄).

**Comment by beddari** [comment]
@yvovandoorn You're right, let's revert that one :)

**Comment by beddari** [comment]
Hmm, still no pic of Marta, I think it is even already in the repo @antonbabenko ?

**Comment by antonbabenko** [comment]
I could not find her photo, but I will email her.

@yvovandoorn - this can be merged now. :)

**Pull request merged**
