### PR TITLE
[BER-2018] Add Nubank Germany as a sponsor

### PR DESCRIPTION
**Pull request by range**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@range where's the logo for Nubank?

**Comment by range** [comment]
This commit should fix it.

**Comment by MikeRosTX** [comment]
@range, that commit didn't fix it. Check out the preview link: https://deploy-preview-4829--devopsdays-web.netlify.com/events/2018-berlin/welcome/

**Comment by range** [comment]
@MikeRosTX Okay. I wasn't aware that the logo name is derived from the name of the yaml file. Can't run hugo here at the moment, otherwise I probably would have caught that. Sorry for the extra work created.

**Pull request merged**
