### PR TITLE
[CHI-2018] Updated Beijing and added Shanghai&Shenzhen

### PR DESCRIPTION
**Pull request by martinliu**
- Updated Beijing Event with new date and DevOpsDays Wechat QC
- Added Shanghai with proposed date and location
- Added Shenzhen with proposed date and location 

We are working on a series press release and online promotion based on devopsdays.org site.
We hope this PR will be merged soon.

Thanks for your support!

Martin Liu / Sun Zhengpeng

### CODE REVIEW

**Comment by martinliu** [comment]
@bridgetkromhout Hi there, would you pls help to take a look? Preview does not have correct time, it is not same as my updated in 2nd commit. Thanks! Martin Liu

**Comment by bridgetkromhout** [comment]
Hi, @martinliu - I made a few corrections and made it so that your China devopsdays site would display with an icon - you can choose a different [font-awesome icon](http://fontawesome.io/icons/) if you prefer.

**Comment by martinliu** [comment]
Hi, @bridgetkromhout I am appreciate  your work and I saw our events pages are correct in preview site, but not on devopsdays.org site. It seems production site is still not updated by our comments. How long will it take to sync our updates to production? Any CDN or cache cause this different? Thanks for your help! Martin

**Comment by martinliu** [comment]
It synced now, Thanks @bridgetkromhout !

**Comment by bridgetkromhout** [comment]
Hi, Martin - it does usually take a few minutes to build, yes. Usually 15min after merging it will be correct (but sometimes there are a lot of updates).

**Pull request merged**
