### PR TITLE
[ATX-2020] Adding alert to POSTPONE

### PR DESCRIPTION
**Pull request by scottsbaldwin**

### CODE REVIEW

**Comment by mattstratton** [comment]
You might want to delete all the dates from those fields as well?

**Comment by scottsbaldwin** [comment]
@mattstratton, I'm going to remove the dates once we have a clearer picture for reschedule vs cancellation.

**Comment by mattstratton** [comment]
Makes sense. We are working on coming up with some consistent guidance on what to do with the website for all this, so it's all in flux of course :)

**Comment by mattstratton** [comment]
The main reason I suggest removing dates is that this affects how the homepage looks - and right now with the dates intact it shows up as coming up very soon. Removing the dates would push the event into the "TBD" part of the sidebar instead of showing up under April.

I appreciate we are all just trying to figure out the best way to handle all of this!

**Comment by scottsbaldwin** [comment]
We definitely know we aren't holding the event on those dates. We do have a committee working on a potential reschedule dates. Our hope was to just update the dates one time.

**Comment by scottsbaldwin** [comment]
@mattstratton I have just removed the dates.

**Pull request merged**
