### PR TITLE
[texas-2022] Initial start of DoDTexas!

### PR DESCRIPTION
**Pull request by jjasghar**
Starting the framework/organization for 2022 DoD Texas

### CODE REVIEW

**Comment by mattstratton** [comment]
Hey @jjasghar .... the state-wide version of devopsdays was a one time thing as we understood it, because it was virtual. is this the plan for 2022 again?

**Comment by jjasghar** [comment]
yep, the plan is another state wide virtual one with representation from all the major cities (and not so major) again.

**Comment by mattstratton** [comment]
Cool!

**Comment by yvovandoorn** [comment]
Adding a `do-not-merge` tag until @jjasghar gives us a heads up that this is ready for review :-)

**Pull request closed without merging**
