### PR TITLE
[SLC2018] Announce

### PR DESCRIPTION
**Pull request by davidasnider**
Getting the team geared up for another great year!  SLC 2018- WOOOHOOO!!

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hey - please email us at info@devopsdays.org confirming the names and email addresses (don't wanna assume emails haven't changed) for the organizers, so we can set up the 2018 aliases. Thanks.

**Comment by davidasnider** [comment]
I’ll update the PR with the official members.  Also will send an email to this list, we did make some changes.

**Comment by davidasnider** [comment]
email sent, updated organizers

**Comment by bridgetkromhout** [comment]
Hi, David! Do you have a signed contract with the venue for those dates?

**Comment by davidasnider** [comment]
Sure do.

**Pull request merged**
