### PR TITLE
Add Curitiba edition

### PR DESCRIPTION
**Pull request by pedroalvesbatista**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi @pedroalvesbatista. There are a couple of things missing from this PR, and we're already trying to chat with you through email about some of our requirements. Let's discuss before we continue with this PR.

**Comment by pedroalvesbatista** [comment]
> Hi @pedroalvesbatista. There are a couple of things missing from this PR, and we're already trying to chat with you through email about some of our requirements. Let's discuss before we continue with this PR.

Hi, thanks for replying back, sure, let's discuss further details please.

**Comment by phrawzty** [comment]
Hi everybody,

This PR was incomplete when it was proposed, and with the recent code change to how the site is built, it's also now out of date. Consequently, I am going to close it. When Curitiba is ready to propose a new event stub (hint: https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#events), please open a new PR.

Cheers

**Comment by pedroalvesbatista** [comment]
Thanks @phrawzty for the review and reply, we'll take a closer look into the changes and make the proper changes for a new PR.

**Pull request closed without merging**
