### PR TITLE
[TLV-2019] Adding event to website

### PR DESCRIPTION
**Pull request by shar1z**
I have run the necessary scripts (the relevant ones for now) and got Hugo up and running.  Please let me know if I missed anything to be able to put the page up.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @shar1z! I'll work with you to get this merged. For starters, you included a number of organizer pictures for organizers you didn't list- please remove those from the PR, or list those organizers in the YAML file. (I'm going to set up the email list and Slack membership based on the organizers in your YAML.) You also have a speaker image for a speaker not (yet) listed.

**Comment by shar1z** [comment]
Thanks. I kept them as placeholders as I'm still finalizing this year's team. I'll add them later if it's relevant.

Will send you the list to email shortly.

**Comment by bridgetkromhout** [comment]
>  I kept them as placeholders as I'm still finalizing this year's team. I'll add them later if it's relevant.

We try to be unambiguous about who's on a local team, so we don't want to merge a PR with contradictory info.

> Will send you the list to email shortly.

Thanks. We need the correct list of email addresses that matches the local team listed in the PR before we merge.

**Comment by shar1z** [comment]
> > I kept them as placeholders as I'm still finalizing this year's team. I'll add them later if it's relevant.

I deleted the extra pictures & updated the missing ones.

> We try to be unambiguous about who's on a local team, so we don't want to merge a PR with contradictory info.
> 
> > Will send you the list to email shortly.
> 
> Thanks. We need the correct list of email addresses that matches the local team listed in the PR before we merge.

I have sent the email with the current organizer list. 
Hope we're good to go now.

**Comment by bridgetkromhout** [comment]
Cool, taking a look. Your logo file is very large; as per https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#event-square-logo we recommend 600px by 600px.

Also, `static/events/2019-tel-aviv/speakers/nicole_forsgren.jpg` shouldn't be there until you're listing speakers.

**Comment by shar1z** [comment]
> Cool, taking a look. Your logo file is very large; as per https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#event-square-logo we recommend 600px by 600px.

Will fix now
> Also, `static/events/2019-tel-aviv/speakers/nicole_forsgren.jpg` shouldn't be there until you're listing speakers.

Ok - but she is a confirmed speaker - so I'm just keeping her there until we announce.

**Pull request merged**
