### PR TITLE
[DC 2017] add InfluxData as gold sponsor

### PR DESCRIPTION
**Pull request by markcornick**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@markcornick I think you forgot to upload their new attached logo from his email.  ;-)

**Comment by markcornick** [comment]
I got Admonished™ over changes to existing sponsor logos last year, but I’ll go ahead and add the new one.

**Comment by MikeRosTX** [comment]
Understood @markcornick, but the CMO is requesting all cities they're sponsoring change their logo to the new one. Since they're paying ;-) we should respect their request.

**Comment by bridgetkromhout** [comment]
> I got Admonished™ over changes to existing sponsor logos last year, but I’ll go ahead and add the new one.

lol, probably by me - fwiw the thing we're trying to prevent is ret-conning the past. Since this change is all for future events, it's fine that we're changing it on all upcoming events without going through the namespacing/archiving exercise we'd otherwise need to do.

**Pull request merged**
