### PR TITLE
Add google forms, styles

### PR DESCRIPTION
**Pull request by VitMosin**
Add google forms, styles

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Asking @mattstratton to take a quick glance to see if he can figure out why deploy/netlify is failing.

**Comment by mattstratton** [comment]
This is the error; I'll have to look to see what is bad about it:

```
ERROR: 2016/11/29 16:14:26 general.go:212: Error while rendering page events/2017-moscow/program/vitaly-mosin.md: template: theme/talk/single.html:23:24: executing "theme/talk/single.html" at <index .Site.Data.spe...>: error calling index: index of nil pointer
```

**Comment by mattstratton** [comment]
The problem is that this file `data/speakers/2017/moscow/vitaly-mosin.yml` is empty; it needs frontmatter.

**Comment by VitMosin** [comment]
This file was deleted in the commit at all. Where is it empty?

**Comment by mattstratton** [comment]
Sorry, I meant you need to delete the file events/20-7-moscow/program/
vitaly-mosin.md

**Comment by VitMosin** [comment]
Well, i see. I'll delete in in new commit

**Comment by VitMosin** [comment]
It's done

**Comment by mattstratton** [comment]
Probably need to remove the `speakers.md` file as well since it has no data yet:

```
Error while rendering page events/2017-moscow/speakers.md: template: theme/speakers/single.html:18:25: executing "theme/speakers/single.html" at <index .Site.Data.spe...>: error calling index: index of nil pointer
```

**Comment by VitMosin** [comment]
I've just corrected the page (no delete). Now it passed well.

**Pull request merged**
