### PR TITLE
[JKT-2020] Add Sponsors, Update Contact and Update Link

### PR DESCRIPTION
**Pull request by mademulia**
[JKT-2020] Add Sponsors, Update Contact Page Content and Add Link

### CODE REVIEW

**Comment by mademulia** [comment]
Hi @MikeRosTX, Thank you :). I have sent the organiser's email info to info@devopsdays.org

**Comment by MikeRosTX** [comment]
Slack invites were sent. We're working on team email DL issues.

**Comment by bridgetkromhout** [comment]
Update: I sent an email regarding discrepancies; we require the website, email list, and Slack to be in sync. Thanks.

**Comment by mademulia** [comment]
Hi @bridgetkromhout, I have resent all the infos again. Thank you for checking

**Pull request merged**
