### PR TITLE
[INDY-2019] Extend CFP two weeks

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
the deploy/netlify error seems unrelated

**Comment by ghoneycutt** [comment]
@MikeRosTX would like the announce date change?

**Comment by bridgetkromhout** [comment]
> @MikeRosTX why would the announce date change?

Hi, @ghoneycutt - the announce date as it stands is invalid - it's already in the past. Please pick a different one in the future if you don't want to use the one Mike picked - thanks!

**Comment by bridgetkromhout** [comment]
Perhaps this is a confusion in what the terms mean?
```

cfp_date_start | YYYY-MM-DD | No | The date you will start accepting talk proposals. Can be a blank value. | 2016-01-05
cfp_date_end | YYYY-MM-DD | No | The date you will close your call for proposals. Can be a blank value. If you set the full datetime string with correct TZ, CFP will display as open until local close time. | 2016-01-05T23:59:00-06:00
cfp_date_announce | YYYY-MM-DD | No | The date you will inform proposers of status. Can be a blank value. | 2016-01-05
```

So technically you can leave the announce date blank although we may use it to populate information in https://www.devopsdays.org/speaking/ at some point, so it's better to set it.

**Comment by ghoneycutt** [comment]
Aha! Looks good to me. Thank you!

**Pull request merged**
