### PR TITLE
[ATL-2022] Add custom styles to the program page for ATL

### PR DESCRIPTION
**Pull request by mattstratton**
Fixes the styles on the "key" for the program page, and adds speaker / talk pages.

Speakers still need images/bios, etc, and talks need descriptions.

Please do not merge without approval from ATL team

### CODE REVIEW

**Comment by mattstratton** [comment]
@aclairefication

**Comment by aclairefication** [comment]
🤔  I'm not sure what to expect since this is my first time working with these generated files...
I see in other published events that on the speaker page there is a link back to the talk.
When I'm running this on my local, I just see the text SPEAKER at Atlanta 2022 without the link back to the talk description page. Does it render that way for you?

**Comment by mattstratton** [comment]
You can see it in the deploy preview here 

https://deploy-preview-10975--devopsdays-web.netlify.app/events/2022-atlanta/program

I’ve seen it act funny when run locally sometimes.

**Comment by aclairefication** [comment]
🤔  Not sure why, but one of the speakers martin-rojas isn't showing up on the program page as a link. 
Instead, it's showing linktitle martin-rojas instead of replacing the text with SPEAKER - TITLE

**Comment by mattstratton** [comment]
Make sure you change the type to “talk”

**Comment by mattstratton** [comment]
Ah that was my mistake.

**Comment by aclairefication** [comment]
Oh I see now. Thanks.

**Comment by aclairefication** [comment]
I added the talk abstracts and speaker bios but can't push to this branch.

**Comment by aclairefication** [comment]
Thanks for merging 👍

**Pull request merged**
