### PR TITLE
[ZRH-2019] Add new organizer

### PR DESCRIPTION
**Pull request by Roderick-Jonsson**
Adding David to our organization team and sent the e-mail with all the new members to you for mailing list and slack opening :)

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I removed Julia F and Tobias W from the email list. They were not on Slack. now the email, Slack, and website all match. Please send a new PR adding them back if you'd like them on the list.

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX @bridgetkromhout Thank you for your review. Yes we are missing Julias and Tobias Bio at the moment. Let me check on this.

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX Could you anonymize the e-mails in your answer?

**Comment by MikeRosTX** [comment]
Anonymous request completed.

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX Thank you very much!

**Comment by Roderick-Jonsson** [comment]
@MikeRosTX @bridgetkromhout  Did the organizers get added to slack? We seem to miss them.

**Comment by MikeRosTX** [comment]
Since @bridgetkromhout merged the PR, I thought she added them. Yet what could be happening, is that they were all sent but your organizers haven't accepted or joined. Because I've seen that happen before. Send us of list via email to info@devopsdays.org and I'll follow-up after my call.

**Pull request merged**
