### PR TITLE
[CHI-2025] Adding Nvisia's Updated Logo and Gold Sponsorship

### PR DESCRIPTION
**Pull request by albert-cheung**
Adding Nvisia's Updated Logo and Gold Sponsorship

### CODE REVIEW

**Comment by albert-cheung** [comment]
I need some help here. I used the utilities/change_sponsor_logo.sh, but the preview is still showing the legacy nvisia logo.

**Comment by don-code** [comment]
This looks like a casualty of #14341 - the `change_sponsor_logo` script needs a change to align with that new feature.

I was able to fix it with these two commands:
```bash
cp static/img/sponsors/nvisia.png assets/sponsors/n/nvisia.png 
cp static/img/sponsors/nvisia-before-20240926.png assets/sponsors/n/nvisia-before-20240926.png
```

Screenshot from 2024-09-27 00-36-36

For now, can you make those copies in your branch? I'll get a change in to update the script.

**Comment by mattstratton** [comment]
@don-code fyi #14613 has updates to the script for this I think before you put in a new PR?

**Comment by don-code** [comment]
That indeed would do it. Do you want me to pull the change to `change_sponsor_logo.sh` into its own change and PR that, or just make a mental note to make sure sponsor logo changes include `assets`, and wait until #14613 merges?

**Comment by albert-cheung** [comment]
Making adjustments to my own branch before resubmitting.

**Pull request closed without merging**
