### PR TITLE
[CAI-2018] Updating sponsors data

### PR DESCRIPTION
**Pull request by aameen79**
Updating sponsors data and images

### CODE REVIEW

**Comment by aameen79** [comment]
@phrawzty 
I have uploaded again the image of infoglobe, can you resolve the below conflict manually by overriding?
"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
static/img/sponsors/infoglobe.png"

**Comment by phrawzty** [comment]
Hello @aameen79,

As I mentioned in the [previous PR](https://github.com/devopsdays/devopsdays-web/pull/5228#issuecomment-416226747):

It looks like you deleted `infoglobe.png` in one commit, then moved the (now-deleted) file to a new location in a subsequent commit. You'll need to resolve that before we can move forward.

Here is the raw error message:

> CONFLICT (rename/delete): infoglobe.png deleted in e8da982 and renamed to static/img/sponsors/infoglobe.png in HEAD. Version HEAD of static/img/sponsors/infoglobe.png left in tree.

My _guess_ is that you just need to `git add static/img/sponsors/infoglobe.png` in another commit and then push it.

**Comment by phrawzty** [comment]
I am attempting a resolve in #5230…

**Comment by aameen79** [comment]
Dear Daniel,

Thanks for your prompt support.
Actually I didn't move the file, I just re-uploaded it in the right directory (which originally contained this file) after deleting it from root.

On 27 Aug 2018 16:33, Daniel Maher <notifications@github.com> wrote:

I am attempting a resolve in #5230<https://github.com/devopsdays/devopsdays-web/pull/5230>…

**Pull request closed without merging**
