### PR TITLE
Toronto 2016 - Fix Brocade logo.

### PR DESCRIPTION
**Pull request by WhatsChrisDoing**

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello,

Sponsor logos must be 200px square. Thanks!

**Comment by WhatsChrisDoing** [comment]
Okay. I was going on what was on the old site. There is a really wide range logo sizes in the repo.

**Comment by phrawzty** [comment]
> Okay. I was going on what was on the old site. There is a really wide range logo sizes in the repo.

Yeah there sure is, which is precisely why we're [standardising](https://github.com/devopsdays/devopsdays-web/blame/master/README.md#L65) on 200px square. 😄

**Comment by WhatsChrisDoing** [comment]
Changed.

**Pull request merged**
