### PR TITLE
[LDN-2019] Change SheffieldDevops logo

### PR DESCRIPTION
**Pull request by chriscoffee**
Change to static elements of theme as SheffieldDevops logo has changed

Original PR was https://github.com/devopsdays/devopsdays-web/pull/7238 which was closed due to not being from an organizer and using correct guidelines

Co-authored-by: Oliver Leaver-Smith <oliver@leaversmith.com>
Co-authored-by: Chris Mills <me@christophermills.co.uk

### CODE REVIEW

**Comment by mattstratton** [comment]
If this logo has been used in the past, the old sponsor needs to be renamed and a new sponsor created. We do not allow retroactive changes. 

More details here:

https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md

**Comment by muggahtee** [comment]
Makes sense @mattstratton. @chriscoffee want me to do the work on another PR you can pull in?

**Comment by chriscoffee** [comment]
It's cool @muggahtee, 62b2ef2 should hopefully be correct implementation if the maintainers want to have another peek 👍

Sorry it took me like ~40 minutes, I got dragged into 🔥 🚒

**Comment by chriscoffee** [comment]
Right so after chatting to @MikeRosTX in Slack I didn't read the documentation as throughly as I should have... (we used another term for this 😄) 

I'll get this sorted now but for those who weren't privee and want to learn from my mistake, don't just skim https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#updating-a-sponsor and actually click the links and stuff and read https://github.com/devopsdays/devopsdays-web/pull/503 😆

**Comment by muggahtee** [comment]
Ah so old events need to have the renamed sponsor applied to them?

**Comment by chriscoffee** [comment]
I've rebased to hide my shame

**Comment by muggahtee** [comment]
I can see the change live, thanks so much 🙌

**Pull request merged**
