### PR TITLE
[MSK-2019] add draft of event announce

### PR DESCRIPTION
**Pull request by Frodox**
add draft of DevOpsDays Moscow 2019 event announce

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Marked as **do-not-merge** because we cannot merge a PR that has dates of when the event will occur without a venue location. Either remove the date so it appears under **TBD** or add a location for the venue conference.

**Comment by bridgetkromhout** [comment]
Hi, folks - we also need at least three organizers listed.

**Comment by Frodox** [comment]
@bridgetkromhout 
@MikeRosTX 
Thank you for review.
I have updated PR according to your comments

**Comment by MikeRosTX** [comment]
I last request so we can complete merging this PR.
Please send an email to **info@devopsdays.org** with a list of all the Moscow organizers that includes:

**Full name** - **email**

**Comment by MikeRosTX** [comment]
One last request so we can complete merging this PR.
Please send an email to **info@devopsdays.org** with a list of all the Moscow organizers that includes:

**Full name - email**

**Comment by Frodox** [comment]
@mikerostx Done!

**Comment by MikeRosTX** [comment]
@Frodox - Copy of reply to email:

OK, there seems to be some misunderstandings.

We have no problems adding all those organizer's emails listed below to organizers-moscow-2019@devopsdays.org DL, but they all have to be listed to the PR and Slack simultaneously.

So if that what you all want, then please update the PR with all the names and we will add them to email and Slack.

**Pull request merged**
