### PR TITLE
[SEA-2023] adding speakers and talks. Create the program but not enabling the Nav link

### PR DESCRIPTION
**Pull request by harbinger55**
- Add Fastly as gold sponsor
- Add speakers
- Add talks
- create program (initially left out of the Nav)
- Add registration link (commented out)

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by adrianmoisey** [comment]
This change seems fine! My only worry is the size of some of the speaker photos.
Could you resize some of the big photos? Some are over 3MB in size.

**Comment by harbinger55** [comment]
I will resize them tonight and update the PR.

**Comment by MikeRosTX** [comment]
> I will resize them tonight and update the PR.

@adrianmoisey's concern is related to this guideline;
https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#speaker-page-fields

> The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. It can be either .png or .jpg. **_It is recommended to be 600px square_**.

**Comment by harbinger55** [comment]
Uploaded new versions of the speaker images all are 600x600px or less and nothing is over 1MB

**Comment by adrianmoisey** [comment]
👍 Thanks!

**Pull request merged**
