### PR TITLE
[BUF-2022] Add initial speakers, update location.

### PR DESCRIPTION
**Pull request by onelioubov**
- Added accepted speakers.
- Removed **Virtual** from location info.
- Moved showcase image into the proper directory as the main sharing image.

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Spot checked a few speaker images (not all) and the ones reviewed were huge.
Please follow the Reference recommended guidelines:

https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields

`The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. **It can be either .png or .jpg. It is recommended to be 600px square**.`

**Comment by onelioubov** [comment]
> Spot checked a few speaker images (not all) and the ones reviewed were huge. Please follow the Reference recommended guidelines:
> 
> https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields
> 
> `The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. **It can be either .png or .jpg. It is recommended to be 600px square**.`

I just resized these. Thank you for pointing that out 🙂

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Speaker cards are all too big and should be reduced.

**Comment by onelioubov** [comment]
> Speaker cards are all too big and should be reduced.

Ack! I can't believe I overlooked these. Thank you. All set.

**Review by MikeRosTX — APPROVED** [review]

**Pull request merged**
