### PR TITLE
WIP - [INDY-2019] Close CFP

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
The propose link is still there - https://deploy-preview-6761--devopsdays-web.netlify.com/events/2019-indianapolis/welcome/

How do you close the CFP and remove that link?

**Comment by bridgetkromhout** [comment]
I've made the necessary adjustment. That `cfp_open` field is deprecated (and never removed such links, in any event).

**Comment by MikeRosTX** [comment]
@ghoneycutt, this is @bridgetkromhout's comment in a previous PR:

_The "propose" link in the header is controlled in the yml file by commenting out "propose", which you did. the cfp_open field is deprecated. None of your dates need to be commented out._

**Comment by ghoneycutt** [comment]
Thanks for the help!

**Pull request merged**
