### PR TITLE
[HOU-2022] Speakers images corrections

### PR DESCRIPTION
**Pull request by azhanov**
[HOU-2022] Speakers images corrections

### CODE REVIEW

**Comment by azhanov** [comment]
[HOU-2022] Speakers images corrections

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Once this image is decrease to 800x800 px, we should be good to proceed with merge.
static/events/2022-houston/speakers/david-stokes.png

**Comment by MikeRosTX** [comment]
This file **david-stokes.png (2525×2525)** has not changed and should be decreased to 800x800.

**Comment by azhanov** [comment]
Image size decreased.

**Review by MikeRosTX — APPROVED** [review]

**Pull request merged**
