### PR TITLE
[CPH-2019] Add Philipp and Eficode

### PR DESCRIPTION
**Pull request by JasmineCrozier**
Adding a sponsor and an ignite speaker

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
`philipp-krenn.jpeg` doesn't appear to be used - just the png one - do you want to remove it?

**Comment by JasmineCrozier** [comment]
not sure why there's two, but yes please remove the one that is not used. Or can I do it? @bridgetkromhout

**Comment by bridgetkromhout** [comment]
You could, but it’s okay.

**Comment by JasmineCrozier** [comment]
@bridgetkromhout sorry i was not sure how to do it. I'll ask my colleagues for next time ;)
Thank you!

**Pull request merged**
