### PR TITLE
[DSM-2019] Update social sponsor and remaining sponsor counts

### PR DESCRIPTION
**Pull request by timgifford**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by timgifford** [comment]
@MikeRosTX The merge request was accepted, and I'm not seeing the changed on the site. Do you have any visibility into where the change is in the pipeline?

**Comment by MikeRosTX** [comment]
I see Sponsorship Remaining for each one was update. Anything else missing?
image

**Comment by timgifford** [comment]
@MikeRosTX It looks like it is there now. 

Something is changing my image link again. Somehow the `srcset` attribute is getting added with the `1x` and 2x`. Not sure where that is being added. We were having a similar issue when we were using a non-local url as the image source. I changed to a local image and it was working for the last couple PRs. It's our payment link, so it's fairly important.

```
<img src="/events/2019-des-moines/paynow.gif" srcset="/events/2019-des-moines/paynow.gif 1x, /events/2019-des-moines/paynow@2x.gif 2x">
```

**Comment by mattstratton** [comment]
This will happen with all images during the build. We can’t override it for a specific image.

**Comment by mattstratton** [comment]
Can this be changed from a gif to a png or jpg?

**Pull request merged**
