### PR TITLE
[PDX-2017] Add third day info

### PR DESCRIPTION
**Pull request by BillWeiss**
We should probably link to CFPs and talk about sponsorships, right?

Please don't merge this until one of the PDX organizers (including me) says "yep, looks good" :)

### CODE REVIEW

**Comment by BillWeiss** [comment]
Alright, 👍

**Comment by MikeRosTX** [comment]
Set to **do-not-merge** until @BillWeiss or someone from PDX gives thumbs up to proceed with merge.

**Comment by MikeRosTX** [comment]
Does **Alright** 👍 mean "**yep, looks good**"?  😉 😆

**Comment by BillWeiss** [comment]
Yes, merge away, please :)

**Pull request merged**
