### PR TITLE
[Belem-2018] Start Devopsdays Belém page

### PR DESCRIPTION
**Pull request by pigor**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @pigor - I have updated your pull request to use the local language - please make any additional changes as desired, and let us know if this looks good to you. You can see the preview here: https://deploy-preview-5107--devopsdays-web.netlify.com/events/2018-belem/welcome/

The next thing you probably want to do is update your event's image for the front page. You'll put it at https://github.com/devopsdays/devopsdays-web/blob/master/static/events/2018-belem/logo-square.jpg

**Comment by gomex** [comment]
@pigor if you need help to put it at https://github.com/devopsdays/devopsdays-web/blob/master/static/events/2018-belem/logo-square.jpg let me know, ok?

**Comment by bridgetkromhout** [comment]
Hi, @pigor -

To clarify: we are not waiting to merge because you need to add anything else to this pull request. We are waiting to make sure you are okay with all my changes. Please let us know - thank you!

**Comment by pigor** [comment]
hi @bridgetkromhout, thank you for updates, everything is great for me! :)

**Comment by pigor** [comment]
@gomex ok, we will check it, thank you!

**Pull request merged**
