### PR TITLE
[CAI-2018] Updating organizers, CFP, sponsorship packages

### PR DESCRIPTION
**Pull request by aameen79**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
If I were to take a wild guess, I would say this errors might be related to @aameen79 not having to rebase in a long time. Please rebase to see if errors resolve themselves.

**Comment by aameen79** [comment]
I think I fixed the bug

**Comment by aameen79** [comment]
Done :) @MikeRosTX

**Comment by aameen79** [comment]
Dears,
The changes have not appeared yet on website, is this normal?
@MikeRosTX @bridgetkromhout @KrisBuytaert

**Comment by MikeRosTX** [comment]
@aameen79 the changes finally got merged. After a couple of other PRs came through and got merged, it kicked off a build process again and you updates are now showing up.

**Pull request merged**
