### PR TITLE
[GAL-2018] Add initial details for DevOpsDays Galway 2018

### PR DESCRIPTION
**Pull request by electrofelix**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Reviewing everything and creating team email.

**Comment by MikeRosTX** [comment]
@electrofelix, we're missing emails for:

-  Coleman Corrigan
-  Alan Duggan
-  Joe Goggins
-  Bryan Solan
-  Kim Tighe
-  Padraic Wade
-  Rusty Weise

On the **_organizers-galway-2018@devopsdays.org_** are:

-  daragh.bailey@gmail.com
-  emma.meehan3@gmail.com
-   j3p0uk@gmail.com
-  lyndaoleary29@gmail.com
-  noel.healy@gmail.com
-  sc@linux.it | sc@linux.it

**Comment by MikeRosTX** [comment]
Sorry I missed the email, I will get this done today.

Darragh Bailey - daragh.bailey@gmail.com (HPE) DevOps Galway Meetup
Emma Meehan - emma.meehan3@gmail.com (Student/Cisco)
Jon Paul Sullivan - j3p0uk@gmail.com (Cisco)
Stefano Canepa - stefano@canepa.ge.it (HPE)
Coleman Corrigan - coleman.corrigan@gmail.com (OpenJaw)
Alan Duggan - aduggan@hpe.com (HPE)
Joe Goggins - joeygoggins@gmail.com (Aspect Software)
Noel Healy - noel.healy@gmail.com (Cisco) DevOps Galway Meetup
Trista Monehan - tristamonaghan@gmail.com (Ericsson)
Lynda O'Leary - lyndaoleary29@gmail.com (HPE) Docker Galway Meetup & Women in Technology
Bryan Solan - bryansolan@gmail.com (Aspect Software)
Kim Tighe - ktighe@hpe.com (DXC) Irish Womens Network (Previously in HPE before split)
Padraic Wade - padraic.wade@woodgroup.com (Woodgroup)
Rustry Weise - rusty.weise@hpe.com (HPE)

**Comment by electrofelix** [comment]
Hi Mike,

Sorry I was about to follow up with the full details:

RETURNING

Darragh Bailey - daragh.bailey@gmail.com (HPE) DevOps Galway Meetup
Emma Meehan - emma.meehan3@gmail.com (Student/Cisco)
Jon Paul Sullivan - j3p0uk@gmail.com (Cisco)

NEW

Stefano Canepa - stefano@canepa.ge.it (HPE)
Coleman Corrigan - coleman.corrigan@gmail.com (OpenJaw)
Alan Duggan - aduggan@hpe.com (HPE)
Joe Goggins - joeygoggins@gmail.com (Aspect Software)
Noel Healy - noel.healy@gmail.com (Cisco) DevOps Galway Meetup
Lynda O'Leary - lyndaoleary29@gmail.com (HPE) Docker Galway Meetup & Women
in Technology
Bryan Solan - bryansolan@gmail.com (Aspect Software)
Kim Tighe - ktighe@hpe.com (DXC) Irish Womens Network (Previously in HPE
before split)
Padraic Wade - padraic.wade@woodgroup.com (Woodgroup)
Rustry Weise - rusty.weise@hpe.com (HPE)

REMOVE

Emil Dimitrov - emildi@gmail.com
John Fitzpatrick - fitzpatrick@chef.io
Graham Hayes - graham@hayes.ie
Xabier Pedrera - xabier.pedrera@hpe.com
Waldemar Znoinski - wznoinsk@redhat.com


I think the only one in the previous email that I skipped in the PR as they
have been busy since the initial response and waiting to check they have
freed up and can help is:
Trista Monehan - tristamonaghan@gmail.com (Ericsson)


Darragh Bailey
"Nothing is foolproof to a sufficiently talented fool" - unknown

**Pull request merged**
