### PR TITLE
[ZRH-2020] Add new Event DevOpsDays Zürich 2020

### PR DESCRIPTION
**Pull request by RomanoRoth**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by mattstratton** [comment]
HI @RomanoRoth 	!

Please send an email to `info@devopsdays.org` with the names and email addresses of the folks who are on your organizing committee. Please also update the `data/events/2020-zurich.yml` in this PR with those names under the `team_members` section.

I will propose the change myself for this one - but we have collapsed email aliases to make things easier. The email address for the event will be `zurich@devopsdays.org`

**Comment by bridgetkromhout** [comment]
Hi, @RomanoRoth! We will close this PR if you aren't able to add your list of organizers. If you are ready, please edit your config file to have your organizer info, like this: https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-zurich.yml#L38-L158

**Comment by RomanoRoth** [comment]
@bridgetkromhout  here we go:
- name: "Martin Thalmann"
    twitter: "martin_thalmann"
    employer: "Swisscom AG"
    bio: "I’m a passionate DevOps Enthusiast who strongly believes in the power of this movement. I’m currently helping a Swiss telco operator in adapting DevOps principles in a large enterprise. Beside that I’m co-organizer of the [DevOps Enthusiast Meetup in Zurich](https://www.meetup.com/DevOps-Meetup-Zurich/). I do have a background as a Software Engineer and experience in several Line- and Project-Management positions."
    github: ""
    facebook: ""
    linkedin: "https://www.linkedin.com/in/martinthalmann/"
    website: ""
    image: "martin-thalmann.jpg"
  - name: "Dirk Lehmann"
    bio: "<p>Dirk is a DevOps evangelist and Continuous Delivery expert at SAP.</p><p>Since 2001 Dirk worked in various roles at SAP including Development and Operations.</br>Together with his former team \"TwoGo by SAP\" he established the first Continuous Delivery implementation at SAP, delivering value daily to their customers.</p><p>In his current role, Dirk is a Cloud Quality Coach at SAP with focus on Continuous Delivery and DevOps practices.</p><p>Dirk is a frequent speaker at international conferences on DevOps and Continuous Delivery.</p>"
    twitter: "doergn"
    linkedin: "https://www.linkedin.com/in/dirk-lehmann-7712bb125/"
    image: "dirk-lehmann.jpg"
  - name: "Nadine Biedermann"
    bio: "<p>Metaphorically, Nadine can conquer the world with her clever quips and her charme. Literally, Nadine's wit and her creativity will enhance your Marketing and Social Media experience of the DevOpsDays 2019.</p>"
    linkedin: "https://www.linkedin.com/in/nadine-biedermann-46436516b"
    image: "nadine-biedermann.jpg"
  - name: "Romano Roth"
    bio: "<p>I'm an experienced software consultant and DevOps enthusiast working at Zühlke. My passion lies in radically transforming monolithic waterfall IT organizations into scalable agile teams doing DevOps.</p>"
    image: "romano-roth.jpg"
    employer: "Zühlke"
    twitter: "RomanoRoth"
    linkedin: "https://www.linkedin.com/in/romanoroth/"
  - name: Carsten Plum
    bio: "<p>I am passionate about everything agile and human centered. Having started my career in an old school waterfall environment more than 20 years ago as a software engineer and project manager, I am now happy to enable teams and large organisations to establish agile methods and DevOps. I specifically like the combination (and challenges) of technical and cultural aspects.</p>"
    Website: https://www.xing.com/profile/Carsten_Plum2/
    image: "carsten-plum.jpg"
  - name: "Selina Reist"
    employer: "Federal Office of Information Technology"
    bio: "<p>I am an enthusiast for everything visual:photography, movies and animations, pictograms, infofraphics, visual design, graphical recordings, UX-Design. I also like to combine these skills in crossfunctional teams to enable app development, transformation processes and last but not least communicate and teach DevOps practices in large federal organizations</p>"
    image: "selina-reist.jpg"
  - name: Lorena Dütsch
    bio: "<p>TBD</p>"
    Website: 
    image: "lorena-dutsch.jpg"
  - name: "Tobias Weinmann"
    bio: "Having worked as a developer, systems engineer and team lead in IT operations, the ideas and concepts behind DevOps are very close to my heart. As I am passionate about coding since my teenage years, I am fascinated by concepts like Infrastructure as Code, Social Coding, and cloud native technologies trying to get hands-on whenever possible. I enjoy lateral thinking and my basic premise is that \"we cannot solve our problems with the same thinking we used when we created them\" (Albert Einstein). In my current role I dedicate all my energy to introducing and spreading DevOps principles and practices in the broader organization."
    linkedin: "https://www.linkedin.com/in/tobias-weinmann"
    twitter: "Wankinobi75"
    github: "tweinmann"
    image: "tobias-weinmann.jpg"
  - name: "Noëmi Kruesi"
    twitter: ""
    employer: "Swisscom AG"
    bio: "<p>It is a well-known fact that girls just wanna have fun. It is also known that companies that incorporate DevOps get more done. How do these two facts relate, you ask?</p>
<p>Meet Noëmi Krüsi, a girl who gets stuff done. Her strengths and talents lie in design and administration. As a creative allrounder she will be assisting with the design and social media of the DevOpsDays 2018.</p>"
    github: ""
    facebook: ""
    linkedin: "https://www.linkedin.com/in/noëmi-krüsi-992436127/"
    website: ""
    image: "noemi-krusi.jpg"
- name: "Matías E. Fernández"
    twitter: "matiasfrndz"
    employer: "Swisscom AG"
    bio: "DevOps evangelist, Kanban practitioner, Lean Startup advocate, Linux and OSS afficionado.<p>
Keen learner and challenger of the status quo.<p>
Enabling organisations to achieve outstanding and sustainable results that exceed customers’ expectations is his passion."
    github: "matiasfrndz"
    facebook: ""
    linkedin: "https://www.linkedin.com/in/matiasfrndz/"
    website: "https://matiasfrndz.ch/"
    image: "matias-e-fernandez.jpg"
- name: "Tobias Brunner"
    twitter: "tobruzh"
    employer: "VSHN AG"
    bio: "Tobias (aka tobru) is a DevOps Engineer and Partner at VSHN and one of the founding members of VSHN. He loves Open Source and everything about state-of-the-art technologies like Docker, Kubernetes and OpenShift. In his day job he is responsible for the Container Platform team at VSHN, works on the next big thing and brings APPUiO - The Swiss Container Platform - to the next level."
    github: "tobru"
    facebook: ""
    linkedin: "https://www.linkedin.com/in/tobru/"
    website: "https://tobru.ch/"
    image: "tobias-brunner.jpg"
 - name: "Julia Faust"
    bio: "<p>Julia loves to communicate and to bring people and solutions together. As a Financial Controller for the IT development department of a Swiss Telco, she accompanies the transformation into an agile setup from the beginning.</p><p>DevOps principles such as \"build it, run it\", autonomy of the team, as well as short and reasonable planning processes motivate her a lot. Julia is thrilled by discussing the basic ideas and causes of agility and to inspire others.</p>"
    image: "julia-faust.jpg"
  - name: "Vittorio Boccone"
    twitter: "drbokko"
    employer: "Dectris Ltd."
    bio: "Vittorio grew up in the a world where hardware and software are in perfect equilibrium. At 8 he started customizing and modifying anything with an engine or a CPU. Curious about the nature of things he later became a detector and accelerator physicist. After 13 years at CERN, he's now often seen at Dectris happily developing Dectris X-ray detectors. He's comfortable with any lab equipment, programming language or particle accelerator."
    github: "https://github.com/drbokko"
    facebook: ""
    linkedin: "https://www.linkedin.com/in/vittorio-boccone-1998a94/"
    website: ""
    image: "vittorio-boccone.jpg"

**Comment by RomanoRoth** [comment]
@bridgetkromhout I've checked in the changes for the team in the yaml

**Pull request merged**
