### PR TITLE
[RDU-2019] removed andrew sullivan as organizer

### PR DESCRIPTION
**Pull request by normalfaults**
[RDU-2019] removed andrew sullivan as organizer

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
note: when merging, also update email and Slack.

**Comment by MikeRosTX** [comment]
What about all the other changes?

- Add Craig Cook as an organizer on the official page
- Take off Andrew Sullivan (unless he wants to be, but I haven’t heard from him as far as interest)
- Add a speaker navigation at the top so you can put the suggested topics we had listed, as well as that copy on a separate page.
- Do we want our photos up on the page? Seems like most other cities have that.

**Comment by normalfaults** [comment]
I was going to put those on separate pull requests once i get content for those items.

**Comment by normalfaults** [comment]
also how did you get that list of actions ? :)

**Comment by MikeRosTX** [comment]
Completed the following:

* Add Craig Cook as an organizer on the official page
* Take off Andrew Sullivan (unless he wants to be, but I haven’t heard from him as far as interest)

Leaving the following for new PR:
* Add a speaker navigation at the top so you can put the suggested topics we had listed, as well as that copy on a separate page.
* Do we want our photos up on the page? Seems like most other cities have that.

**Comment by normalfaults** [comment]
thanks!

**Pull request merged**
