### PR TITLE
[MTL-2020] Add Montreal 2020 event with dates

### PR DESCRIPTION
**Pull request by idcrosby**
Initial add of 2020 event for Montreal, with event dates.

### CODE REVIEW

**Comment by idcrosby** [comment]
My mistake, we do have a contract, I'll add the venue to the PR

**Comment by MikeRosTX** [comment]
> My mistake, we do have a contract, I'll add the venue to the PR

While you're at it, also remove **conduct-fr.md** & **_conduct-pt-br.md_** from your repo because they're not being used.

**Comment by idcrosby** [comment]
Portuguese conduct removed. We will use the French version as we run a bilingual event

**Comment by idcrosby** [comment]
Portuguese conduct removed. We will use the French version as we run a bilingual event

**Comment by idcrosby** [comment]
Thanks for the review and extra fixes @MikeRosTX !

**Pull request merged**
