### PR TITLE
[NYC-2023] Adding COVID policy, updating welcome page

### PR DESCRIPTION
**Pull request by ceren**
mimicking Chicago's pages (with permission), made relevant regional changes and policy changes.

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Check the formatting of you Welcome page, because it seems to be having some problems aligning correctly.

image

**Comment by ceren** [comment]
> Check the formatting of you Welcome page, because it seems to be having some problems aligning correctly.
> 
> image

yeah, we know. we're working on fixing that next.

**Comment by MikeRosTX** [comment]
> > Check the formatting of you Welcome page, because it seems to be having some problems aligning correctly.
> 
> yeah, we know. we're working on fixing that next.

Would you like for us to merge AS IS or wait until y'all have resolved the formatting?

**Comment by ceren** [comment]
> > > Check the formatting of you Welcome page, because it seems to be having some problems aligning correctly.
> > 
> > 
> > yeah, we know. we're working on fixing that next.
> 
> Would you like for us to merge AS IS or wait until y'all have resolved the formatting?

We've gotten help from @miketheman and it should look fine now! 
I think we need the unblocking from linters again, though?

**Review by MikeRosTX — APPROVED** [review]

**Comment by ceren** [comment]
thanks! We see the problem with the location link in text, we'll get to that next.

**Pull request merged**
