### PR TITLE
[AMS-24] Update sysdig logo

### PR DESCRIPTION
**Pull request by FloorD**
Sysdig is one of our sponsors! They have a new logo, so I renamed the previous logo to `sysdig-before-24.png` and the new logo is `sysdig.png` so that should update it across devopsdays.org? Yes? Maybe? Yell at me if I'm wrong?

### CODE REVIEW

**Comment by adrianmoisey** [comment]
The old references to the logo need updating too, see https://github.com/devopsdays/devopsdays-web/tree/main/utilities#updating-a-sponsor-image-or-data

**Comment by yvovandoorn** [comment]
@FloorD please see @adrianmoisey comment 🙂

**Comment by phrawzty** [comment]
@FloorD This PR has been open for two weeks now. Please either move forward or let us know if you require assistance; otherwise, we'll go ahead and close it out, and you can re-open when you're ready. 👍

**Comment by phrawzty** [comment]
> @FloorD This PR has been open for two weeks now. Please either move forward or let us know if you require assistance; otherwise, we'll go ahead and close it out, and you can re-open when you're ready. 👍

Closing due to inactivity.

**Pull request closed without merging**
