### PR TITLE
[GYN-2023] Create new event

### PR DESCRIPTION
**Pull request by strund3r**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by somatorio** [comment]
Could you please also change this one? https://github.com/devopsdays/devopsdays-web/blob/main/static/_redirects#L43

**Comment by somatorio** [comment]
Slack and distribution list were synced with the team members on the PR

**Comment by phrawzty** [comment]
@somatorio Good to merge?

**Review by somatorio — APPROVED** [review]

**Comment by somatorio** [comment]
yes :)

**Pull request merged**
