### PR TITLE
[moscow-2018] fixed speakers photos format

### PR DESCRIPTION
**Pull request by aprilix**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
I took a look and those file extensions are not why you can't see your speakers. I fixed that in https://github.com/devopsdays/devopsdays-web/pull/4762 - this branch now has a merge conflict (and these changes aren't necessary anyhow). Give it a minute to build, please. :) The main thing you want right now is a program.

**Comment by aprilix** [comment]
Thank you so much!

**Comment by bridgetkromhout** [comment]
See my email - I can enter your schedule information if you can send it to me.

**Comment by bridgetkromhout** [comment]
This is now working: https://www.devopsdays.org/events/2018-moscow/speakers/

**Comment by bridgetkromhout** [comment]
It’s late - but you can add the program like this: https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#program

**Pull request closed without merging**
