### PR TITLE
[Berlin] add devopsdays berlin 2020

### PR DESCRIPTION
**Pull request by cpanato**
Add page for DevopsDays Berlin 2020

### CODE REVIEW

**Comment by cpanato** [comment]
Ready to go

**Comment by bridgetkromhout** [comment]
Hi, @cpanato - please include the missing files that are needed to list the 2020 event. (The [new event script](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_new_event.sh) would create them, or you can add them manually). Also, please use the correct new email - berlin@devopsdays.org - thanks.

**Comment by bridgetkromhout** [comment]
Hi, @cpanato - I'm closing this PR as it cannot stand alone. Please open a PR when you have the necessary files - I recommend using https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_new_event.sh to build out the files. Thanks.

**Pull request closed without merging**
