### PR TITLE
[EDI 2019] talks

### PR DESCRIPTION
**Pull request by MichalBryxi**
- First wave of speakers & sponsors
 - Enabled both program & speakers sections

cc: @kevinhcross looks good?

### CODE REVIEW

**Comment by kevinhcross** [comment]
@MichalBryxi I had a quick look and I think there is more info we can add at this stage. A few of the speakers profiles only have first names but we actually have full names and bios for all the speakers. I will send you the location of that info on another channel.

**Comment by MichalBryxi** [comment]
@kevinhcross I think now it has all the possible data we have? Anything missing?

**Comment by bridgetkromhout** [comment]
You need the speakers.md and program.md files for those links to work. Here are the templates:

https://github.com/devopsdays/devopsdays-web/blob/master/utilities/examples/templates/program.md

https://github.com/devopsdays/devopsdays-web/blob/master/utilities/examples/templates/speakers.md

**Comment by MichalBryxi** [comment]
Sorry @bridgetkromhout. Added, pushed.

**Pull request merged**
