### PR TITLE
Bhe 2019 - bio and others

### PR DESCRIPTION
**Pull request by devopsdaysbh**
Changelog

Fixed bios and program

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please follow the guidelines for speaker images.

- Must be square
- Has to be **_.png_** or **_.jpg_** extension format, **_because .jpeg will not render_**.

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields

The image for the speaker. This image is relative to the static/events/YYYY-CITY/speakers directory. **_It can be either .png or .jpg. It must be square, and 300px square, 600px square, or 900px square._**

**Comment by MikeRosTX** [comment]
Please resize all pictures to be square, and 300px square, 600px square, or 900px square.

**Comment by gomex** [comment]
Please follow these instructions ;) 

https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields

**Comment by gomex** [comment]
I had a talk with @MikeRosTX and we agreed that size is fine ;)

**Comment by bridgetkromhout** [comment]
I see that @gomex has merged this, but the deploy preview showed errors you may want to fix: https://deploy-preview-8341--devopsdays-web.netlify.com/events/2019-belo-horizonte/speakers

If you do not have pictures for speakers, then remove the line that loads them: https://github.com/devopsdays/devopsdays-web/blame/master/content/events/2019-belo-horizonte/speakers/juliano-silveira.md#L3

**Pull request merged**
