### PR TITLE
[LUANDA-2020] Add new members, date, photos, logo and description.

### PR DESCRIPTION
**Pull request by JovanyNegocio**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi @JovanyNegocio - please email us at info@devopsdays.org and send us the email addresses for these new members. We need to update the email group and Slack at the same time as the website.

**Comment by JovanyNegocio** [comment]
> Hi @JovanyNegocio - please email us at [info@devopsdays.org](mailto:info@devopsdays.org) and send us the email addresses for these new members. We need to update the email group and Slack at the same time as the website.

Done!

**Comment by bridgetkromhout** [comment]
Please look at Jose's picture, and crop it appropriately; when organizer pictures are not square, the auto-cropping may not do a good job: https://deploy-preview-9588--devopsdays-web.netlify.com/events/2020-luanda/contact

**Comment by JovanyNegocio** [comment]
> Please look at Jose Tandavala's picture, and crop it appropriately; when organizer pictures are not square, the auto-cropping may not do a good job: https://deploy-preview-9588--devopsdays-web.netlify.com/events/2020-luanda/contact


Thanks. I actually saw this detail I tried to use the best photo possible but I couldn't. I already booked a new photo session with Tandavala

**Pull request merged**
