### PR TITLE
[jf-2023]  Inclusion of speakers already confirmed

### PR DESCRIPTION
**Pull request by jgt-josegeraldo**
Inclusão de palestrantes já confirmados, ainda estamos aguardando alguns retornos de confirmação, que serão incluídos nos próximos pull requests.

### CODE REVIEW

**Comment by somatorio** [comment]
Só para evitar situações ruins (como por exemplo a pessoa descobrir dessa forma), já enviaram os emails e afins para as pessoas que não foram aceitas?

**Comment by jgt-josegeraldo** [comment]
Sim, por isso tomei cuidado para entrar em contato com todo mundo, não queira deixar ninguém sem pelo menos um retorno.

**Comment by FloorD** [comment]
Screenshot (567)

I wonder why I can see a nav item for speakers (and on their speaker page I can click to view their session) but there's no program? Or do you just want to publish speakers first? I think maybe my confusion stems from my preference to select a program made up from several sessions/speakers, rather than trying to make sessions/speakers work in a schedule somehow?

**Comment by jgt-josegeraldo** [comment]
Sorry, I was just trying to keep the page up to date with the points we've already confirmed.

We already have the speakers and which lectures, but we still have a pendency linked to the schedules.

If that's the case, you can refuse this pull request, which after I make another one only when the programming is already complete.

**Pull request merged**
