### PR TITLE
[POZ-2021] date and team fix

### PR DESCRIPTION
**Pull request by Kacperek0**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by mattstratton** [comment]
Have you emailed info@devopsdays.org with the organizer changes for the email list/slack?

**Comment by Kacperek0** [comment]
> Have you emailed [info@devopsdays.org](mailto:info@devopsdays.org) with the organizer changes for the email list/slack?

No! Thanks for the reminder :)

**Comment by Kacperek0** [comment]
@mattstratton Now it's done :)

**Comment by yvovandoorn** [comment]
@Kacperek0 did you see @phrawzty's request in the mail with regards to complete emails?

**Pull request merged**
