### PR TITLE
Use existing docker image

### LINKED ISSUE #4127: Change to use common docker image
There is an updated docker setup that we won't have to maintain here - https://hub.docker.com/r/jojomi/hugo/

We should update our docs and scripts (and travis build) to use this instead.

### PR DESCRIPTION
**Pull request by adrianmoisey**
Fixes #4127

Replaces https://github.com/devopsdays/devopsdays-web/pull/4401

(I deleted an re-created my fork, cause my upload bandwidth is slow, and then killed my previous branch)

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks! I'm going to hold off on merging this since I don't have the bandwidth right now to test it (literal and figurative - I'm on a plane with terrible wifi right now). It's possible another person may get a chance before me; I'm pretty slammed for the next few days.

**Comment by adrianmoisey** [comment]
No rush from my side. This is something that only makes sense to merge if you're 100% confident with the change.

**Comment by bridgetkromhout** [comment]
I'm going to ask @mattstratton to take a look since it affects the build.

**Comment by adrianmoisey** [comment]
🥇

**Pull request merged**
