### PR TITLE
Clarifying guidance on payments for speakers.

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Clarifying guidance on payments for speakers.

### CODE REVIEW

**Comment by devopsdays-service** [comment]
@bridgetkromhout, thanks! Based upon the content in this PR, we need a review from @mattstratton, @MikeRosTX, @phrawzty and @bridgetkromhout

**Comment by KrisBuytaert** [comment]
+1

**Comment by mattstratton** [comment]
👍

**Comment by MikeRosTX** [comment]
👍

**Pull request merged**
