### PR TITLE
[Boise 2016] Adding Bodybuilding.com and ForgeRock sponsorshoips

### PR DESCRIPTION
**Pull request by tresni**

### CODE REVIEW

**Comment by mattstratton** [comment]
Can you resize the sponsor image down to 200x200?

**Comment by bridgetkromhout** [comment]
To clarify @mattstratton's request please see https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#sponsor-logos - thanks!

**Comment by mattstratton** [comment]
This script will help ya - https://github.com/devopsdays/devopsdays-web/blob/master/utilities/resize_sponsor_logo.sh

**Comment by tresni** [comment]
already done :)

**Comment by mattstratton** [comment]
Cool cool cool

**Pull request merged**
