### PR TITLE
[CHI-2019] objective url update

### PR DESCRIPTION
**Pull request by margaretvaltie**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Fine to change, since this is the only time and place it has been used.

**Comment by bridgetkromhout** [comment]
Here's how to do this correctly:

 #  url: http://mysponsor.com/?campaign=me # Use this if you need to over-ride a sponsor URL.

Add it under here: https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-chicago.yml#L189

And remove the change in this PR.

**Comment by mattstratton** [comment]
Oh, @margaretvaltie, yeah, I think you misunderstood my direction. I meant to do it in the event.yml not the sponsor.yml.

**Comment by mattstratton** [comment]
I'm going to close this PR and do the changes myself to make life easier for @margaretvaltie 	:)

**Pull request closed without merging**
