### PR TITLE
[Beijing-2018]Open registration.

### PR DESCRIPTION
**Pull request by martinliu**
Add registration link.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
"registration_closed: 2018-05-04" this doesn't take a date - just true/false reflecting current state, so I'd suggest not setting it.

**Comment by martinliu** [comment]
I will change that, but I did not see any error when I build locally. Thanks for your help!

**Comment by martinliu** [comment]
Ok, I got it fixed.

**Comment by bridgetkromhout** [comment]
I think you are right; we don't validate all the yaml. I just didn't want you to think that would do something that it will not.

**Pull request merged**
