### PR TITLE
Improves performance on program and speaker pages

### PR DESCRIPTION
**Pull request by mattstratton**
This change should help increase performance on the two heaviest templates (the program and the individual speaker)

### CODE REVIEW

**Comment by mattstratton** [comment]
After the latest tweak to the program page:
```
Template Metrics:

     cumulative       average       maximum
       duration      duration      duration  count  template
     ----------      --------      --------  -----  --------
   7.284321126s  132.442202ms     486.304ms     55  partials/future.html
   7.075130841s    2.382198ms    20.17775ms   2970  speaker/single.html
   6.634613378s   37.912076ms   83.655459ms    175  speakers/single.html
    6.01157401s     738.794µs    43.06075ms   8137  partials/head.html
   5.327928328s     663.585µs    24.69275ms   8029  partials/sponsors.html
   4.949253787s   16.608234ms   63.415541ms    298  welcome/single.html
...
Total in 15549 ms
```

That's much better! That cuts over ten seconds from the build on my local machine, which will make a bigger difference on slower ones.

**Comment by mattstratton** [comment]
For comparison, this is the speed/time in the netlify build with these latest changes:
`11:23:25 PM: Total in 10606 ms`

A previous deploy preview was:
`9:30:58 PM: Total in 55395 ms`

This shaves almost a minute off of the netlify part (the long part of deploy previews are the actual deploying of the files)

**Comment by mattstratton** [comment]
I've done some testing (but I recommend before merging/approving, someone else hit the deploy preview and check out Program pages on some cities as well as individual speaker pages)

**Comment by yvovandoorn** [comment]
I can confirm the massive increase!

```
Start building sites …
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown

                   |  EN
-------------------+--------
  Pages            |  8139
  Paginator pages  |     3
  Non-page files   |    54
  Static files     | 18103
  Processed images |     0
  Aliases          |   630
  Sitemaps         |     1
  Cleaned          |     0

Built in 10833 ms
```

**Pull request merged**
