### PR TITLE
[SHA-2020]Add shanghai event

### PR DESCRIPTION
**Pull request by overloadzy**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by overloadzy** [comment]
> Just curious... 🤔
> Why are you including these 2 files, **_conduct-fr.md_** and **_conduct-pt-br.md_**?

I just used add_new_event.sh script to generate the directory, these 2 files are default content in the folder.

**Comment by MikeRosTX** [comment]
The Shanghai event is happening **_in person at a venue_** or **_virtual_**?

**Comment by overloadzy** [comment]
> The Shanghai event is happening **_in person at a venue_**

The Shanghai event is happening in person at The Longemont Hotel Shanghai, not a virtual conference.

**Comment by MikeRosTX** [comment]
I will need to remove 5 organizers from Slack and team email of the 2019 Contact list from the link below:
https://devopsdays.org/events/2019-shanghai/contact

Is that OK with you?

**Comment by overloadzy** [comment]
> I will need to remove 5 organizers from Slack and team email of the 2019 Contact list from the link below:
> https://devopsdays.org/events/2019-shanghai/contact
> 
> Is that OK with you?
> 
> > **[Contact](https://devopsdays.org/events/2019-shanghai/contact/)**Contact information for devopsdays Shanghai 2019

It's OK, thanks!

**Comment by MikeRosTX** [comment]
Please send an email to the Core team that lists all your organizer's full names and their emails.

**Pull request merged**
