### PR TITLE
 [HOU-2019] Adding FireMon silver sponsor & LinkedIn link

### PR DESCRIPTION
**Pull request by skryukova**
Adding FireMon silver sponsor

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello,

The title and comment of this PR only refer to adding FireMon as a sponsor, which is done in commit 
638689d (and looks fine, btw).

However, there's also commit 1e08373 which attempts to add a LinkedIn link. If the preview is anything to go by, I don't think that commit does what you want:

image

Please verify and confirm these commits. Thanks!

**Comment by skryukova** [comment]
The commit does not work as intended on local hugo server. I read online that it is "not expected" to work on localhost, and needs to be on the real server to work. Could you please get this merged, and if it still does NOT work as expected, I will pull it off?

**Comment by phrawzty** [comment]
To be fair, I'm referring to the Netlify preview build: https://deploy-preview-6192--devopsdays-web.netlify.com/events/2019-houston/welcome/

Where did you read this information? I believe you - I'm just curious myself! 😄

**Comment by skryukova** [comment]
So the code is taken from here: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/follow-company-plugin
I can't find the article right now. I did find this one: https://stackoverflow.com/questions/43236492/linkedin-javascript-sdk-is-working-on-localhost-but-not-on-server that talks about adding your website to "Valid SDK Domains". Perhaps, that is the problem?

In any case, I am fine if only one of the changes is merged. I would love to have "follow on LinkedIn" button, but that is not absolutely required.

**Comment by bridgetkromhout** [comment]
I see the button in the preview:
screen shot 2019-01-27 at 11 07 19 am

You may want to adjust layout, but it's present, so I'll merge it.

**Pull request merged**
