### PR TITLE
[FOR-2019] Creating placeholder for Fortaleza

### PR DESCRIPTION
**Pull request by gb8may**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please do a **rebase**, because the **errors** are happening because you're way behind.

**_This branch is 1 commit ahead, 4967 commits behind devopsdays:master._**

**Comment by gb8may** [comment]
rebase done

**Comment by MikeRosTX** [comment]
Not sure what's going on.

1. Recommend you close this PR. 
2. Delete your local repo.
3. Clone a new repo.
4. Make all the changes.
5. Submit a new PR.

**Comment by bridgetkromhout** [comment]
Hi, @gb8may - this is the problem - see how you're 4977 commits behind?

Screen Shot 2019-05-18 at 12 04 24 PM

Please follow these directions to bring your fork up to date correctly: https://github.com/devopsdays/devopsdays-web/blob/master/CONTRIBUTING.md#editing-your-site

**Comment by gb8may** [comment]
OK

**Pull request closed without merging**
