### PR TITLE
Fix sponsor logos on archived events

### PR DESCRIPTION
**Pull request by adrianmoisey**
Remove `srcset`, as the @2x images don't seem to exist.

This should fix https://github.com/devopsdays/devopsdays-web/issues/8194

From my investigation I think this is the correct solution.

### CODE REVIEW

**Comment by adrianmoisey** [comment]
https://deploy-preview-8203--devopsdays-web.netlify.com/events/2015-minneapolis/welcome/

**Comment by mattstratton** [comment]
That gets you halfway there. A lot of the old legacy events are now hosted at https://github.com/devopsdays/devopsdays-legacy so you need to do the same "search and replace" on that repo too :)

**Comment by mattstratton** [comment]
https://github.com/devopsdays/devopsdays-web/blob/master/static/_redirects#L1-L34 for more context

**Comment by adrianmoisey** [comment]
> so you need to do the same "search and replace" on that repo too :)

There aren't any matches for `srcset` on that repo, the image URLs all look good to me.

**Comment by mattstratton** [comment]
Fair. I guess the legacy site was updated :)

**Comment by bridgetkromhout** [comment]
Super awesome, @adrianmoisey! Nice to get those legacy sites fixed.

**Pull request merged**
