### PR TITLE
[Montreal-2022] Sponsors no longer accepted

### PR DESCRIPTION
**Pull request by sebagomez**
as of Friday Oct 14th EOD, sponsors are no longer accepted.
Added last sponsors, and included a couple of background (header) and sharing images

### CODE REVIEW

**Comment by glasnt** [comment]
Should Palo Alto Networks have a dedicated logo, and Prisma be split out into it's own sponsor? I don't think the canonical Palo Alto logo should have something that's not palo alto, just for ease of future organisers.

**Comment by sebagomez** [comment]
Hey @glasnt, I thought about that, and actually that was my first aproach, but I then reverted it and just updated the Palo Alto Networks logo.

Let me create a new Prisma Cloud sponsor and use that one

**Comment by phrawzty** [comment]
@glasnt Looks OK to me but please 👀 :)

**Comment by sebagomez** [comment]
@mattstratton I thought about it, but it had been only used by us in the past and the logo had the same issue. White letters over white background... that's why I updated the logo itself

**Pull request merged**
