### PR TITLE
add sponsors tlv

### PR DESCRIPTION
**Pull request by gilzellner**

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello,

Sponsor logos need to be 200px square or else they don't render properly. Also, the backgrounds must be white or transparent - anything else looks weird.

Please re-size the sponsor logos and adjust the background on the AppsFlyer logo as appropriate. If you'd like some help with these operations, please don't hesitate to ask!

screen shot 2016-09-27 at 10 31 20

**Comment by gilzellner** [comment]
so the problem is with: redislabs, logz.io and appsflyer? 
all else are ok ?

**Comment by phrawzty** [comment]
From this particular PR (as of 59e0aa2):
* `AppsFlyer.png` is 225 × 225 px and has an incorrect background.
* `Inneractive.png` is 158 × 144 px.
* `Outbrain.png` is 192 × 192 px.
* `soluto.png` is 180 × 241 px.
* `yotpo.png` is 192 × 192 px.

I didn't check the RedisLabs or Logz.io logos, but I note that they have borders built into them, which is also incorrect (the site draw the borders with CSS). Those were added by another event though, so don't worry about them for now - I'll make a note on our side to deal with them separately.

To be honest, as long as the images are *square*, about the right size, and don't have coloured backgrounds, that's all that matters. 😄 For now, if you could fix `AppsFlyer.png`, `Inneractive.png`, and `soluto.png`, that'd be great.

**Comment by bridgetkromhout** [comment]
I'm going to merge this, then clear up the image issues.

**Pull request merged**
