### PR TITLE
Fix sed commands to use correct placeholder for file

### PR DESCRIPTION
**Pull request by electrofelix**
Remove argument after '-i' as it is being recognized as the sed script to execute
rather than as an argument to the option flag.

### CODE REVIEW

**Comment by devopsdays-service** [comment]
@electrofelix, thanks! Based upon the content in this PR, we need a review from @mattstratton and @bridgetkromhout

**Comment by electrofelix** [comment]
Was this script perhaps written for Mac? The change I've made allows it to work on Ubuntu, but I'm not sure about cross platform compatibility with sed.

**Comment by adrianmoisey** [comment]
I think it makes sense to copy what the other scripts are doing, take a look at https://github.com/devopsdays/devopsdays-web/blob/c2e36cb117669f27ff9282e76c40855acf6b112a/utilities/add_new_event.sh#L5-L13 as an example.

**Comment by mattstratton** [comment]
Yeah, the -i is for x-plat to Mac. I want to get a +1 from @bridgetkromhout before merging and I am pretty sure she is AFK for a bit.

**Pull request merged**
