### PR TITLE
[ZRH-2018] add nine.ch as gold sponsor + new logo for Atlassian

### PR DESCRIPTION
**Pull request by drbokko**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Recommend using jpg instead of png format. P
Why is there a new logo for Atlassian being upload if you don't even have them listed a a sponsor in the yaml file?

**Comment by drbokko** [comment]
Hello Mike:
- Atlassian requested a logo change for the 2017 event; We are finalising the contract so I thought it would be nice to perform the change as they request.
There is a unique logo file per sponsor unless one would create sponsor profiles with the year in the prefix (as was in the past)

- nine.ch also requested a logo change

- About the png I use the same format as the former logo I found.

**Comment by bridgetkromhout** [comment]
I'm preserving the logo history for old events in https://github.com/devopsdays/devopsdays-web/pull/3713 - when that's in place I'll merge this.

**Comment by MikeRosTX** [comment]
OK, it's all fine.  But Atlassian's logo is not appearing in the preview.
**https://deploy-preview-3709--devopsdays-web.netlify.com/events/2018-zurich/welcome/**

Only reason I suggest changing png to jpg, is because we've seen this behavior before.

**Comment by bridgetkromhout** [comment]
>> We are finalising the contract 

>  Atlassian's logo is not appearing in the preview.

This would imply to me that they'll list the logo when the contract is final.

**Comment by bridgetkromhout** [comment]
Hi, @drbokko - if you rebase off master to resolve the conflict this should be okay to merge now.

**Comment by drbokko** [comment]
@MikeRosTX @bridgetkromhout pages now look as they should

**Comment by bridgetkromhout** [comment]
Well, the new atlassian file has the wrong name, but i'll just merge and then fix. thanks.

**Pull request merged**
