### PR TITLE
[KRK-2022] init changes for the next edition of the event

### PR DESCRIPTION
**Pull request by ivellios**
Hey!

I have prepared the init page for the next event in Krakow.

The list of organizers was already sent, please check it and confirm.

### CODE REVIEW

**Comment by phrawzty** [comment]
AppVeyor failed on
```
error: invalid path 'static/events/2022-krakow/organizers/Jakub_Barc.png:Zone.Identifier'
```
Which is weird because the file is there, the other tests pass, and the preview works just fine. Chalking that up to an AppVeyor issue unrelated to this PR.

**Comment by phrawzty** [comment]
There are `team_member` discrepancies. I sent a message to the `#kraków` on the DOD Slack for clarification.

**Review by phrawzty — APPROVED** [review]

**Comment by ivellios** [comment]
@phrawzty - hugo was generating the files in my local dev environment. I didn't include it in the commits as looked like some sort of temp/generated files. Should I include them anyway? Asking for the future PRs.

**Comment by phrawzty** [comment]
@ivellios Hugo will build the entire website—that's what Hugo does. Please don't try to commit the build artefacts. :)

**Pull request merged**
