### PR TITLE
[POZ-2019] Update event with location and team members

### PR DESCRIPTION
**Pull request by jakubjakubik**
@mazek as the original author can you give your blessing for me to edit the POZ-2019 from now on?

### CODE REVIEW

**Comment by jakubjakubik** [comment]
Circle is not building because of #6625 - once fixed it should be fine :)

**Comment by bridgetkromhout** [comment]
Hi -

This PR adds new organizers for your event. That's great, but please email us at info@devopsdays.org with their names and email addresses. We need to add the new organizers to the email list and to Slack. Then we can merge this PR.

Meanwhile, it would also be good if you could rebase this PR off master, as we've merged your fix for the speaking page. Then the tests should pass. Thanks.

**Comment by jakubjakubik** [comment]
hi,

I've rebased (I think :) but don't have permissions to rerun circle, can you trigger it please?
Marcin emailed the list of updated organisers.

thanks!

**Comment by bridgetkromhout** [comment]
Did you merge upstream master into your branch and push it to github again? I see no evidence of this.

**Comment by jakubjakubik** [comment]
should be fine right now - circle has passed

**Comment by bridgetkromhout** [comment]
Okay, email and Slack updated too.

**Pull request merged**
