### PR TITLE
[2017-Brasilia] Update 2017 logo

### PR DESCRIPTION
**Pull request by adrianovieira**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@adrianovieira I'll go ahead and merge it, but your new logo is not showing up on the main page.
[https://www.devopsdays,org/events/2017-brasilia/](https://www.devopsdays,org/events/2017-brasilia/)

Is that intentional?

**Comment by adrianovieira** [comment]
Hummm! I don't why it not showing up on the main page of the main site.

But the main page in deploy/netlify is showing (https://deploy-preview-2690--devopsdays-web.netlify.com/)

**Comment by adrianovieira** [comment]
Is it possible be a deploy delay (or cache update delay)?

I don't know either.

**Comment by MikeRosTX** [comment]
OK so the merge completed for this PR.
If you look here [https://www.devopsdays.org/](https://www.devopsdays.org/), the logo is updated.
But here [https://www.devopsdays.org/events/2017-brasilia/](https://www.devopsdays.org/events/2017-brasilia/) there is no logo.

**Pull request merged**
