### PR TITLE
[rdu-2023] Enabled program page and created template

### PR DESCRIPTION
**Pull request by jrn00**
uncommented program in main yaml to enable page

created program template to be edited later.

### CODE REVIEW

**Comment by jrn00** [comment]
If there is an issue, my first PR failing linting because one of the speaker file names didn't fit the right format. I changed it and it looks like the PR was updated to reflect.

**Comment by yvovandoorn** [comment]
Hi @jrn00. Need some clarification with the PR. The program lists everything as TBD yet there are a ton of speaker photos being added. maybe take out the images until after the program becomes more concrete?

**Comment by jrn00** [comment]
> Hi @jrn00. Need some clarification with the PR. The program lists everything as TBD yet there are a ton of speaker photos being added. maybe take out the images until after the program becomes more concrete?

Hey @yvovandoorn, the plan was to have the speaker photos ready so a few of us could work on adding them to the program.

If it makes more sense, I can send a PR without the pictures

**Comment by jrn00** [comment]
I'll resubmit with just the program template.

**Pull request closed without merging**
