### PR TITLE
[Cape Town 2017] Add registration URL - Don't merge yet!

### PR DESCRIPTION
**Pull request by adrianmoisey**
**Please don't merge just yet!**
We will ping you when we're ready to merge.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Looks like this has a conflict anyhow, so before we can merge, please do resolve that! Thanks.

**Comment by adrianmoisey** [comment]
Should be fixed now, thanks!

**Comment by adrianmoisey** [comment]
(Still not to be merged though)

**Comment by adrianmoisey** [comment]
This is safe to merge now, thanks!

**Pull request merged**
