### PR TITLE
Add google forms, change ui

### PR DESCRIPTION
**Pull request by VitMosin**
Add google forms, change ui

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@VitMosin can you take care of the conflicts?  Because we cannot move forward until this is resolved..

**Comment by VitMosin** [comment]
It seems i have no access to resolve conflicts. How can i do it?

**Comment by VitMosin** [comment]
And first commit was pushed and merged 17 days ago really. Don't see why it's going to be merged again((

**Comment by bridgetkromhout** [comment]
@VitMosin You could try saving your changes locally, making sure your fork is up to date with the origin, and sending a new pull request with your new changes.

**Comment by MikeRosTX** [comment]
@VitMosin - Have you tried saving your changes locally and making sure your fork is up to date with the origin?  Would you like us to close this PR and you send a new pull request with your new changes when you're ready?

**Comment by VitMosin** [comment]
Yes, please close this PR. I'll create new one.

**Comment by MikeRosTX** [comment]
Closing out PR for now due to some conflicts.

**Conflicting files:**
content/events/2017-moscow/program.md 
content/events/2017-moscow/propose.md 
content/events/2017-moscow/registration.md 
content/events/2017-moscow/speakers.md 
content/events/2017-moscow/sponsor.md 
content/events/2017-moscow/welcome.md 
data/events/2017-moscow.yml

**Pull request closed without merging**
