### PR TITLE
[Boise 2020] Suggested update

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Hi, @tresni! We have updated the suggested language for the code of conduct - see #9006. If you let us know that you approve this PR, we will merge it. Thanks.

### CODE REVIEW

**Comment by tresni** [comment]
Hi @bridgetkromhout I need to take it to the organizing team for approval. Thanks for the heads up.

**Comment by yvovandoorn** [comment]
@tresni thanks for the update. We will hold off on merging until you've communicated with the broader team!

**Comment by bridgetkromhout** [comment]
Hi, @tresni! Please take a look this week so we can finish this update - thanks!

**Comment by tresni** [comment]
Sorry, didn't realize there was a date you guys were looking it.  While consensus via email has been positive, we wanted to discuss at our next F2F meeting in Feb (I believe Feb 20.)  If we need to make a decision sooner, I'll ask for adoption via email.

**Comment by bridgetkromhout** [comment]
Hi @tresni - ah, most events have not needed long deliberation. Take the time your team needs. (Usually it's just that they haven't gotten to it.)

**Comment by bridgetkromhout** [comment]
I'm closing this PR for the moment as we can't merge it for quite some time, and we'll revisit it after Boise has had a chance to confer.

**Comment by tresni** [comment]
Good to merge

**Pull request closed without merging**
