### PR TITLE
[BER-2017] Initial setup for DoD Berlin 2017

### PR DESCRIPTION
**Pull request by gethash**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@gethash the front page logo is not showing up correctly.  See the following:
[https://github.com/devopsdays/devopsdays-web/tree/master/themes/devopsdays-theme#frontpage-logo](https://github.com/devopsdays/devopsdays-web/tree/master/themes/devopsdays-theme#frontpage-logo)

**Comment by gethash** [comment]
Hi Mike,
the logo is there and in the directory. Do you see an error?

**Comment by MikeRosTX** [comment]
@gethash  there seems to be 2 files (logo.jpg and logo.png)

**Comment by MikeRosTX** [comment]
@gethash the should be 2 files the logo and logo-square, so that's correct. Change the *_logo.png_* to *_logo.jpg_*

**Comment by mattstratton** [comment]
To really confuse matters, it needs to be `logo_square.jpg` and `logo.png`. For backwards compatiblity we didn't change logo to jpg yet. 

This seems to show up fine in deploy preview for me.

**Comment by gethash** [comment]
I try to figure whats "wrong" locally

**Comment by gethash** [comment]
Thanks for merging.. Means it was correct, right?

**Pull request merged**
