### PR TITLE
[IST-2017] Added sponsors

### PR DESCRIPTION
**Pull request by funkydorian**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello,

As per the [guidelines](https://github.com/devopsdays/devopsdays-web/blob/master/utilities/README.md#sponsor-logos), sponsor logos must be 200 pixels square. Somewhat ironically, the logo you're deleting in this PR is at least square (though too large), so it will display properly.

Please update this PR by (preferably) uploading a 200 px square logo, or by *not* replacing the one already present.  Thank you.

**Comment by mattstratton** [comment]
200 pix square is the very *minimum*, they don't need to be square anymore, but the shortest side should be 600 px.

**Comment by mattstratton** [comment]
To clarify, the link from @phrawzty says:

```
Sponsor logos

Guidelines regarding sponsor logo files and formatting:

The dimensions of the image file must be at least 200px wide. 600px will look best for high-density display.
The background must be either white or transparent.
All logos will be resized at release time, to 200px wide. Versions for high-density display (ex. Retina) will also be created. It is recommended that you do not use a sponsor logo that is smaller than 200px wide to keep from quality degradation at resize time.
```

**Comment by mattstratton** [comment]
> Somewhat ironically, the logo you're deleting in this PR is at least square (though too large), so it will display properly.

It's actually not too large; it's a size that we want :)

**Comment by mattstratton** [comment]
The best fix, to not rewrite history, is to create a new sponsor, `2017-kloia.yml` and `2017-kloia.png` and add those. That won't rewrite sponsor history for the events that have already used it. The file is fine; just rename it.

**Comment by phrawzty** [comment]
> 200 pix square is the very minimum, they don't need to be square anymore, but the width should be 600 px.

They don't need to be square any more? Neat! Sorry for the incorrect comment - I got so used to pasting this response that I stopped looking at the docs. My fault.

**Comment by bridgetkromhout** [comment]
> The best fix, to not rewrite history, is to create a new sponsor, 2017-kloia.yml and 2017-kloia.png and add those. That won't rewrite sponsor history for the events that have already used it. The file is fine; just rename it.

@mattstratton is correct that we don't want to change the old logo shown in the past site.

I solved it in the preferred way (in https://github.com/devopsdays/devopsdays-web/pull/2587) and then I submitted https://github.com/devopsdays/devopsdays-web/pull/2588 with changes cherry-picked from here.

**Pull request closed without merging**
