### PR TITLE
[CAI-23] Opening CFP 

### PR DESCRIPTION
**Pull request by aameen79**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello @aameen79. Just to keep you updated, the reason this is tagged `do-no-merge` is because we're currently reviewing the proposed changes to the Code of Conduct and will reach out to your team directly outside of this PR.

**Comment by aameen79** [comment]
Dear Daniel,

Many thanks for your continuous support, I suggest an online meeting if you have any inquiries or concerns.

**Comment by aameen79** [comment]
Dears,

We need to get out CFP opened, your prompt response is highly appreciated.

From: Ahmed Ameen
Sent: Sunday, May 14, 2023 12:10 PM
To: 'devopsdays/devopsdays-web' ***@***.***>
Subject: RE: [devopsdays/devopsdays-web] [CAI-23] Opening CFP (PR #12688)

Dear Daniel,

Many thanks for your continuous support, I suggest an online meeting if you have any inquiries or concerns.

**Comment by phrawzty** [comment]
Hello,

Please see the email entitled "request for clarification on PR 12688" sent to the `cairo@` mailing list on 15 May 2023, 14:56 UTC +2.

Thank you.

**Comment by phrawzty** [comment]
@aameen79 Hello. In the interest of opening your CFP, please revert the changes to the Code of Conduct, but leave the rest. We will continue to engage on the CoC separately.

**Review by phrawzty — APPROVED** [review]

**Pull request merged**
