### PR TITLE
2017 beijing

### PR DESCRIPTION
**Pull request by xiaotianguo**
Hi,I have added devopsdayschina official website and update the menu in wecome page,Please help us to review.Thank you.

### CODE REVIEW

**Comment by xiaotianguo** [comment]
Hi @MikeRosTX ,could you help us to review this PR thanks.

**Comment by xiaotianguo** [comment]
Hi @mattstratton Cloud you help us to review this PR thank you.

**Comment by MikeRosTX** [comment]
@xiaotianguo I'm reviewing now.

**Comment by MikeRosTX** [comment]
@xiaotianguo there were conflicts in the following 3 files that I fixed. So  I'm merging it now. Double check the site to make sure everything is in place the way you want it to show up.

content/events/2017-beijing/location.md 
content/events/2017-beijing/welcome.md
data/events/2017-beijing.yml

**Pull request merged**
