### PR TITLE
Update Baltimore home page

### PR DESCRIPTION
**Pull request by nathenharvey**
More links and a logo.

### CODE REVIEW

**Comment by mattstratton** [comment]
As @bridgetkromhout once said to me, "Y U NO GIT SQUASH, BRO?"

**Comment by mattstratton** [comment]
Any particular reason to have both logos? Can you just use the `logo.png`? Or are they different somehow that I cannot see?

**Comment by nathenharvey** [comment]
removed the larger version of the logo.

gave you another PR with everything squashed if you prefer - #551

**Comment by mattstratton** [comment]
I'm just teasing about the squashing.

**Pull request merged**
