### PR TITLE
Use newer Hugo

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by mattstratton** [comment]
I need to do some testing - we had a newer version push out via Appveyor and the build broke.

**Comment by mattstratton** [comment]
Additionally, we now pin the hugo version in https://github.com/devopsdays/devopsdays-web/blob/master/appveyor.yml so that file needs to be added to this PR

**Comment by ghoneycutt** [comment]
Hi @mattstratton I just tested `hugoserver.sh` locally and thought CI would handle the rest. For `hugoserver.ps1`, I looked up that version exists in Cholately.

**Comment by mattstratton** [comment]
I totally get that! I was just curious because when we were floating the version in Appveyor, the latest version broke. If you can update the appveyor file in this PR too, that will be checked and that will help!

**Comment by ghoneycutt** [comment]
Appveyor is updated here

**Comment by ghoneycutt** [comment]
Maybe last time you tried, the package was not pushed to Chocolatey yet.

https://chocolatey.org/packages?q=hugo

**Comment by mattstratton** [comment]
> Appveyor is updated here

well clearly I missed it! Sorry!

I'll check the deploy preview after it's done building. Looking good though!

**Comment by mattstratton** [comment]
Ah,it was floating to `0.66.0` of hugo. So this looks fine. I think we will break on `0.66.0` though.

**Comment by mattstratton** [comment]
FYI this was what happened:

```
Build started
git clone -q --branch=master https://github.com/devopsdays/devopsdays-web.git C:\projects\devopsdays-web
git checkout -qf 038e8b17b1968dbb2eda4587fc1eec6104407b69
Running Install scripts
choco install hugo -y
Chocolatey v0.10.15
Installing the following packages:
hugo
By installing you accept licenses for the packages.
Progress: Downloading hugo 0.66.0... 100%
hugo v0.66.0 [Approved]
hugo package files install completed. Performing other installation steps.
Downloading hugo 64 bit
  from 'https://github.com/gohugoio/hugo/releases/download/v0.66.0/hugo_0.66.0_Windows-64bit.zip'
Progress: 100% - Completed download of C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\hugo\0.66.0\hugo_0.66.0_Windows-64bit.zip (12.69 MB).
Download of hugo_0.66.0_Windows-64bit.zip (12.69 MB) completed.
Hashes match.
Extracting C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\hugo\0.66.0\hugo_0.66.0_Windows-64bit.zip to C:\ProgramData\chocolatey\lib\hugo\tools...
C:\ProgramData\chocolatey\lib\hugo\tools
 ShimGen has successfully created a shim for hugo.exe
 The install of hugo was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\hugo\tools'
Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
hugo version
Hugo Static Site Generator v0.66.0-78C3C78F windows/amd64 BuildDate: 2020-03-03T15:20:46Z
hugo --verbose
INFO 2020/03/04 20:38:36 No translation bundle found for default language "en"
INFO 2020/03/04 20:38:36 Translation func for language en not found, use default.
INFO 2020/03/04 20:38:36 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
INFO 2020/03/04 20:38:36 Using config file: 
Building sites … INFO 2020/03/04 20:38:36 syncing static files to C:\projects\devopsdays-web\public\
ERROR 2020/03/04 20:39:43 render of "page" failed: "C:\projects\devopsdays-web\themes\devopsdays-theme\layouts\talk\single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/events/2019-kiev/speakers/john-willis" is ambiguous
ERROR 2020/03/04 20:39:43 render of "page" failed: "C:\projects\devopsdays-web\themes\devopsdays-theme\layouts\talk\single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/events/2019-montreal/speakers/" is ambiguous
ERROR 2020/03/04 20:39:43 render of "page" failed: "C:\projects\devopsdays-web\themes\devopsdays-theme\layouts\talk\single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/events/2019-oslo/speakers/johan-abildskov" is ambiguous
ERROR 2020/03/04 20:39:43 render of "page" failed: "C:\projects\devopsdays-web\themes\devopsdays-theme\layouts\talk\single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/events/2019-oslo/speakers/leonardo-di-donato" is ambiguous
Total in 78211 ms
Error: Error building site: failed to render pages: render of "page" failed: "C:\projects\devopsdays-web\themes\devopsdays-theme\layouts\talk\single.html:144:15": execute of template failed: template: talk/single.html:144:15: executing "main" at <$.Site.GetPage>: error calling GetPage: page reference "/events/2019-buffalo/speakers/jj-asghar" is ambiguous
Command exited with code -1
```

**Comment by ghoneycutt** [comment]
CircleCI uses cibuilds/hugo instead of jojomi and it lags behind.

**Comment by ghoneycutt** [comment]
That's JJ breaking stuff for you :>

**Comment by mattstratton** [comment]
Yeah, eventually we will update the scripts to use `cibuilds/hugo` as well but there's some syntax changing in docker for that to work, hence why we haven't done it yet.

**Comment by somatorio** [comment]
i can look later for using cibuilds instead of jojomi, last time i tried it just needed a few tweaks

**Comment by somatorio** [comment]
```
$ docker run -tip 1313:1313 -v $(pwd):/home/circleci/project:cached -e HUGO_THEME=devopsdays-theme -e HUGO_BASEURL="http://localhost:1313" --name hugo-server --entrypoint "" cibuilds/hugo:0.67.0 hugo server --watch --bind ""

                   |  EN
-------------------+--------
  Pages            |  4271
  Paginator pages  |     2
  Non-page files   |    41
  Static files     | 14374
  Processed images |     0
  Aliases          |   278
  Sitemaps         |     1
  Cleaned          |     0

Built in 121121 ms
Watching for changes in /home/circleci/project/{archetypes,content,data,static,themes}
Watching for config changes in /home/circleci/project/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address )
Press Ctrl+C to stop

```

:D

**Comment by mattstratton** [comment]
Thanks @somatorio ! I would say let's put that in a separate PR so that I can merge this one for now.

**Comment by mattstratton** [comment]
oof. so I didn't quite notice this, but next time we need to make sure that ALL versions are the same.

I understand that Circle doesn't have the latest images always, but since it's a key part of our test matrix, we cannot go higher than what they have. Right now we have a weird mix of versions in the test chain and that's not awesome. I'll watch for this next time (I think it's okay to just let it go right now)

**Comment by ghoneycutt** [comment]
💯 we've always had multiple versions which agreed is not great. One docker image everywhere and that corresponding version would be awesome.

**Comment by mattstratton** [comment]
well, netlify and appeveyor don't use docker so it won't be 100% the same, but I suggest we figure out how to consolidate on one docker image (cibuilds/hugo) with what @somatorio suggested, and then we make sure that the following are all the same version (even if there is a newer one available for one of them):

- circleCI
- docker scripts
- Appveyor
- netlify

:)

(thanks for helping with this, btw!)

**Pull request merged**
