### PR TITLE
[KC-2017] Updating organizers for new theme and adding GA

### PR DESCRIPTION
**Pull request by barkerd427**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Let me review the details before merging.

**Comment by MikeRosTX** [comment]
Set to do-not-merge. Want to give @barkerd427 a chance to resize the images to 600x600 or minimum 300x300.

**Comment by barkerd427** [comment]
There's a bunch of info missing and pictures aren't perfect. We'll fix
those later. Let me know if anything else is messed up or missing. Thanks,
Mike.

**Comment by MikeRosTX** [comment]
Leaving **AS IS** and @barkerd427 will fix later.

**Pull request merged**
