### PR TITLE
🚧 Cleaning up the SP-2019 organizers commits

### PR DESCRIPTION
**Pull request by nathenharvey**
Signed-off-by: Nathen Harvey <nathen.harvey@gmail.com>

### CODE REVIEW

**Comment by nathenharvey** [comment]
@camilafrasan I am trying to condense #5975 down into one clean commit.  I believe this commit does just that but would appreciate it if you could verify before we merge this.  #5975 touched files outside of Sao Paulo but I am guessing you did not want to do that.

**Comment by nathenharvey** [comment]
I'm actually not sure this is any good either.  I'm going to close it out.

**Comment by camilafrasan** [comment]
> @camilafrasan I am trying to condense #5975 down into one clean commit. I believe this commit does just that but would appreciate it if you could verify before we merge this. #5975 touched files outside of Sao Paulo but I am guessing you did not want to do that.

@nathenharvey You're right, please, you can close and I'll upload new PR.

**Comment by nathenharvey** [comment]
@camilafrasan I closed this one.  I'll let you close #5975 and re-open a new PR when you have it ready.  Let me know if I can be of any help.

**Pull request closed without merging**
