### PR TITLE
[OSL-19] Oslo speakers

### PR DESCRIPTION
**Pull request by bruvik**
* First round of speakers for oslo
* please don't merge yet, I want to see the preview

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@bruvik let us know when you're happy with the preview and we'll merge.

**Comment by bridgetkromhout** [comment]
You probably want to edit https://deploy-preview-8294--devopsdays-web.netlify.com/events/2019-oslo/program/ramez-hanna/ to add either dashes or newlines.

Also, the "program" link doesn't currently work (you will want to use https://github.com/devopsdays/devopsdays-web/blob/master/utilities/add_program.sh to create it before linking to it).

**Comment by bruvik** [comment]
Hi @MikeRosTX (or whoever sees this first) - time to merge now! Thanks

**Comment by bridgetkromhout** [comment]
Here's an example of putting your Ignite talks on the program: https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-chicago.yml#L493-L513

**Pull request merged**
