### PR TITLE
Aws new logo

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Is this what they want used in all future events going forward?

**Comment by ghoneycutt** [comment]
Yes, they no longer use the old logo.

**Comment by bridgetkromhout** [comment]
Okay, I've done the necessary renaming for the old use of the logo in https://github.com/devopsdays/devopsdays-web/pull/4158. Please update from upstream into your fork and change this PR to upload this new one with the name "aws", which is now available for your use. Let me know if you need me to close this PR and do it for you. Thanks.

**Comment by ghoneycutt** [comment]
Thanks @bridgetkromhout

**Pull request merged**
