### PR TITLE
[WARSAW-2017] Event added.

### PR DESCRIPTION
**Pull request by turkus**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@turkus before we can merge this PR we need you or someone from your team to sens a complete list of all your local organisers, because you team email has 5 and 3 from this PR are missing. 

Please send the email to info@devopsdays.org

first name, last name, email

**Comment by turkus** [comment]
@MikeRosTX emails sent.

**Comment by bridgetkromhout** [comment]
I have emailed you, @turkus, about what we need in order to merge this pull request (the missing email addresses, and your name on the organizer list in this PR). Thanks.

**Comment by turkus** [comment]
Hi @bridgetkromhout yes, thanks. I'm currently waiting for response from organizers.

**Comment by turkus** [comment]
@bridgetkromhout well, I'm just only a programmer who pushes a piece of code on organizers demand. Organizers won't place me to the organizer list. So what should I do then?

**Comment by bridgetkromhout** [comment]
> @bridgetkromhout well, I'm just only a programmer who pushes a piece of code on organizers demand. Organizers (they said) won't place me to the organizer list. So what should I do then?

I will reach out to them via email - thanks.

**Comment by bridgetkromhout** [comment]
Thanks; we got the necessary emails.

**Comment by turkus** [comment]
@bridgetkromhout thank you so much.

**Pull request merged**
