### PR TITLE
[DC-2021] Update sponsorship link

### PR DESCRIPTION
**Pull request by trevorbryant**
Updating sponsorship link for DevOpsDays DC chapter.

### CODE REVIEW

**Comment by mattstratton** [comment]
This PR is way too messy - please close it, rebase, and submit again. 

There are 1700+ changed files in this PR :)

**Comment by robbkidd** [comment]
I've got an update. To confirm, we open PRs from branches in our forks, right? I recall a time when events were expected to merge PRs to their own main branches that are kept up-to-date with upstream's main and then open PRs from the event forks' main. … I could also be very confused.

**Comment by robbkidd** [comment]
@mattstratton How about [1 file changed](https://github.com/devopsdays/devopsdays-web/pull/10576) this time? 😁

**Comment by mattstratton** [comment]
Hmm seems to still have all the other stuff in this PR image

**Comment by robbkidd** [comment]
Er, I meant over on a different PR: #10573 

_This_ PR should remain closed and encircled by a ring of salt and sigils.

**Pull request closed without merging**
