### PR TITLE
Update 2018-fortaleza.yml

### PR DESCRIPTION
**Pull request by gb8may**
Add "Ingressos" link to tickets

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2018] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@gb8may, we cannot merge this PR until the url is fixed and it is valid.
image

**Comment by gb8may** [comment]
This URL will be able on 07/30, when we will begun to sell tickets

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
CompTIA Network+ | Ethical Hacking Foundation
Fortinet NSE1 | DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 | Puppet ID: PPT0005371

2018-07-26 20:15 GMT-03:00 Mike Rosado <notifications@github.com>:

**Comment by MikeRosTX** [comment]
OK, I'll merge AS IS.

**Comment by gb8may** [comment]
Thank you Mike!

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
CompTIA Network+ | Ethical Hacking Foundation
Fortinet NSE1 | DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 | Puppet ID: PPT0005371

**Pull request merged**
