### PR TITLE
Remind Ignite presenters that there are no presenter notes

### PR DESCRIPTION
**Pull request by jasonious**
For my first Ignite, I asked the organizer 15 minutes before stage time
where I'd be able to see my notes.  I was then informed that Ignite talks
don't get Presenter Notes, which was quite a surprise.

Letting the Ignite presenters know this ahead of time, as well as reminding
them on the day of, should help eliminate future surprises.

Also mentioned that animations and videos do not work either

### CODE REVIEW

**Comment by mattstratton** [comment]
The bit about animations etc depend on how the event does it. Not sure we want to assume all events will be removing them.

**Comment by mattstratton** [comment]
Likewise, it's possible for an event to construct the ignites in a way where presenter notes are supported.

**Comment by phrawzty** [comment]
> Likewise, it's possible for an event to construct the ignites in a way where presenter notes are supported.

To be fair, the doc specifically suggests *impressive*, which doesn't support speaker notes. Perhaps some clarification around that particular topic might be helpful?

**Comment by KrisBuytaert** [comment]
This is what I put in most of my ignite speaker prep mails 

"We need PDF files , with 20 slides maximum , our tool does the
autoforwarding. 

You can test run them with 
impressive -a 15 yourslides.pdf

"

**Comment by mattstratton** [comment]
I think given that the direction of the doc is assuming use of `impressive` this probably makes sense. We have never used it at Chicago so I didn't even notice it was mentioned :)

I'm okay with merging this given that.

**Comment by bridgetkromhout** [comment]
Right. We can do some clarification around _how_ to run the Ignites (Minneapolis doesn't use impressive, for example), but in the vast majority of cases, notes and animations aren't going to work.

Thanks, @jasonious!

**Pull request merged**
