### PR TITLE
2016-boston: program, keynote speakers, opsgenie

### PR DESCRIPTION
**Pull request by masteinhauser**
- Big update with the full schedule planned out
- One of our speaker profiles done (and actually working!)
- Adding in a new sponsor.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
* Are you sure you want me to merge a program full of links that 404 because they're not found? We could just merge it without all these links to stuff that doesn't exist yet:
```
<a href="/events/2016-boston/program/elliot-murphy">....</a>
```

* Your speaker stuff for Jill is good, but I haven't fixed https://github.com/devopsdays/devopsdays-web/issues/365 yet so you probably want to add either an image of her or a blank image (sorry).

**Comment by masteinhauser** [comment]
Honestly, I'm not terribly opposed to the 404's since I'm planning to actually follow up quickly and get those pages built out. Getting the scheduled sessions up and timeline is likely ore useful than nothing at all. Of course, that does mean another PR will be coming soon.

Yeahhhhh, that kept me confused for quite a while. I can just do the 1x1px hack for now. :sadpanda:

**Comment by masteinhauser** [comment]
I just tossed a script together to generate this data from an export off of papercall. I'll add speakers, bios, and the picture hack.

**Comment by bridgetkromhout** [comment]
Okay, merged as requested. Hopefully I can merge another one shortly!

**Comment by bridgetkromhout** [comment]
> I just tossed a script together to generate this data from an export off of papercall. I'll add speakers, bios, and the picture hack.

Hah. In your next PR. Since this one's merged. :)

**Comment by masteinhauser** [comment]
@bridgetkromhout Okay! Got my script working and new PR is ready. Thank you!
https://github.com/devopsdays/devopsdays-web/pull/623

**Pull request merged**
