### PR TITLE
[AMS2019] Add Sarvesh as speaker

### PR DESCRIPTION
**Pull request by thomaskrag**

### CODE REVIEW

**Comment by phrawzty** [comment]
You appear to _remove_ `content/events/2019-amsterdam/speakers/stacey-jenkins.md`—is that intentional?

**Comment by thomaskrag** [comment]
@phrawzty , yup he's not joining the conference. Thanks for the sanity check.

**Comment by bridgetkromhout** [comment]
As you're removing a speaker by removing `content/events/2019-amsterdam/speakers/stacey-jenkins.md`, please also remove `content/events/2019-amsterdam/program/stacey-jenkins.md` and `static/events/2019-amsterdam/speakers/stacey-jenkins.jpg`.

**Comment by thomaskrag** [comment]
@bridgetkromhout Done. :)

**Comment by phrawzty** [comment]
> Remove traces of Stacey

That's vaguely menacing, haha!

**Pull request merged**
