### PR TITLE
[bna-2019] updated logo, added sponsor, added ga tracking code

### PR DESCRIPTION
**Pull request by notsureifkevin**
@MikeRosTX is there anything else I need to do in order to update the frontpage logo?

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@notsureifkevin the one on the main page will use **_logo-square.jpg_** by default, but **_logo.jpg_** needs to be referenced in **_welcome.md_**.

**Comment by notsureifkevin** [comment]
> @notsureifkevin the one on the main page will use **_logo-square.jpg_** by default, but **_logo.jpg_** needs to be referenced in **_welcome.md_**.

will png files be picked up as well?

**Comment by MikeRosTX** [comment]
No must be **_jpg_**.
https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/README.md#frontpage-logo

**Comment by MikeRosTX** [comment]
welcome.md has not been updated, you need to remove the following that remarks it out.

**Comment by MikeRosTX** [comment]
**_welcome.md_** has not been updated, you need to remove the following that remarks it out.

""

**Pull request merged**
