### PR TITLE
[AMS-2020] Add initial speakers

### PR DESCRIPTION
**Pull request by PaulusTM**
This is de initial speaker list.
Please hold for team validation.

### CODE REVIEW

**Comment by MikeRosTX** [comment]
We don't hold PRs open as WIP, of it's going to take a a few days of approval by the team, then close out this PR and reopen it once once approval is reach over Slack or email.

**Comment by PaulusTM** [comment]
This PR is ready to merge

**Comment by MikeRosTX** [comment]
> This PR is ready to merge

I thought it was too, but not yet. Please follow guidelines by correcting speaker images.
https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#speaker-page-fields

**Comment by PaulusTM** [comment]
Fixed the image extension to PNG.

**Comment by yvovandoorn** [comment]
Thanks for settling on PNG @PaulusTM

I'll merge this for now as I know Amsterdam is itching to launch a program, but please try to:

- adhere to 600x600 (or 1000x1000), the guidelines has the 600x600 as a recommendation but consider it a very strong recommendation -
- settle on an uniform size & format for photos - e.g. 600x600 or 1000x1000 for *all* images. Current PR has it all different sizes
- try to retroactively fix the photos you have with the above two asks.

**Pull request merged**
