### PR TITLE
Script to generate new organizer fields (+README update)

### PR DESCRIPTION
**Pull request by bridgetkromhout**
This is some basic bash that generates the entries for new organizers. I minimally updated the README too. This is MVP and doesn't prompt for every conceivable field; we could update the README to link to the relevant doc. @mattstratton, please take a look and see if this is okay to add as MVP.

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Looks great @bridgetkromhout.  If you may satisfy my curiosity :wink:,... Why not add the fields for **github**, **website**, and **facebook**?

**Comment by bridgetkromhout** [comment]
> Looks great @bridgetkromhout. If you may satisfy my curiosity 😉,... Why not add the fields for github, website, and facebook?

I don't want people who are setting up their organizer list to stop midway because they don't have so much info at hand. Their local team can add extra fields later if needed.

**Comment by MikeRosTX** [comment]
>I don't want people who are setting up their organizer list to stop midway because they don't have so
>much info at hand. Their local team can add extra fields later if needed.

Point understood. But you add the empty fields, so whomever is coming behind them can fill them out?

**Comment by mattstratton** [comment]
@mikerostx imho adding blank fields would imply they are required. 

I think at this point since the tooling is "add only" and not "edit later" this is fine.

**Pull request merged**
