### PR TITLE
[CHA-2019] Updating Aaron Sachs pic & info

### PR DESCRIPTION
**Pull request by asachs01**
I've updated the CHA 2019 yaml with my information and added my pic to to the pics dir for the event.

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Can the image be reduced to **600x600px** as noted in **Organizer Field** then re-upload it?
https://github.com/devopsdays/devopsdays-web/blob/master/themes/devopsdays-theme/REFERENCE.md#organizer-fields

**Comment by bridgetkromhout** [comment]
> Can the image be reduced to 600x600px as noted in Organizer Field

Nice to have, but image processing handles enough of this in terms of how it displays.

**Comment by asachs01** [comment]
Eeek. @MikeRosTX I'll probably have to resubmit. I didn't pick up on reference until you linked it. The image was showing up fine locally, but I'm looking a bit squished on the site. :grimacing:

**Comment by MikeRosTX** [comment]
It's fine to leave AS IS, they look fine,
https://www.devopsdays.org/events/2019-chattanooga/contact/

Maybe future ones like speakers make sure to follow the guide.

**Pull request merged**
