### PR TITLE
[Victoria-2019] updated Daitan logo

### PR DESCRIPTION
**Pull request by BGnoinski**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
What is the purpose of adding this new logo?  Because it will not make it any bigger as you can see from the preview.

https://deploy-preview-6839--devopsdays-web.netlify.com/events/2019-victoria/welcome/
image

**Comment by BGnoinski** [comment]
@MikeRosTX  The sponsor asked me to update the logo was all. I am content closing the PR if it's not going to change anything.

**Comment by MikeRosTX** [comment]
@BGnoinski proceed to close.

**Comment by bridgetkromhout** [comment]
@BGnoinski i think the confusion came in because you need to update https://github.com/BGnoinski/devopsdays-web - "This branch is 1273 commits behind devopsdays:master"

**Comment by BGnoinski** [comment]
@bridgetkromhout This PR was based off of a branch(2019-victoria-yyj), not master which had been rebased.

I just repushed it if you want to take a look. But as Mike pointed out the new logo didn't change anything.

**Pull request closed without merging**
