### PR TITLE
[LA-2018] Initial commit for Los Angeles 2018

### PR DESCRIPTION
**Pull request by omargohan**
- Initial commit for Los Angeles 2018

### CODE REVIEW

**Comment by kmugrage** [comment]
@omargohan Please send an email to info@devopsdays.org with the names and email addresses of the organizers who should be on the 2018 mailing list. 

It looks like you've lost a few organizers, is this accurate? If so, please include a list of those people in that same email so we can adjust Slack access.

Thanks!

**Comment by bridgetkromhout** [comment]
The main thing we need at this point is Omar Alva's email address. /cc @irabinovitch

**Comment by irabinovitch** [comment]
@bridgetkromhout omargohan@gmail.com

**Comment by omargohan** [comment]
@kmugrage, let me double check the list of organizers. As @irabinovitch pointed out, my email is omargohan@gmail.com

**Comment by bridgetkromhout** [comment]
Great, thanks.

**Pull request merged**
