### PR TITLE
[OSL-2017] first commit

### PR DESCRIPTION
**Pull request by steinim**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@steinim what version of Hugo are you using?

Can you check on the following?  Because TravisCI build is failing with 1 error...

npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by MikeRosTX** [comment]
@steinim also need to enable **conduct** on the navbar.

**Comment by steinim** [comment]
@MikeRosTX It builds now, and it also builds locally on my machine. The hugo version is v0.18.1 so that should be OK. Enabled conduct on the navbar, but it seems odd if that was the reason for build failed. Will you merge?

**Comment by MikeRosTX** [comment]
@steinim update any of pages pertinent to navbar to include team email address **_organizers-oslo-2017@devopsdays.org_**.

**Pull request merged**
