### PR TITLE
[NYC] Add links to the CFP

### PR DESCRIPTION
**Pull request by nathenharvey**
Adds the URL for the CFP to the data file.

### CODE REVIEW

**Comment by nathenharvey** [comment]
@kuritz for your consideration

**Comment by kuritz** [comment]
Thanks @nathenharvey!

**Review by kuritz — APPROVED** [review]

**Comment by MikeRosTX** [comment]
@kuritz are we good to merge?

**Comment by kuritz** [comment]
@MikeRosTX yes

**Pull request merged**
