### PR TITLE
[SANTIAGO-2025] first commit resolved (#14340)

### PR DESCRIPTION
**Pull request by kokedevops**
SANTIAGO-2025 first commit of the event, issues from the previous commit are resolved

### CODE REVIEW

**Comment by kokedevops** [comment]
@nimbinatus Hello Laura, very good day to you.
I decided to start again to avoid errors, follow your instructions and the changes were sent in the pull https://github.com/devopsdays/devopsdays-web/pull/14366

**Comment by phrawzty** [comment]
👋 The PR looks clean enough. Before you can "claim" a date, you need a signed contract from the venue where the conference will be held. Please send a copy of that contract to info@devopsdays.org for review (original language, presumably Spanish, is fine).

**Comment by nimbinatus** [comment]
Sorry for the delay, @kokedevops! Had some personal things to handle. As @phrawzty mentioned ^^, once that's done, this can merge.

**Comment by kokedevops** [comment]
Hi @nimbinatus  and @phrawzty  Good morning, Good afternoon, Good evening when you read me :)

Update the application to remove the date, unfortunately without payment we will not have room, everyone requires advance payments, so first we must find who will sponsor. We remain attentive to the upload, thank you very much.

**Pull request merged**
