### PR TITLE
[LA-2022] Update site pages

### PR DESCRIPTION
**Pull request by omargohan**
**Summary of changes:**

- Updating `Description` on all pages.
- Updating `sponsor`'s content.
- Adding `cfp` to welcome page.
- Updating data in `los-angeles-2022.yml` including cfp dates, links, team members info and `sponsor_levels`

### CODE REVIEW

**Comment by omargohan** [comment]
I don't see the parsing [error](https://github.com/devopsdays/devopsdays-web/pull/10565/checks?check_run_id=3500485413#step:7:9).

```
Parse Error: <!--
```

Am I missing something here?

**Comment by omargohan** [comment]
Errors have been fixed. :)

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Fix url for **CFP** & **Registration** on the **Welcome.md** page that don't resolve.

**Comment by omargohan** [comment]
@MikeRosTX are you referring to these links?

[cfp](https://docs.google.com/forms/d/e/1FAIpQLSewxucXuZ5nmZYX-nBitrmnr1ZA-O7oc33kheNvoRw1ufEbgg/viewform)
[registration](https://register.socallinuxexpo.org/reg6/)

I do see both links working. Could you please provide more information here?

Thanks,

**Comment by MikeRosTX** [comment]
> @MikeRosTX are you referring to these links?
> 
> [cfp](https://docs.google.com/forms/d/e/1FAIpQLSewxucXuZ5nmZYX-nBitrmnr1ZA-O7oc33kheNvoRw1ufEbgg/viewform)
> [registration](https://register.socallinuxexpo.org/reg6/)
> 
> I do see both links working. Could you please provide more information here?
> 
> Thanks,

My mistake, not CFP.

Navbar all resolve, it's **Location** (begins line 21) and **Registration** (begins line 41) on the **welcome.md** that resolves to a 404 page and not the same url as Navbar.

**Comment by brynak** [comment]
Thank you for your concern. Can you please let us publish this PR? It's been 5 days now, and our site already has broken links we're trying to fix with this PR. Our broken links should not be a reason to hold our PR, please.

**Pull request merged**
