### PR TITLE
[Baku-2019] Added 2 new sponsors

### PR DESCRIPTION
**Pull request by NasehBadalov**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
Please send a list of full name and emails of organizers being added, and the one being deleted.

**Comment by MikeRosTX** [comment]
Please send a list of full name and emails of organizers being added, and the one being deleted.

**Comment by bridgetkromhout** [comment]
Please send the email addresses for your team to info@devopsdays.org.
Zəhmət olmasa komandanızın e-poçt ünvanlarını info@devopsdays.org elektron poçtuna göndərin.

**Comment by bridgetkromhout** [comment]
Current status: waiting for Vusal to answer email from @serhatcan.

**Comment by serhatcan** [comment]
Ask and answered. Moving on with updates.

**Pull request merged**
