### PR TITLE
[PDX-2020] Adding CFP and registration links

### PR DESCRIPTION
**Pull request by jyee**
Adding the registration and CFP links

### CODE REVIEW

**Comment by jyee** [comment]
Don't merge yet. Iframe sizing isn't right.

**Comment by glasnt** [comment]
@jyee Your latest revision looks good to me on the netlify preview. Are you happy with the wider iframe and happy to merge?

**Comment by jyee** [comment]
@glasnt Let's hold until another PDX organizer gives a 👍

**Comment by nvwls** [comment]
:+1:

**Comment by dev-dull** [comment]
👍 looks good

**Pull request merged**
