### PR TITLE
[OSL-2017] Slides for all ignites and links to videos

### PR DESCRIPTION
**Pull request by steinim**
*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2017] Add Bluth Company as a sponsor`*

### CODE REVIEW

**Comment by phrawzty** [comment]
Hello! I strongly suspect that the PDFs should be in https://github.com/devopsdays/devopsdays-assets but I'm not entirely sure. I'll ask on Slack. :)

**Comment by steinim** [comment]
I've moved the files to assets.devopsdays.org [OSL-2017 slides from ignite talks](https://github.com/devopsdays/devopsdays-assets/pull/25)

**Comment by mattstratton** [comment]
Oh whoops. Good catch @bridgetkromhout  :)

**Comment by bridgetkromhout** [comment]
Hey, @steinim - this is close! You want to put the slides as a link in the frontmatter for the talk page, though. Use the "pdf" type: https://github.com/devopsdays/devopsdays-theme/blob/master/REFERENCE.md#talk-page-fields

**Comment by steinim** [comment]
Ok. Thanks. Should be all good now :)

**Comment by MikeRosTX** [comment]
Merging since links all look good. Changes were done as requested.

**Pull request merged**
