### PR TITLE
[Los Angeles 2020] Initial Post

### PR DESCRIPTION
**Pull request by CMeza99**
Getting DevOps Day LA 2020 off the ground.

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi! Welcome back! This is a good start. We have a few things to fix:
- we need at least three listed organizers
- the email we'll list is los-angeles@devopsdays.org. You'll need to send the email addresses of at least your three listed team members to info@devopsdays.org so we can set this up

**Comment by CMeza99** [comment]
:+1: We are having our first meeting soon. I will have more organizers soon. :)

**Comment by bridgetkromhout** [comment]
Great to hear, @CMeza99! FYI we don't keep PRs for events open here without merging them, so if it's going to be days, go ahead and close this one and re-open when you've got at least three organizers listed! Thanks and excited to see Los Angeles happening again.

**Comment by CMeza99** [comment]
Hi @bridgetkromhout . I have sent the list of emails and updated the PR. Thanks!

**Comment by bridgetkromhout** [comment]
Thanks - looks great. I updated email and Slack.

**Pull request merged**
