### PR TITLE
Refactor data directory to use subfolders and update Hugo to 0.121.2

### LINKED ISSUE #13658: Move schedule out of main data event yaml
If we want to have to have schedule automation, it would be better to have autogenerated files seperate from the general file.
Let say by having Pretalx output the schedule in DoD Hugo Schedule YAML format and then having a release push the YAML file to git

### LINKED ISSUE #13683: Refactor data/events directory
This was part of the redesign but i think we need it now. 

Currently structure is a flat directory with a single yaml for every event. 

New would be like this:

`data/events/2024-chicago/main.yml`

Which allows us to break up the yaml files like...
`data/events/2024-chicago/program.yml` etc 

First step is to figure out how big of a change the path changes will be. 

Assuming that is no big deal, then refactor the program page to use the `program.yml` if it exists, and fall back to the main if not. 

This is needed for #13658

### LINKED ISSUE #13692: Refactor "past" partial
Right now the range of years is hardcoded… That should be able to be made dynamic… I believe it should be able to take current year plus one year

### PR DESCRIPTION
**Pull request by mattstratton**
## _ATTENTION: Do NOT merge this PR until coordinating with Matty, etc._

This adjusts the data directory to use subfolders per event, which will let the YAML files be broken up and worked on individually.

Fixes #13683 
Fixes #13658 
Fixes #13692

### Changes in this PR

- Move data files from `data/events/YYYY-CITY.yml` to `data/events/YYYY/CITY/main.yml`
- Add support to break out portions of the config file into separate files (this change is not made to any existing events; and it's optional). Currently supported are
  - `main.yml`
  - `program.yml`
  - `sponsors.yml`
  - `organizers.yml`
- Update Hugo to `0.121.2`
- Updates the "past events" page to use the same global queries as other event lists, and removes the hardcoded year range (#13692)
- moves a lot of duplicate code into "functions" in some partials, which is definitely making the whole thing a lot DRY-er
- Various internal cosmetic improvements for code readability 
- The "speaking" page now directly links to either the event's propose page or direct CFP link for the listed events 
- update utility scripts for new data file paths, including sample/template for use in scripts 
- Update documentation to refer to the new data file paths

### Steps post-merge

This is what I think is going to need to be done by anyone who has a data file "in flight" for their event, prior to them.

When the commits in this PR are applied, it fundamentally will "delete" any data file in the old format (bc it also creates it, but a commit doesn't say "move this file" it's a "delete and create"). So let's say I have a branch with a modified version of `2024-chicago.yml`. It's not going to take my version of that file and rename it to "main.yml", it's going to delete that file and create a "main.yml" with the contents from the commit in this PR.

now that said, the contents of that data file in this PR at the time of merge will be the same as whatever is currently in `main` (or at least really close to it!). we really really don't want any non-merged PRs hanging around when we merge this one. So we want to close as many PRs as possible prior to the merge. Granted, right now one of the worst offenders is me (the Chicago draft PR) which I can close without merging and I'll keep it in my local branch.

#### Local branches not in a PR

When someone rebases, etc, it might overwrite their changes in their data files. highly recommended to suggest to folks to make a copy of their data file prior to rebasing, just in case they have to recreate those changes. I will test this out myself with my own local branch right after this merges, so I can create some quick "step by step" stuff.

### CODE REVIEW

**Comment by mattstratton** [comment]
okay, i can see the maintainer made a commit 2 weeks ago, so it might just be temporary issue...

**Comment by mattstratton** [comment]
In the PR, I have commented out the windows test for now

**Comment by mattstratton** [comment]
Since I think this is getting close to being merged, I thought I would run the performance metrics on the current site and the new structure/changes.

Here's the build and metrics on current `main`:
```
Template Metrics:

     cumulative       average       maximum      cache  percent  cached  total
       duration      duration      duration  potential   cached   count  count  template
     ----------      --------      --------  ---------  -------  ------  -----  --------
   20.75917357s    2.094981ms     128.609ms          8        0       0   9909  partials/head.html
  17.099770613s    4.777806ms  130.157667ms          0        0       0   3579  speaker/single.html
   14.61617827s    4.515347ms   46.895917ms          0        0       0   3237  talk/single.html
   7.458997378s    3.325455ms   45.158875ms          0        0       0   2243  event/single.html
   7.136999001s  209.911735ms  710.736375ms          0        0       0     34  blog/single.html
   6.878396259s     694.156µs  119.797375ms         78        0       0   9909  partials/head_includes.html
   6.093885875s   28.609792ms   60.444167ms          0        0       0    213  speakers/single.html
   6.030957417s  125.644946ms  604.303875ms        100       98      47     48  partials/future.html
   4.438374206s   12.260702ms   46.787917ms          0        0       0    362  welcome/single.html
   3.853148845s     399.953µs    35.42875ms         15       19    1874   9634  partials/sponsors.html
   2.593837344s     261.765µs      40.191ms          2        0       0   9909  partials/head/seo.html
   2.353886501s     6.39643ms    25.58225ms          5        0       0    368  partials/welcome.html
   2.079144749s   10.092935ms   46.599541ms          0        0       0    206  program/single.html
   1.898186957s  158.182246ms   196.69525ms          0        0       0     12  events/single.html
   1.757406584s  146.450548ms  158.818792ms         54        0       0     12  partials/past.html
   828.199441ms      84.098µs   10.577292ms         60        0       0   9848  partials/events/event_navbar.html
   667.860239ms    2.295052ms    8.539417ms          0        0       0    291  shortcodes/event_logo.html
   495.756499ms       50.03µs    48.77625ms        100      100    9908   9909  partials/footer.html
    322.08409ms      32.504µs    2.465333ms         77        0       0   9909  partials/footer_scripts.html
   222.841846ms      22.488µs     716.334µs         83        0       0   9909  partials/google_analytics.html
   207.489344ms      20.939µs    1.671583ms         98        0       0   9909  partials/google_tag_manager.html
   130.700498ms    4.840759ms  123.795917ms          0        0       0     27  _internal/_default/rss.xml
    71.933209ms   71.933209ms   71.933209ms          0        0       0      1  index.html
    70.566123ms    4.704408ms   42.301625ms          0        0       0     15  _default/single.html
    70.374438ms       7.102µs    1.420291ms        100        0       0   9909  partials/meta.html
    57.684916ms   57.684916ms   57.684916ms          0        0       0      1  _internal/_default/sitemap.xml
    57.294673ms     156.116µs     831.791µs          0        0       0    367  shortcodes/list_organizers.html
     44.91131ms       4.532µs    4.567208ms        100      100    9908   9909  partials/global_navbar.html
    41.622083ms   41.622083ms   41.622083ms          0        0       0      1  sponsor/single.html
    36.948083ms   36.948083ms   36.948083ms          0        0       0      1  speaking/single.html
     26.57978ms      16.266µs     470.541µs          0        0       0   1634  shortcodes/event_link.html
    21.206042ms   21.206042ms   21.206042ms        100        0       0      1  partials/speaking.html
    19.407193ms      19.465µs     229.833µs          0        0       0    997  shortcodes/email_organizers.html
    12.351681ms      33.564µs     156.458µs         58        0       0    368  partials/events/cta.html
     8.904466ms      33.102µs     725.709µs          0        0       0    269  shortcodes/cfp_dates.html
     7.643006ms       26.63µs     274.125µs          0        0       0    287  shortcodes/event_map.html
     6.539572ms       9.159µs     272.083µs          0        0       0    714  _internal/alias.html
     6.239125ms    6.239125ms    6.239125ms          0        0       0      1  section/events.rss.xml
     5.515292ms    5.515292ms    5.515292ms        100        0       0      1  partials/sponsors-accepted.html
     5.035879ms      14.899µs      90.166µs          0        0       0    338  shortcodes/event_start.html
     3.748375ms    3.748375ms    3.748375ms          0        0       0      1  section/speaking.rss.xml
      3.27301ms      10.228µs      73.209µs          0        0       0    320  shortcodes/event_twitter.html
     3.008124ms      11.394µs         147µs          0        0       0    264  shortcodes/event_location.html
     2.758666ms     689.666µs    1.297416ms          0        0       0      4  section/blog.html
     2.630332ms       9.101µs      99.875µs          0        0       0    289  shortcodes/event_end.html
     2.518042ms     503.608µs    2.495333ms          0        0       0      5  shortcodes/emoji.html
     1.435625ms    1.435625ms    1.435625ms        100        0       0      1  partials/toc.html
     1.238958ms    1.238958ms    1.238958ms          0        0       0      1  section/blog.rss.xml
      731.458µs      21.513µs     122.917µs          0        0       0     34  blog/summary.html
      584.124µs      14.977µs      86.791µs          0        0       0     39  shortcodes/email_proposals.html
      401.833µs     401.833µs     401.833µs          0        0       0      1  404.html
      363.584µs      90.896µs     289.834µs         38        0       0      4  partials/blog_pagination.html
       214.96µs      35.826µs      80.875µs          0        0       0      6  _internal/shortcodes/figure.html
        214.5µs        42.9µs      85.125µs          0        0       0      5  _internal/shortcodes/youtube.html
       207.34µs         566ns      32.959µs          0        0       0    366  shortcodes/list_core.html
      199.875µs     199.875µs     199.875µs        100        0       0      1  partials/heading_link.html
      159.667µs      31.933µs     125.125µs          0        0       0      5  shortcodes/google_form.html
      122.958µs     122.958µs     122.958µs          0        0       0      1  shortcodes/list_core_active.html
      110.333µs     110.333µs     110.333µs          0        0       0      1  shortcodes/privacy_policy.html
          110µs         110µs         110µs          0        0       0      1  shortcodes/list_core_emeritus.html
      106.042µs      53.021µs     102.667µs          0        0       0      2  _internal/shortcodes/param.html
      103.875µs     103.875µs     103.875µs          0        0       0      1  shortcodes/registration_start.html
      101.666µs        3.63µs      98.125µs          0        0       0     28  _default/list.html
       98.958µs      98.958µs      98.958µs          0        0       0      1  shortcodes/list_core_advisory.html
       77.459µs      77.459µs      77.459µs          0        0       0      1  shortcodes/registration_end.html


                   |  EN
-------------------+--------
  Pages            |  9936
  Paginator pages  |     3
  Non-page files   |    67
  Static files     | 16282
  Processed images |     0
  Aliases          |   714
  Sitemaps         |     1
  Cleaned          |     0

Total in 10857 ms
```

and here's this branch:

```
Template Metrics:

     cumulative       average       maximum      cache  percent  cached  total
       duration      duration      duration  potential   cached   count  count  template
     ----------      --------      --------  ---------  -------  ------  -----  --------
  3m3.373183833s   18.494521ms   196.89625ms          8        0       0   9915  partials/head.html
  2m16.58451567s   42.194783ms  204.887083ms          0        0       0   3237  talk/single.html
  1m40.081237677s   44.539936ms    203.8365ms          0        0       0   2247  event/single.html
  1m21.742712735s   22.839539ms  145.230583ms          0        0       0   3579  speaker/single.html
  58.664893887s    5.916782ms  121.221917ms         78        0       0   9915  partials/head_includes.html
  46.877088883s  128.783211ms  275.532792ms          0        0       0    364  welcome/single.html
   38.71198962s    3.904386ms  139.624958ms          2        0       0   9915  partials/head/seo.html
  26.905591128s   72.717813ms  199.211792ms          5        0       0    370  partials/welcome.html
  25.670460962s     2.66291ms  106.707667ms         15       19    1876   9640  partials/sponsors.html
  23.903243891s    2.410816ms  115.285083ms         83        0       0   9915  partials/google_analytics.html
  23.376024523s    2.357642ms  115.333792ms         77        0       0   9915  partials/footer_scripts.html
  23.216744232s    2.341577ms   93.639167ms         98        0       0   9915  partials/google_tag_manager.html
  22.424224521s    2.275646ms   93.201958ms         60        0       0   9854  partials/events/event_navbar.html
  18.454166166s   86.639277ms  200.276167ms          0        0       0    213  speakers/single.html
   7.319531496s   35.531706ms  187.230542ms          0        0       0    206  program/single.html
   6.883315458s  202.450454ms  685.362792ms          0        0       0     34  blog/single.html
    5.79720525s  120.775109ms   579.76425ms        100       98      47     48  partials/future.html
   4.584379534s    2.785163ms   93.063083ms          0        0       0   1646  shortcodes/event_link.html
   4.581717113s      55.729µs   11.596583ms          0        0       0  82213  partials/functions/get-event-data.html
   2.933901073s    7.929462ms   93.525459ms         58        0       0    370  partials/events/cta.html
   2.525417788s    2.527945ms   61.061625ms          0        0       0    999  shortcodes/email_organizers.html
   1.564921082s   130.41009ms  211.566666ms          0        0       0     12  events/single.html
   1.423272711s    4.857586ms   63.661958ms          0        0       0    293  shortcodes/event_logo.html
   1.254399464s    3.399456ms   72.410792ms          0        0       0    369  shortcodes/list_organizers.html
   1.223672209s    3.599035ms   62.569375ms          0        0       0    340  shortcodes/event_start.html
   997.060336ms     3.09646ms   64.508541ms          0        0       0    322  shortcodes/event_twitter.html
    937.38071ms    3.484686ms  113.921583ms          0        0       0    269  shortcodes/cfp_dates.html
   865.315919ms    3.253067ms   113.87425ms          0        0       0    266  shortcodes/event_location.html
   858.046876ms    2.246196ms   25.652292ms        100        0       0    382  partials/functions/get-all-events.html
    846.76966ms    2.909861ms   49.063625ms          0        0       0    291  shortcodes/event_end.html
   843.665753ms    2.939601ms   49.325167ms          0        0       0    287  shortcodes/event_map.html
   640.635834ms   33.717675ms  576.378167ms        100        0       0     19  partials/functions/get-upcoming-events.html
   562.085702ms       56.69µs   55.409291ms        100      100    9914   9915  partials/footer.html
   239.310919ms   15.954061ms   60.777333ms          0        0       0     15  _default/single.html
   165.746833ms  165.746833ms  165.746833ms          0        0       0      1  index.html
   127.153877ms    4.709402ms  120.044792ms          0        0       0     27  _internal/_default/rss.xml
   110.930208ms  110.930208ms  110.930208ms          0        0       0      1  sponsor/single.html
   108.305251ms   27.076312ms    53.23175ms          0        0       0      4  section/blog.html
    60.890652ms       6.141µs    1.205709ms        100        0       0   9915  partials/meta.html
    56.948083ms   56.948083ms   56.948083ms          0        0       0      1  speaking/single.html
    55.950708ms   55.950708ms   55.950708ms        100        0       0      1  partials/speaking.html
    55.572875ms   55.572875ms   55.572875ms          0        0       0      1  _internal/_default/sitemap.xml
    52.751458ms   52.751458ms   52.751458ms        100        0       0      1  partials/sponsors-accepted.html
    51.367418ms        5.18µs    5.000167ms        100      100    9914   9915  partials/global_navbar.html
    49.256209ms    1.262979ms     2.67325ms          0        0       0     39  shortcodes/email_proposals.html
    23.838168ms    1.833705ms     2.05175ms        100        0       0     13  partials/functions/get-tbd-events.html
      9.58975ms     9.58975ms     9.58975ms          0        0       0      1  section/speaking.rss.xml
     7.374417ms    7.374417ms    7.374417ms          0        0       0      1  section/events.rss.xml
     6.525665ms       9.114µs      241.75µs          0        0       0    716  _internal/alias.html
         1.81ms        1.81ms        1.81ms          0        0       0      1  shortcodes/registration_start.html
     1.552417ms    1.552417ms    1.552417ms        100        0       0      1  partials/toc.html
     1.502042ms      50.068µs     225.459µs          6        0       0     30  partials/functions/get-cfp-url.html
     1.370541ms     274.108µs       1.352ms          0        0       0      5  shortcodes/emoji.html
     1.203291ms    1.203291ms    1.203291ms          0        0       0      1  section/blog.rss.xml
      1.14475ms     1.14475ms     1.14475ms          0        0       0      1  shortcodes/registration_end.html
      800.625µs      23.547µs     124.375µs          0        0       0     34  blog/summary.html
      464.499µs      16.589µs     181.042µs          0        0       0     28  _default/list.html
       367.75µs      367.75µs      367.75µs          0        0       0      1  404.html
       298.25µs      74.562µs     172.708µs         38        0       0      4  partials/blog_pagination.html
      209.669µs         569ns      45.209µs          0        0       0    368  shortcodes/list_core.html
      204.541µs       34.09µs      83.542µs          0        0       0      6  _internal/shortcodes/figure.html
      195.749µs      39.149µs        70.5µs          0        0       0      5  _internal/shortcodes/youtube.html
      170.334µs     170.334µs     170.334µs        100        0       0      1  partials/heading_link.html
      133.124µs      26.624µs         100µs          0        0       0      5  shortcodes/google_form.html
       129.75µs      129.75µs      129.75µs          0        0       0      1  shortcodes/list_core_active.html
      119.833µs     119.833µs     119.833µs          0        0       0      1  shortcodes/list_core_emeritus.html
      117.584µs      58.792µs     111.584µs          0        0       0      2  _internal/shortcodes/param.html
      106.042µs     106.042µs     106.042µs          0        0       0      1  shortcodes/privacy_policy.html
      103.583µs     103.583µs     103.583µs          0        0       0      1  shortcodes/list_core_advisory.html


                   |  EN
-------------------+--------
  Pages            |  9942
  Paginator pages  |     3
  Non-page files   |    67
  Static files     | 16286
  Processed images |     0
  Aliases          |   716
  Sitemaps         |     1
  Cleaned          |     0

Total in 41854 ms
```

it's... a lot slower. I'll have to do some digging.

**Comment by mattstratton** [comment]
some context on performance:

current build is basically about 10 seconds

new build is 41 seconds

I should look at the difference on netlify

**Comment by mattstratton** [comment]
On Netlify:

current branch (deploy preview) Build time: 2m 2s. Total deploy time: 2m 3s
new branch: Build time: 1m 55s. Total deploy time: 1m 57s

so actually it's not that much different ...

**Comment by mattstratton** [comment]
Please note! Do NOT merge this PR, even after it's been reviewed and approved. This needs to be merged at a certain time and after the data files have been re-updated with any changes since etc.

**Review by glasnt — APPROVED** [review]
Approved, based on spot check of preview

**Pull request merged**
