### PR TITLE
[LA-2024] Add Sharif to organizers list

### PR DESCRIPTION
**Pull request by mrwacky42**
**Summary of changes:**

- Add myself to list of organizers

   
**Tested:**

- Locally using Hugo

@omargohan - Can you vouch for me :D

### CODE REVIEW

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
Need someone from the LA team to approve this PR and send Sharif's email to the Core team.

**Comment by irabinovitch** [comment]
approved.

**Review by MikeRosTX — APPROVED** [review]

**Comment by MikeRosTX** [comment]
@mrwacky42 we would like for you to provide us your email address to add you to los-angeles@devopsdays.org and t our global devopsdays Slack workspace.

**Review by MikeRosTX — CHANGES_REQUESTED** [review]
@mrwacky42 we would like for you to provide us your email address to add you to [los-angeles@devopsdays.org](mailto:los-angeles@devopsdays.org) and to our global devopsdays Slack workspace.

**Comment by MikeRosTX** [comment]
We are leaving PR unmerged due to lack of response of sending Sharif's full name and his email address to info@devopsdays.org as a new organizer. Once we receive this email, we will proceed in merging this PR.

**Comment by omargohan** [comment]
@MikeRosTX , I have sent an email to info@devopsdays.org

Please let me know if you need anything else.

Thank you!

**Review by MikeRosTX — APPROVED** [review]

**Comment by mrwacky42** [comment]
Sorry, I was traveling. Thanks team for getting this done in my absence.

**Pull request merged**
