### PR TITLE
[2017-charlotte] Added sponsors

### PR DESCRIPTION
**Pull request by hemersonvarela**

### CODE REVIEW

**Comment by MikeRosTX** [comment]
@hemersonvarela we unable to merge due to the following:

Conflicting files
data/sponsors/actifio.yml 
static/img/sponsors/actifio.png

Check that everything looks correct local or create a new branch.

**Comment by MikeRosTX** [comment]
@hemersonvarela this is what it's giving us as a suggestion for you to try on your end:

**Step 1:** From your project repository, check out a new branch and test the changes.
git checkout -b hemersonvarela-master master
git pull https://github.com/hemersonvarela/devopsdays-web.git master


**Step 2:** Merge the changes and update on GitHub.
git checkout master
git merge --no-ff hemersonvarela-master
git push origin master

**Comment by mattstratton** [comment]
Yeah, somehow your fork didn't have activio, so your commits are for it as a new file, but it's alr ash in the repo. You can try to pull and merge from our master to your fork and then merge into the PR.

**Comment by mattstratton** [comment]
Yeah, your fork is over 1,000 commits behind master. You should always pull or fetch from our master before doing a PR or this will happen :)

**Comment by hemersonvarela** [comment]
Thanks everybody for your help.
please, ignore this PR

**Pull request closed without merging**
