### PR TITLE
Update to Hugo 0.81.0

### PR DESCRIPTION
**Pull request by mattstratton**
Signed-off-by: Matt Stratton <matt.stratton@hey.com>

This updates the version of Hugo; it could provide better build performance as well.

### CODE REVIEW

**Comment by mattstratton** [comment]
hugo build time with this version:
`Total in 104658 ms`

previous build:
`Total in 91822 ms`

so, uh, it's slower?

**Comment by mattstratton** [comment]
It's about ten seconds slower with this version, but that is slightly anecdata maybe since only one build?

**Comment by MikeRosTX** [comment]
> It's about ten seconds slower with this version, but that is slightly anecdata maybe since only one build?

I know 10 secs is not much difference, but I would not go backwards unless the new build provides some features that would benefit us. Just my .02¢.

**Comment by mattstratton** [comment]
The main reason to update is that this is the version people are likely pulling down. We're pretty behind on versions so as long as it's not causing bugs, we should get ourselves updated. 

TBH one of my concerns is that I am on this version of hugo locally, so developing against it when we have an older version in prod could cause issues.

**Comment by bridgetkromhout** [comment]
I would suggest merging this since those of us who use hugo for multiple projects are already on this version locally.

**Pull request merged**
